### ISSUE TITLE
time.rs not included in sgx_tstd

### ISSUE THREAD

**Issue by akhilles** [apache/teaclave-sgx-sdk#104]
`Cargo.toml` for `sgx_tstd` includes `src/time/mod.rs` but not `src/time.rs`. The leads to
 "file not found for module time" error

**Comment by dingelish** [comment]
Oh. Thank you!

**Comment by dingelish** [comment]
And time/duration.rs not exist.

**Comment by dingelish** [comment]
Fixed in 2ba1d4ae282c78de4009256c1a23a5c691c4ab50. Is this correct?

**Comment by akhilles** [comment]
Yeah, it compiles now. However, is the include key necessary? Cargo defaults to follow ‘.gitignore’ rules when include/exclude is missing, which seems perfectly fine.

**Comment by dingelish** [comment]
Which keys are unnecessary? Let me see if we can remove them. Thanks!
