### ISSUE TITLE
dependency error with third_party/ring 0.13 (possibly fixed in ring >= 0.14)

### ISSUE THREAD

**Issue by brenzi** [apache/teaclave-sgx-sdk#122]
I'm getting a dependency error since I put a cargo workspace at the root of my repo
https://github.com/scs/substraTEE-worker/tree/brenzi-ra

```
error: failed to select a version for `ring`.
    ... required by package `libp2p-secio v0.7.0`
    ... which is depended on by `libp2p v0.7.0`
    ... which is depended on by `substrate-consensus-common v2.0.0 (https://github.com/paritytech/substrate?rev=6e67eff0653677d3d01980ca822c4b8a227914a3#6e67eff0)`
    ... which is depended on by `substrate-client v2.0.0 (https://github.com/paritytech/substrate?rev=6e67eff0653677d3d01980ca822c4b8a227914a3#6e67eff0)`
    ... which is depended on by `substrate-consensus-aura-primitives v2.0.0 (https://github.com/paritytech/substrate?rev=6e67eff0653677d3d01980ca822c4b8a227914a3#6e67eff0)`
    ... which is depended on by `substratee-node-runtime v2.0.0 (https://github.com/scs/substraTEE-node?tag=M1#fbfa785e)`
    ... which is depended on by `substratee_client v1.0.0 (/home/abrenzikofer/substraTEE-worker/client)`
versions that meet the requirements `^0.14` are: 0.14.6, 0.14.5, 0.14.4, 0.14.3, 0.14.2, 0.14.1, 0.14.0

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.13.2 (https://github.com/baidu/rust-sgx-sdk#0acdfa35)`
    ... which is depended on by `rustls v0.13.0 (https://github.com/baidu/rust-sgx-sdk#0acdfa35)`
    ... which is depended on by `substratee_worker_enclave v1.0.0 (/home/abrenzikofer/substraTEE-worker/enclave)`
```

I've found [a remark](https://www.reddit.com/r/rust/comments/7zln3a/trying_to_use_ring_compilation_error_after_just/dupc1ua?utm_source=share&utm_medium=web2x), that ring >0.13 should avoid this error.

Any chance you could update to 0.14.x?

Or do you see a workaround?

**Comment by dingelish** [comment]
Not ever seen this before. I can upgrade it in third_party, and/or maintain a fork like before. Which one do you prefer?

**Comment by brenzi** [comment]
My preference are separate forks. Do you see a chance to PR your changes upstream?
thanks a lot for your maintenance.

**Comment by dingelish** [comment]
https://github.com/briansmith/ring/issues/775

Brian and I have some discussion here. And later I decided to maintain my own forks.

**Comment by dingelish** [comment]
Sorry about the late reply. I'm traveling in China from Shanghai to Beijing for BlueHat talk and Defcon Village. I'll get it forked asap.

**Comment by piotr-roslaniec** [comment]
I've encountered similar issue when working with `samplecode/ue-ra`:

```
$ make
make -C ./enclave/
make[1]: Entering directory '/root/src/ue-ra-server/enclave'
cargo build --release
    Updating git repository `https://github.com/baidu/rust-sgx-sdk`
    Updating crates.io index
    Updating git repository `https://github.com/elichai/ring.git`
    <redacted>
error: failed to select a version for `ring`.
    ... required by package `rustls v0.13.0 (https://github.com/baidu/rust-sgx-sdk?rev=v1.0.8#c4f443fa)`
    ... which is depended on by `ueRA v1.0.0 (/root/src/ue-ra-server/enclave)`
versions that meet the requirements `^0.13.2` are: 0.13.2

the package `ring` links to the native library `ring-asm`, but it conflicts with a previous package which links to `ring-asm` as well:
package `ring v0.14.6 (https://github.com/elichai/ring.git?rev=sgx-0.14.6#1454e91f)`
    ... which is depended on by `crypto v0.1.0 (/root/src/crypto)`
    ... which is depended on by `tools v0.1.0 (/root/src/tools)`
    ... which is depended on by `ueRA v1.0.0 (/root/src/ue-ra-server/enclave)`

failed to select a version for `ring` which could resolve this conflict
Makefile:44: recipe for target 'libenclave.a' failed
make[1]: *** [libenclave.a] Error 101
make[1]: Leaving directory '/root/src/ue-ra-server/enclave'
Makefile:162: recipe for target 'enclave' failed
make: *** [enclave] Error 2
```
I've tried to create a workaround for this conflict, but `ring@sgx-0.14.6` does not export features required by `rustls@v0.13.0`:
```
# /root/rust-sgx-sdk/third_party/rustls
$ cargo build
    Updating crates.io index
error: failed to select a version for `ring`.
    ... required by package `rustls v0.13.0 (/root/rust-sgx-sdk/third_party/rustls)`
versions that meet the requirements `^0.14.6` are: 0.14.6

the package `rustls` depends on `ring`, with features: `rsa_signing` but `ring` does not have these features.


failed to select a version for `ring` which could resolve this conflict
```
Reproduced [here](https://github.com/baidu/rust-sgx-sdk/compare/v1.0.8...piotr-roslaniec:v1.0.8-ring-0.14.6)

**Comment by dingelish** [comment]
Just forked ring to ring-sgx here
https://github.com/mesalock-linux/ring-sgx

tests passed. working on rustls now.

**Comment by brenzi** [comment]
Thank you very much for this new fork. 
As it is I unfortunately can't use it yet because:

My crate depends on 
```
rustls = { git = "https://github.com/baidu/rust-sgx-sdk", features = ["dangerous_configuration"]}
```
which today would depend on 
```
ring = { path = "../ring", version = "0.13.2", features = ["rsa_signing"] }
```
so if I want to use your new fork, I have to fork rustls myself. No problem, but rustls also depends on
```
sct = { path = "../sct" }
```
which itself depends on
``` 
ring = { version = "0.13.2", path = "../ring" }
```

So the actual state of baidu-repo vs new per-crate forks is quite confusing.
The quick solution for me would be if I could rely solely on per-crate forks, but I'd need `rustls` and `sct` as well (probably along with all their dependencies).

**Comment by dingelish** [comment]
i have done porting ring/rustls/sct/webpki/webpki-roots in the mesalock-linux organization 

show you a use case later :-)

**Comment by brenzi** [comment]
Strange, I can only find a https://github.com/mesalock-linux/rustls/ fork which doesn't depend on https://github.com/mesalock-linux/ring-sgx, but the original on crates.io. Is your port on some branch?

**Comment by dingelish** [comment]
branch = "mesalock_sgx"

https://github.com/mesalock-linux/rustls/tree/mesalock_sgx

**Comment by brenzi** [comment]
adding the following patch solved this issue for me, together with the sgx-forks mentioned above

In the top workspace Cargo.toml, add:
```
[patch.crates-io]
ring = { git ="https://github.com/mesalock-linux/ring-sgx" }
```
