### ISSUE TITLE
bugreport: Enclave_t.h

### ISSUE THREAD

**Issue by bradyjoestar** [apache/teaclave-sgx-sdk#125]
Currently the import file of Enclave_t.h is:
```
#include "time.h"
#include "inc/stat.h"
#include "sys/uio.h"
#include "inc/stat.h"
```

Maybe there is some bug in generating tool?  Maybe it is:
```
#include "time.h"
#include "sys/stat.h"
#include "sys/uio.h"
#include "sys/stat.h"
```

**Comment by dingelish** [comment]
hmmmm

I think it might be something related to current EDL files.

**Comment by bradyjoestar** [comment]
sure. I'll try to solve it in several days.:ok_hand:
