### ISSUE TITLE
sgx-tcrypto-helper depends on third_party libs which clashes with forked libs

### ISSUE THREAD

**Issue by brenzi** [apache/teaclave-sgx-sdk#127]
I'm moving all my third_party dependiencies to your new forks on mesalock-linux. However, there is one inconsistency:

`cargo tree` gives me
```
├── sgx_tcrypto_helper v1.0.8 (https://github.com/baidu/rust-sgx-sdk#f17a7929)
│   ├── itertools v0.8.0
│   │   └── either v1.5.2 (*)
│   ├── serde v1.0.84 (https://github.com/baidu/rust-sgx-sdk#f17a7929)
│   │   └── sgx_tstd v1.0.8 (https://github.com/baidu/rust-sgx-sdk#f17a7929)
```

this way cargo thinks there are two `sgx_tstd` libs and I get errors:

```
error: duplicate lang item in crate `sgx_tstd`: `f32_runtime`.
  |
  = note: first defined in crate `sgx_tstd`.
```

could you maintain sgx_tcrypto_helper as its own repository depending on the new forks?

**Comment by dingelish** [comment]
ok. do you mean an isolated repo for sgx_tcrypto_helper? :-)

**Comment by dingelish** [comment]
https://github.com/mesalock-linux/sgx_tcrypto_helper

try this!

**Comment by brenzi** [comment]
thanks a lot!
