### ISSUE TITLE
rust-sgx-sdk community

### ISSUE THREAD

**Issue by piotr-roslaniec** [apache/teaclave-sgx-sdk#131]
Is there any community around `baidu/rust-sgx-sdk`? I think this project is fairly popular and I'd like to get in touch with other developers. Would you consider for example running [gitter.im]( https://gitter.im)?

**Comment by dingelish** [comment]
Good idea! I just created one and add the badge to Readme!

**Comment by dingelish** [comment]
[![Gitter](https://badges.gitter.im/rust-sgx-sdk/community.svg)](https://gitter.im/rust-sgx-sdk/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by piotr-roslaniec** [comment]
That's great, thanks!
