### ISSUE TITLE
Logging environment in enclave

### ISSUE THREAD

**Issue by electronix** [apache/teaclave-sgx-sdk#134]
Hello,

do you know a way to use the `log` crate inside an enclave? Adding
```
env_logger = { git = "https://github.com/mesalock-linux/env_logger-sgx", default-features = false, features = ["mesalock_sgx"] }
```
to the Cargo.toml in the enclave, I get errors like `String not found in this scope`.

Thanks in advance

**Comment by dingelish** [comment]
Just add another [example](samplecode/logger) on env_logger's usage.

**Comment by electronix** [comment]
Thanks @dingelish!! 
The sample code works perfectly and the README is very clear.

I was missing the `TCSPolicy = 0` and the `sgx_env.edl`.

**Comment by brenzi** [comment]
@dingelish:  It seems that logging somehow got broken in v1.1.0

If I apply the following patch to teaclave-sgx-sdk tag=v1.1.0
```
diff --git a/samplecode/logger/enclave/Cargo.toml b/samplecode/logger/enclave/Cargo.toml
index 95e2550d..120a5e52 100644
--- a/samplecode/logger/enclave/Cargo.toml
+++ b/samplecode/logger/enclave/Cargo.toml
@@ -15,7 +15,7 @@ sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
 sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }

 [dependencies]
-log = { git = "https://github.com/mesalock-linux/log-sgx" }
+log = { tag = "sgx_1.1.0", git = "https://github.com/mesalock-linux/log-sgx" }
 env_logger = { git = "https://github.com/mesalock-linux/env_logger-sgx" }

 [patch.'https://github.com/apache/teaclave-sgx-sdk.git']

```
then logging doesn't work anymore. Although the commit is the same:
https://github.com/mesalock-linux/log-sgx/commit/1f02c0fffc360b9efb6cd319f402c4a2b28d96e7

**Comment by dingelish** [comment]
@brenzi 
It's interesting. I can confirm that the enclave can build with your patch, but cannot print log to console. I guess the reason is that there are "two different `log`". The one without `tag` is initiated by env_logger, while the other with `tag` is not. But for some unknown reason, the env variable `RUST_LOG` only affects the `log` with `tag` which is not associated with env_logger.

**Comment by tehsunnliu** [comment]
Hello everyone!
I've added a logger in the untrusted part and it's working as expected, when I try to add the logger in the trusted part (enclave) the logger doesn't print anything on the console.  However, when I comment `env_logger()::init()` from the application part, the enclave logger appears. It seems I cannot use `env_logger()::init()` in both enclave and application simultaneously.
Is there any way to achieve this?
