### ISSUE TITLE
Rust 2018 edition

### ISSUE THREAD

**Issue by tomtau** [apache/teaclave-sgx-sdk#136]
https://doc.rust-lang.org/stable/edition-guide/rust-2018/edition-changes.html

A lot of rust-sgx-sdk uses `try!` etc.

it would be nice to have it in the new edition's idiomatic code.

**Comment by akhilles** [comment]
@dingelish If you’re okay with moving to Rust 2018 edition, I can submit a PR for this. I’ve already ported a good amount of `rust-sgx-sdk` code to 2018 edition in my fork.

**Comment by dingelish** [comment]
@akhilles Sure! I'd like to! I'm really overburdened recently. Sorry!

**Comment by tomtau** [comment]
It seems this commit migrated quite a bit of the codebase: https://github.com/baidu/rust-sgx-sdk/commit/888c0a3e734e2d0d26a16d726cac59236fcedca1

**Comment by dingelish** [comment]
I think 9de4680fe6adc7a9ab3cb4df7e8b998a5debeeb5 can close this issue!

**Comment by tomtau** [comment]
awesome!
