### ISSUE TITLE
sgx_tcrypto: create signature with ECDSA

### ISSUE THREAD

**Issue by puzzlewolf** [apache/teaclave-sgx-sdk#139]
In the `sgx_tcrypto` crate, there are functions to create a private (`sgx_tcrypto::rsgx_calculate_ecdsa_priv_key`) and a public (`sgx_tcrypto::rsgx_ecc256_calculate_pub_from_priv`) ecc256/ecdsa key.

I did not find a sign or encrypt function, like for rsa (e.g. `sgx_tcrypto::rsgx_rsa3072_sign_msg`). 

Is there a recommended way to create an ecdsa signature in an enclave?

**Comment by elichai** [comment]
https://github.com/baidu/rust-sgx-sdk/blob/master/sgx_tcrypto/src/crypto.rs#L2281

**Comment by puzzlewolf** [comment]
nice :) 

Sorry I didn't see it before. It is somehow not listed in the documentation generated by running `cargo doc` in  sgx_tcrypto, specifically it is not listed when viewing `sgx_tcrypto/target/doc/sgx_tcrypto/index.html`.

**Comment by puzzlewolf** [comment]
So, it turns out, the function you referenced is not `pub`, so it is not accessible (and also it does not end up in the documentation).
But I found [`sgx_tcrypto::SgxEccHandle`](https://github.com/baidu/rust-sgx-sdk/blob/07adab206e7507c2ea4c41c6ba2a1037015e852b/sgx_tcrypto/src/crypto.rs#L1874), which provides everything related to ecc256/ecdsa :)
