### ISSUE TITLE
Intel RA breaking changes on 7/2/2019

### ISSUE THREAD

**Issue by clangenb** [apache/teaclave-sgx-sdk#142]
https://github.com/intel/sgx-ra-sample#v30

**Comment by dingelish** [comment]
I have working samples on the V5 API. Should we switch to the new API, or using new samples for the new APIs?

**Comment by clangenb** [comment]
Thanks for the fast reply. Working V5 API samples is fine for us.

We are working with Mutual RA. If possible a soonish upload of such a sample would be awesome.

**Comment by dingelish** [comment]
No problem. I can quickly provide a mutual-ra example in another directory like mutual-ra-v5. It collects spid and api key from `bin/spid.txt` and `bin/key.txt`. Is this ok?

**Comment by clangenb** [comment]
Perfect!
Thanks, mate!

**Comment by dingelish** [comment]
Fixed in f28d3ca99b5967f856f141e28c9914aec8fde621

Please help me test it! Thanks!

**Comment by dingelish** [comment]
the old apis seem not working anymore. I'll switch to V5 in all of RA based samples.

**Comment by dingelish** [comment]
One minute. sigrl request has a bug

**Comment by clangenb** [comment]
No worries, still reading through the code and looking for our api key. :D

**Comment by dingelish** [comment]
Fixed in a193ce9f5f2384ef17da8db61da92fefc6d38739.

**Comment by dingelish** [comment]
And instructions for added in Readme in e68d3bbdb66e59790dcc0f3a0d43fb05e08872bc

**Comment by dingelish** [comment]
Squashed these commits to 95c24d065fb3a50ba416a15a2318965e0c19e913 :-) You can see the changes in a commit

**Comment by clangenb** [comment]
Thanks dingelish.

I got it partly to run. At the moment we get an invalid api key error, while retriving the intel_sigrl, which is most likely due to the key not being correctly linked to the spid.

However, this is an issue on our end. Thanks for the very fast and competent fix!

**Comment by clangenb** [comment]
Got it to work!

Anyone having the same problem: Key and SPID need to be made at:
https://api.portal.trustedservices.intel.com/EPID-attestation
