### ISSUE TITLE
Migrate RA API from user cert auth to API subscription keys?

### ISSUE THREAD

**Issue by h4x3rotab** [apache/teaclave-sgx-sdk#145]
Just noticed the latest change in Intel Remote Attestation API ([link](https://github.com/intel/sgx-ra-sample/blob/master/CHANGES.md))

> Switch from user certificate authentication to API subscription keys per the Attestation Service for Intel SGX API Documentation, version 5.

Intel has closed auth certificate uploading and my old certs are expired. Do we need to change the rust sdk as well?

Here is the major change to adopt subscription key based auth from the official RA example:
https://github.com/intel/sgx-ra-sample/commit/946abce058e585ada750f722dab6440083565ded

**Comment by h4x3rotab** [comment]
Oh, nevermind. Just found the updated code here:
https://github.com/baidu/rust-sgx-sdk/commit/7a2303a1af55221a6270d777c5461a1db3988829

**Comment by dingelish** [comment]
Glad you found it! If you still prefer the previous API, please submit a license update request at
https://software.intel.com/en-us/form/updating-your-service-provider-certificate

Good luck!
