### ISSUE TITLE
Support `dbg!` macro

### ISSUE THREAD

**Issue by tomtau** [apache/teaclave-sgx-sdk#147]
it makes it easier for quick print-debugging: https://doc.rust-lang.org/std/macro.dbg.html

**Comment by dingelish** [comment]
Supported by switch sgx_tstd to edition!

See https://github.com/baidu/rust-sgx-sdk/blob/master/samplecode/hello-rust/enclave/src/lib.rs#L75 for usage!

**Comment by tomtau** [comment]
Awesome!
