### ISSUE TITLE
undefined reference to `posix_memalign`

### ISSUE THREAD

**Issue by chuanbowen** [apache/teaclave-sgx-sdk#15]
Hi,
   I'm trying to run the sample code using `make SGX_MODE=SIM`. Then errors:

make -C ../../sgx_ustdc/ 2> /dev/null
make[1]: Entering directory `/root/sgx/rust-sgx-sdk/sgx_ustdc'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/sgx/rust-sgx-sdk/sgx_ustdc'
cp ../../sgx_ustdc/libsgx_ustdc.a ./lib
LINK =>  bin/app
make -C ./enclave/
make[1]: Entering directory `/root/sgx/rust-sgx-sdk/samplecode/helloworld/enclave'
cargo build --release
    Finished release [optimized] target(s) in 0.0 secs
cp ./target/release/libhelloworldsampleenclave.a ../lib/libenclave.a
make[1]: Leaving directory `/root/sgx/rust-sgx-sdk/samplecode/helloworld/enclave'
make -C ../../compiler-rt/ 2> /dev/null
make[1]: Entering directory `/root/sgx/rust-sgx-sdk/compiler-rt'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/sgx/rust-sgx-sdk/compiler-rt'
cp ../../compiler-rt/libcompiler-rt-patch.a ./lib
Fuck Fucker
./lib/libenclave.a(sgx_tstd-47265592e650a341.sgx_tstd2-8794749acdeababf8ded62cd435a787f.rs.rcgu.o): In function `__rg_alloc':
sgx_tstd2-8794749acdeababf8ded62cd435a787f.rs:(.text.__rg_alloc+0x41): undefined reference to `posix_memalign'
./lib/libenclave.a(sgx_tstd-47265592e650a341.sgx_tstd2-8794749acdeababf8ded62cd435a787f.rs.rcgu.o): In function `__rg_realloc':
sgx_tstd2-8794749acdeababf8ded62cd435a787f.rs:(.text.__rg_realloc+0x83): undefined reference to `posix_memalign'
collect2: error: ld returned 1 exit status

rust version:
`rustc 1.26.0-nightly (392645394 2018-03-15)`

**Comment by dingelish** [comment]
Please refer to the [patch](https://github.com/baidu/rust-sgx-sdk/blob/master/dockerfile/patch) and the [Dockerfile](https://github.com/baidu/rust-sgx-sdk/blob/master/dockerfile/Dockerfile) (line 60 to 65) to build a Intel SGX SDK with memalign.

**Comment by chuanbowen** [comment]
My OS version: centos 7
kernel version:3.10.0-514.21.1.el7.x86_64.

**Comment by chuanbowen** [comment]
It works. Thanks @dingelish .
But, I want to know why. Could you give me some info. I got nothing from google.

**Comment by dingelish** [comment]
grep 'USE_MALLOC_DEPRECATED' in the tlibc's source codes
for some reason Intel disabled some APIs in their sdk. maybe Intel believes some APIs should be deprecated.

**Comment by chuanbowen** [comment]
@dingelish  Thanks!!!
