### ISSUE TITLE
sgx_unwind fails to compile on centos:7.6

### ISSUE THREAD

**Issue by akhilles** [apache/teaclave-sgx-sdk#158]
I realize only Ubuntu is officially supported, but I've been using `rust-sgx-sdk` on CentOS 7 without any problems for a while now. I recently updated to `v1.0.9` from `v1.0.8` and am no longer able to compile. I'm not sure how much effort it is to get `sgx_unwind` to work on CentOS but I would greatly appreciate your help on this.

Running the following commands in `libunwind` directory before `cargo build` seems to be a temporary fix:
```
autoreconf --force --install
./configure
make distclean
```

error log:
```
command did not execute successfully: "make" "INCDIR=/app/sgx_unwind/../sgx_unwind/libunwind" "-j5"
expected success, got: exit code: 2



--- stderr
++ dirname /app/sgx_unwind/../sgx_unwind/libunwind/autogen-linux.sh
+ srcdir=/app/sgx_unwind/../sgx_unwind/libunwind
+ '[' -z /app/sgx_unwind/../sgx_unwind/libunwind ']'
++ pwd
+ ORIGDIR=/app/sgx_unwind/target/debug/build/sgx_unwind-6f700cc2242b9b40/out/libunwind
+ cd /app/sgx_unwind/../sgx_unwind/libunwind
+ autoreconf -v --install
autoreconf: Entering directory `.'
autoreconf: configure.in: not using Gettext
autoreconf: running: aclocal
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
autoreconf: configure.in: tracing
autoreconf: running: libtoolize --copy
aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
src/Makefile.am:277: warning: whitespace following trailing backslash
automake: warning: autoconf input should be named 'configure.ac', not 'configure.in'
autoreconf: Leaving directory `.'
+ cd /app/sgx_unwind/target/debug/build/sgx_unwind-6f700cc2242b9b40/out/libunwind
+ CFLAGS=' -fvisibility=hidden -O2 -std=c99 -fno-builtin -DHAVE_SGX=1 -fPIC -DUNW_LOCAL_ONLY'
++ echo -fvisibility=hidden -O2 -std=c99 -fno-builtin -DHAVE_SGX=1 -fPIC -DUNW_LOCAL_ONLY
++ uniq
++ tr '\n' ' '
++ grep -v nostdinc
++ sort
++ tr ' ' '\n'
+ CFLAGS='-DHAVE_SGX=1 -DUNW_LOCAL_ONLY -O2 -fPIC -fno-builtin -fvisibility=hidden -std=c99 '
+ HOST_OPT=
+ echo -DHAVE_SGX=1 -DUNW_LOCAL_ONLY -O2 -fPIC -fno-builtin -fvisibility=hidden -std=c99
+ grep -q -- -m32
+ '[' -f /usr/bin/dpkg ']'
+ export CFLAGS
+ /app/sgx_unwind/../sgx_unwind/libunwind/configure --enable-shared=no --disable-block-signals --enable-debug=no --enable-debug-frame=no --enable-cxx-exceptions --host=x86_64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu
libtool: Version mismatch error.  This is libtool 2.4.6 Debian-2.4.6-2, but the
libtool: definition of this LT_INIT comes from libtool 2.4.2.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6 Debian-2.4.6-2
libtool: and run autoconf again.
make[2]: *** [os-linux.lo] Error 63
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

**Comment by dingelish** [comment]
Thanks for this report! Which version of CentOS is the preferred? I'll try to start with a CentOS docker image :-)

**Comment by akhilles** [comment]
I think the latest CentOS version (7.6) would probably be best. The centos:latest docker image is 7.6 as well.

**Comment by AvishaiW** [comment]
hey, I'm using an IBM machine based on Ubuntu and it's also failing for me. ```error: failed to run custom build command for sgx_unwind v0.0.1 (https://github.com/baidu/rust-sgx-sdk.git?rev=v1.0.9#de01b631)```

**Comment by dingelish** [comment]
Hi @AvishaiW , could you please provide more info regards to this failure? and could you please try akhilles's fix and then build again? Thanks!

**Comment by AvishaiW** [comment]
[failure.log](https://github.com/baidu/rust-sgx-sdk/files/3617147/failure.log)
I don't think we have the same exact problem: I'm running 1.0.9 on an ubuntu 18.04 docker, on my local ubuntu machine everything runs properly but in my CI which is running on an IBM ubuntu based machine using the same exact docker i get the failure error as shown in the failure.log

**Comment by akhilles** [comment]
@AvishaiW looks like the Intel SGX SDK environment variables aren’t set properly in your CI environment. Make sure to source the environment file in the SGX SDK install path.

**Comment by AvishaiW** [comment]
yeah, I found the error on my side.. Thanks!

**Comment by dingelish** [comment]
@AvishaiW @akhilles 

Please help me check if the latest commit 78ccd4a9e57ae7f218973d3a5e1f1b6e100bf571 fixed the problem. Thanks!

And I added a Dockerfile for centos:7  as well. Hope it works!

**Comment by dingelish** [comment]
Then removed unused files which are ignored in .gitignore in 371e9db

**Comment by dingelish** [comment]
And finally Xargo should work well!

**Comment by akhilles** [comment]
@dingelish, finally got around to testing it. Seems to be working just fine!

**Comment by dingelish** [comment]
Cool!
