### ISSUE TITLE
Rename ring-sgx's links value

### ISSUE THREAD

**Issue by akhilles** [apache/teaclave-sgx-sdk#164]
**Proposal**: rename the `links` value in `ring-sgx`'s Cargo manifest (https://github.com/mesalock-linux/ring-sgx/blob/master/Cargo.toml#L16) from `"ring-asm"` to `"ring-sgx-asm"`.

According to Cargo book:

> Cargo requires that there is at most one package per `links` value. In other words, it’s forbidden to have two packages link to the same native library.

I believe it's a common use-case to compile the same Rust code for sgx and non-sgx environments based on a feature flag. This means having *`ring`* **and** `ring-sgx` as dependencies in the same Cargo workspace. Currently, that's not allowed since Cargo thinks both of these crates are attempting to link to the same native library.

**Comment by dingelish** [comment]
Hey, I totally understand your concern, and I think it really makes sense. But the "same linking name" failure can help with finding the collisions. For example, if an enclave brings in the regular upstream "ring" with `no_std` enabled, as well as ring-sgx at the same time, the collision failure would find this. So I think this may help with finding all such collisions. What do you think?

**Comment by akhilles** [comment]
For the scenario you mentioned, Cargo wouldn’t allow it anyways unless either upstream ring or ring-sgx was explicitly renamed using the `package` key.

Also, if I have 2 separate libraries in the same Cargo workspace, I should be able to use ring in one and ring-sgx in the other.

**Comment by dingelish** [comment]
got it. let me fix it now.

**Comment by dingelish** [comment]
fixed in https://github.com/mesalock-linux/ring-sgx/commit/a871a4ef683480750dce65d7c893c2911629bbdd

**Comment by akhilles** [comment]
thanks!
