### ISSUE TITLE
sgx_quote3_error_t has a mismatch with intel's library.

### ISSUE THREAD

**Issue by Doresimon** [apache/teaclave-sgx-sdk#167]
hi, i'm building dcap of intel, and i found the "sgx_quote3_error_t"  has a different SGX_QL_SUCCESS value with intel's library, 0xE000 vs 0x0000. 

the code lies here:
rust:   https://github.com/baidu/rust-sgx-sdk/blob/0ca456a8f153bc4eeb86750ed9f56fde3496d6ee/sgx_types/src/error.rs#L385
intel-dcap:   https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/df69a7f998168bb5d0fd859615387d806031693b/QuoteGeneration/quote_wrapper/common/inc/sgx_ql_lib_common.h#L48

**Comment by dingelish** [comment]
Oh. Thanks!

**Comment by dingelish** [comment]
Could you please check if fa854ed27242ee0e3f23351b6099f2fbb37e3144 fixes this problem? Thank you!

**Comment by Doresimon** [comment]
Yes, it works~
