### ISSUE TITLE
v1.1.0 beta issue tracking

### ISSUE THREAD

**Issue by dingelish** [apache/teaclave-sgx-sdk#168]
Hi everyone,

I just pushed v1.1.0 beta version to the v1.1.0-beta branch. It provides:

* `thread::spawn` supported by a OCALL-ECALL routine. The ECALL interface requires an enclave ID as an argument, so we need to remember the enclave id when going through this routine. This is achieved by sgx_urts's feature `gobal_init`. Please look into the `unit-test` sample code for usage.

* `std::is_x86_feature_detected!` and `is_cpu_feature_supported!`. These two macros are like magic. Intel SGX SDK provides a global symbol `g_cpu_feature_indicator` which holds the CPU feature bits. Our implementation parses that indicator and output the result, without triggering any `cpuid` instructions and avoids from AEXs.

* support env var func like home_dir/current_exe etc.

Please feel free to comment!

**Comment by akhilles** [comment]
Could you provide some clarification on the `global_init` and `global_exit` features in `sgx_urts`? I'm not sure when they should be enabled and what functionality they offer.

**Comment by dingelish** [comment]
Working on the documentation. Give me a couple of days!

**Comment by dingelish** [comment]
will track it in another issue :-)
