### ISSUE TITLE
Immediate 2.7 upgrade on v1.0.9

### ISSUE THREAD

**Issue by dingelish** [apache/teaclave-sgx-sdk#169]
Hi all,

Intel just released the 2.7 version of their SDK. The diff indicates that 2.7 can defend against novel attacks to the switchless feature. My tests reveals that 2.7 is 100% compatible with current 1.0.9 release. Shall we update the docker image directly in 1.0.9?

**Comment by dingelish** [comment]
I find (potentially) a bug in 2.7, which may break mutual-ra.

https://github.com/intel/linux-sgx/issues/457

If you have chance to try with 2.7, please help me check if it happens to you. Thanks!

**Comment by akhilles** [comment]
I would update it as part of the next release. IMO, a 1-to-1-to-1 mapping between Intel's SDK version, `rust-sgx-sdk` version, and Rust toolchain version is worth preserving for the immediate future.

**Comment by dingelish** [comment]
Got it. Thanks for the advice!

Seems that Intel has a patch and will release a new version soon. Let's wait for it.

**Comment by dingelish** [comment]
Intel released 2.7.1

https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-linux-2.7.1-release-version-string-2.7.101.3

Since 2.7 breaks the remote attestation APIs, I think we should skip it and move to 2.7.1 directly.
