### ISSUE TITLE
can't find crate "sgx_types" in sgx_tcrypto

### ISSUE THREAD

**Issue by weichiao-cs07** [apache/teaclave-sgx-sdk#171]
Hello all, 
I have met a problem while adding `sgx_tcrypto = "1.0.9"` to dependencies.
There will be error message such as
```
Updating crates.io index
   Compiling sgx_tcrypto v1.0.9
error[E0463]: can't find crate for `sgx_types`
  --> /home/breakfast/.cargo/registry/src/github.com-1ecc6299db9ec823/sgx_tcrypto-1.0.9/src/lib.rs:43:1
   |
43 | extern crate sgx_types;
   | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `sgx_tcrypto`.

To learn more, run the command again with --verbose.
```

The toolchain used is nightly-x86_64-unknown-linux-gnu (default)

Any suggestions? Thanks in advance!

Erica

**Comment by dingelish** [comment]
Hi Erica, could you please provide your Cargo.toml? Thanks!

**Comment by dingelish** [comment]
Please do not use it directly from crates.io. Use it like this:
```
sgx_tcrypto = { git = "https://github.com/baidu/rust-sgx-sdk.git" }
```

**Comment by weichiao-cs07** [comment]
Sure! Thank you for reply!
This is the Cargo.toml of my project
```
[package]
name = "app"
version = "0.1.0"

[dependencies]
sha2 = "0.7.1"
ring = "0.16.6"
secp256k1 = "0.15.5"
rand = "0.6.5"
sgx_tcrypto = { git = "https://github.com/baidu/rust-sgx-sdk.git" }
```

And this is sgx_tcrypto-1.0.9's Cargo.toml file 
```
# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO
#
# When uploading crates to the registry Cargo will automatically
# "normalize" Cargo.toml files for maximal compatibility
# with all versions of Cargo and also rewrite `path` dependencies
# to registry (e.g., crates.io) dependencies
#
# If you believe there's an error in this file please file an
# issue against the rust-lang/cargo repository. If you're
# editing this file be aware that the upstream Cargo.toml
# will likely look very different (and much more reasonable)

[package]
edition = "2018"
name = "sgx_tcrypto"
version = "1.0.9"
authors = ["Baidu"]
description = "Rust SGX SDK provides the ability to write Intel SGX applications in Rust Programming Language."
documentation = "https://dingelish.github.io/"
license-file = "LICENSE"
repository = "https://github.com/baidu/rust-sgx-sdk"

[lib]
name = "sgx_tcrypto"
crate-type = ["rlib"]

[features]
default = []

```

**Comment by dingelish** [comment]
I wonder if you are working on a SGX enclave? or just a regular linux app?

If you need to work on an enclave, I recommend you to try start from one of our sample code, such as the hello-rust.

**Comment by dingelish** [comment]
The crates hosted by crates.io are just some place holders. They do not work in most cases.

If you intend to construct a SGX enclave, you should have the entire enclave project ready before writing the code. For external crates, I recommend you to refer to this Cargo.toml, which include all supported crates in rust-sgx ecosystem:

https://github.com/dingelish/sgx-world/blob/master/dumb-all/Cargo.toml

**Comment by weichiao-cs07** [comment]
I afraid that I will need to work this on SGX enclaves:)
And this test that I just show you, is also run on SGX enclaves, however, I haven't start programming yet, I just add the dependencies  and it comes compile error.
(Sorry, I am new to rust and sgx....)

**Comment by dingelish** [comment]
If you are new to Intel SGX, the following documents can help you with the basics of Intel SGX, and its programming model:

[1] Intel SGX Developer Guide, https://download.01.org/intel-sgx/latest/linux-latest/docs/Intel_SGX_Developer_Guide.pdf
[2] Intel SGX Developer Reference, https://download.01.org/intel-sgx/latest/linux-latest/docs/Intel_SGX_Developer_Reference_Linux_2.7_Open_Source.pdf
[3] Intel SGX explained. https://eprint.iacr.org/2016/086.pdf

To use this SDK, please clone it recursively to your disk, and `cd` to `samplecode/hello-rust` and then `make`, then `cd bin` and `./app`. Look into [1] and [2] to see how the SGX enclave are constructed and worked with the untrusted app, and look closely into EDL to see how the program is partitioned. After you understand how the helloworld works, I think you can start using this SDK.

**Comment by dingelish** [comment]
I'm closing this issue because most of the developers do not want to get notified. But @weichiao-cs07 , you can still comment on this issue after it's closed. I'll keep watching on this and answer your questions. Thanks!

**Comment by weichiao-cs07** [comment]
Ok! No problem, I will start from there,  thank you so much for your time and explanation!

**Comment by dingelish** [comment]
You can look at this video for a quick start. It's me. Hope you like it!

https://www.youtube.com/watch?v=8IvWPeavjiQ&t=1s
