### ISSUE TITLE
Support `SGX_KEYPOLICY_MRENCLAVE`

### ISSUE THREAD

**Issue by bradyjoestar** [apache/teaclave-sgx-sdk#172]
Currently we only support `SGX_KEYPOLICY_MRSIGNER` in sealing, for we use default parameters in the following function.

https://github.com/baidu/rust-sgx-sdk/blob/3a43c5f205d90b9866c421329f4f3e8db32e39c0/sgx_tseal/src/internal.rs#L276-L287

I'd like to support `SGX_KEYPOLICY_MRENCLAVE` if what I analysed is right :smile:

**Comment by volcano0dr** [comment]
The function SgxSealedData::<T>::seal_data_ex can support SGX_KEYPOLICY_MRENCLAVE key_policy

**Comment by bradyjoestar** [comment]
@volcano0dr yeah, you're right, I found it.
Thanks!
