### ISSUE TITLE
Where is /dev/isgx?

### ISSUE THREAD

**Issue by hjlee9182** [apache/teaclave-sgx-sdk#177]
![zc](https://user-images.githubusercontent.com/46337218/68765127-6be43880-065f-11ea-96d6-049e16e79ffe.PNG)

![3](https://user-images.githubusercontent.com/46337218/68765202-9504c900-065f-11ea-98e3-b7997452c4b7.PNG)

If I follow this picture I didn't have /dev/isgx folder.
How to solve this problem?

**Comment by dingelish** [comment]
Hi there,

You need to confirm that:
(1) Your CPU supports Intel SGX
(2) Your motherboard supports Intel SGX
(3) Intel SGX is enabled in BIOS

And then boot to Linux and install the driver. You'll see `/dev/isgx` then.

For (1) and (2), you can refer to SGX-hardware
https://github.com/ayeks/SGX-hardware
