### ISSUE TITLE
Occur error when ./app in SIM

### ISSUE THREAD

**Issue by hjlee9182** [apache/teaclave-sgx-sdk#178]
![에러하나](https://user-images.githubusercontent.com/46337218/68780369-87f4d380-0679-11ea-94e5-ab38218d098c.PNG)
![에러 둘](https://user-images.githubusercontent.com/46337218/68780372-89260080-0679-11ea-842b-df2524472b84.PNG)

![시뮬](https://user-images.githubusercontent.com/46337218/68780430-a2c74800-0679-11ea-84a9-027d3ae7b25c.PNG)

I follow upper image ( SIM mode)

But when I use ./app upper error occur.

I tried to change "HW -> SW" in make file
and "make SGX_MODE=SIM" .

But still error occur.

How to solve this error?

**Comment by dingelish** [comment]
Hi there, I can't see any failure on my testbed. Which docker image did you use? More info will be much more helpful. Thanks!

**Comment by hjlee9182** [comment]
@dingelish 
My OS is ubuntu 16.04
my docker image is  sgx-rust:1604 and sgx-rust-stable.
![에러3](https://user-images.githubusercontent.com/46337218/68783479-6813de80-067e-11ea-942e-1becf5df76b6.PNG)
Now I experienced another error :<

**Comment by dingelish** [comment]
the stable branch and docker images are not maintained anymore. and the latest docker image tags are:

baiduxlab/sgx-rust:1804-1.0.9
baiduxlab/sgx-rust:1604-1.0.9

you just used baiduxlab/sgx-rust:1604 and I think I forgot to update it to point to 1604-1.0.9. thanks for your report! I just updated the tag. so please `docker pull baiduxlab/sgx-rust:1604` again to use the latest docker image. thanks!

**Comment by hjlee9182** [comment]
@dingelish 

Thanks for your service!!
So download now !! :)

**Comment by hjlee9182** [comment]
@dingelish 
![여전히에러](https://user-images.githubusercontent.com/46337218/68785091-fa1ce680-0680-11ea-9457-da1f0fa2f048.PNG)
I'm pull again sgx-rust:1604
but now this error occur :<....
How to fix it?

**Comment by dingelish** [comment]
I can't reproduce. Here is my log. I use `make SGX_MODE=SW`

```
docker run -ti baiduxlab/sgx-rust:1604 bash
root@902b9a088b19:~# git clone https://github.com/apache/mesatee-sgx
Cloning into 'mesatee-sgx'...
remote: Enumerating objects: 216, done.
remote: Counting objects: 100% (216/216), done.
remote: Compressing objects: 100% (197/197), done.
remote: Total 15834 (delta 58), reused 44 (delta 16), pack-reused 15618
Receiving objects: 100% (15834/15834), 40.83 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (8279/8279), done.
Checking connectivity... done.
root@902b9a088b19:~# cd mesatee-sgx/samplecode/localattestation/
root@902b9a088b19:~/mesatee-sgx/samplecode/localattestation# make SGX_MODE=SW
/opt/sgxsdk/bin/x64/sgx_edger8r --use-prefix --trusted enclave1/Enclave1.edl --search-path /opt/sgxsdk/include --search-path ../../edl --trusted-dir enclave1
/opt/sgxsdk/bin/x64/sgx_edger8r --use-prefix --untrusted enclave1/Enclave1.edl --search-path /opt/sgxsdk/include --search-path ../../edl --untrusted-dir app
......
......
......
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 2174976B.
The required memory is 0x213000, 2124 KB.
Succeed.
SIGN =>  bin/enclave3.signed.so
root@902b9a088b19:~/mesatee-sgx/samplecode/localattestation# cd bin/
root@902b9a088b19:~/mesatee-sgx/samplecode/localattestation/bin# ./app


Secure Channel Establishment between Source (E1) and Destination (E2) Enclaves successful !!!

Secure Channel Establishment between Source (E1) and Destination (E3) Enclaves successful !!!

Secure Channel Establishment between Source (E2) and Destination (E3) Enclaves successful !!!

Secure Channel Establishment between Source (E3) and Destination (E1) Enclaves successful !!!

Close Session between Source (E1) and Destination (E2) Enclaves successful !!!

Close Session between Source (E1) and Destination (E3) Enclaves successful !!!

Close Session between Source (E2) and Destination (E3) Enclaves successful !!!

Close Session between Source (E3) and Destination (E1) Enclaves successful !!!
```

**Comment by dingelish** [comment]
can you try `make clean` and `make SGX_MODE=SW`? thanks!

**Comment by hjlee9182** [comment]
@dingelish 
My implement sequence
-> docker pull baiduxlab/sgx-rust:1604
-> docker run -ti baiduxlab/sgx-rust:1604 bash
-> git clone https://github.com/apache/mesatee-sgx
->cd mesatee-sgx/samplecode/localattestation
-> make SGX_MODE=SW
-> cd bin   
-> ./app

is right sequence? But i didn't... 

So i try again docker pull baiduxlab/sgx-rust:1604 

++ i pull another docker pull baiduxlab/sgx-rust:1604-1.0.9 , But that's also same error 
: ( ....

Is any other action before run images?

**Comment by dingelish** [comment]
it's really weird. is your `hello-rust` sample working?

**Comment by hjlee9182** [comment]
@dingelish 
![hello](https://user-images.githubusercontent.com/46337218/68794439-59cfbd80-0692-11ea-9934-d74cf7c2fbed.PNG)

Occur token error(?) .

**Comment by dingelish** [comment]
token error is not a real error. it does not mean anything. you can ignore that.

it seems that the hello-rust enclave works fine.

**Comment by hjlee9182** [comment]
@dingelish 
But  why doesn't implement in localattestation?... 
That's very harass to me ...  :(
Are you on Ubuntu 16.0.4?

++ I tried to in Ubuntu 18.0.4 , But same error  "code e5".

**Comment by dingelish** [comment]
do you use amd cpu?

**Comment by dingelish** [comment]
I have a few questions regarding to your testbed
(1) is this testbed a virtual machine?
(2) how many physical cores are there in this test bed?
(3) how many logical cores are there in this test bed?
(4) what is the memory size of this test bed?
(5) what's the output of `cat /proc/cpuinfo` in this test bed?

**Comment by dingelish** [comment]
I think I find the problem. The local attestation sample does not work on some platforms.

Please skip this sample and give me a few days to fix it. Thanks!

**Comment by dingelish** [comment]
@hjlee9182 Just pushed a fix 46837a05facee93622cdf5c3a1d542525c4fce75

Please check if it fixes your problem :-)

**Comment by hjlee9182** [comment]
@dingelish 
That's running!! Thanks!

**Comment by dingelish** [comment]
@hjlee9182 can we close this issue?

**Comment by hjlee9182** [comment]
@dingelish 
I have on question!.
I want to send msg enclave 2 -> enclave 1 and enclave 3 -> enclave 1 in SampleCode localattestation.
Which section should I refer to?
