### ISSUE TITLE
I have a question!

### ISSUE THREAD

**Issue by hjlee9182** [apache/teaclave-sgx-sdk#179]
I have on question!.
I want to send msg enclave 2 -> enclave 1 and enclave 3 -> enclave 1 in SampleCode localattestation.
Which section should I refer to?

**Comment by dingelish** [comment]
Hi @hjlee9182 ,

You should refer to the localattestation sample.

But the current sample is toooooooooold (>3 years!), and it does not show how to send messages across enclaves.

The good news is Intel implemented it in C++ [here](https://github.com/intel/linux-sgx/blob/master/SampleCode/LocalAttestation/Enclave1/Enclave1.cpp). If you have time, I recommend you to rewrite it to Rust, according to the latest local attestation C++ sample. It's very, very straightforward. And I'd very happy to merge your implementation :-) It'll be a very good start for you to understand local attestation and ECDH via local attestation.

Good luck!

**Comment by hjlee9182** [comment]
@dingelish 
THX :)
