### ISSUE TITLE
关于远程证实

### ISSUE THREAD

**Issue by 60ke** [apache/teaclave-sgx-sdk#183]
During the IAS registration, one always generates two files: client.crt and client.key.
在intel注册完账号，只看到SPID和密匙，没见到client.crt  client.key.

**Comment by dingelish** [comment]
您好，现在已经不需要crt/key了，因为IAS已经切换到了v5 API。在之前的IAS spec中是需要crt/key的，v5已经抛弃了这个接口。

对于不可信组件/可信组件之间的远程证实，请参考ue-ra例子。
对于可信组件之间的互相远程证实，请参考mutual-ra例子。

老式的remoteattestation例子今后会不再维护。
