### ISSUE TITLE
`set_enclave_path` always returns Ok(())

### ISSUE THREAD

**Issue by mssun** [apache/teaclave-sgx-sdk#184]
I found that the `set_enclave_path` function always return `Ok(())`. I suggest this function should check whether the `path` exits or not and return an error.

https://github.com/apache/incubator-teaclave-sgx-sdk/blob/4508450be2c6e169bc592b9d8c6ab3802eb2d557/sgx_tstd/src/enclave.rs#L100-L108

**Comment by dingelish** [comment]
@volcano0dr can we do this?

**Comment by volcano0dr** [comment]
If we do this, we need to use untrusted_fs features. I am considering whether this API needs to be marked.

**Comment by dingelish** [comment]
Closed by #188

**Comment by dingelish** [comment]
@volcano0dr crates-sgx updated accordingly. Please create a PR for incubator-teaclave. Thanks!
