### ISSUE TITLE
hugemem

### ISSUE THREAD

**Issue by Claaudiaaa** [apache/teaclave-sgx-sdk#192]
When I run the program **hugemem** , the process just terminates,  and "killed"  appears. I don't know why it happens. Thank you for your help.

**Comment by dingelish** [comment]
I successfully tested on my workstation (Xeon E-2186G + 64GB memory).

This configuration is:
```
<HeapMaxSize>0xB80000000</HeapMaxSize>
```
resulting in
```
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0xB80000000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 49392754688B.
The required memory is 0xb8009a000, 48235112 KB.
Succeed.
SIGN =>  bin/enclave.signed.so
```
Due to the limitation of current SGX driver, it seems that you cannot run this example without 64GB of physical memory.

**Comment by dingelish** [comment]
![image](https://user-images.githubusercontent.com/1870436/71784891-b756fb00-2fad-11ea-91c5-19ef325aa9b1.png)

**Comment by Claaudiaaa** [comment]
thank you for reminding！！
