### ISSUE TITLE
why dont u guys write sample code in rust?

### ISSUE THREAD

**Issue by m3ngzhang** [apache/teaclave-sgx-sdk#193]
I tried ur samples from this sdk. But I dont understand why u guys use c code instead of rust in most of those samples. This is a rust sdk, right? I'm a rust learner ready now. Maybe u can add some second version samples to help me know how to play with rust sgx sdk.

**Comment by dingelish** [comment]
Hi @czzmmc , 

I want to emphasize that:
**As of today, Jan 20 2020, we provide 38 samples. All of the enclaves are written in Rust.**

Only the following legacy samples have codes in C/C++ in their **untrusted app**:
(1) helloworld. This sample contains legacy untrusted app. But the enclave is written in Rust
(2) localattestation, and thread. Only untrusted side are written in C++. These untrusted apps are developed by Intel. This sample is to show that Rust SGX SDK can do exactly the same thing.
(3) crypto/sealeddata/file/backtrace/serialize/hello-regex/hugemem/secretsharing are the same to (1)

If you look into all other samples, they are written in 100% Rust.

We can replace everything in Rust. But it's not the first priority.

**Comment by dingelish** [comment]
If you don't know where to start, please look at hello-rust sample, instead of helloworld.

**Comment by m3ngzhang** [comment]
@dingelish thx bro
