### ISSUE TITLE
How to get machine code related to machine hardware?

### ISSUE THREAD

**Issue by renxingliang** [apache/teaclave-sgx-sdk#198]
I want to get the unique machine code of the computer through the sdk interface. Someone told me to use rsgx_get_key, but I didn't find detailed documentation. When I tested with the following code, I found that the keys obtained each time were different. I hope to consult the sgx_key_request_t which is really normal after entering to obtain unique machine code.

    let key_request = sgx_key_request_t {
        key_name: SGX_KEYSELECT_SEAL,
        key_policy,
        isv_svn: report.body.isv_svn,
        reserved1: 0_u16,
        cpu_svn: report.body.cpu_svn,
        attribute_mask,
        key_id,
        misc_mask: TSEAL_DEFAULT_MISCMASK,
        config_svn: report.body.config_svn,
        reserved2: [0_u8; SGX_KEY_REQUEST_RESERVED2_BYTES],
    };
    let sgx_key = rsgx_get_key(&key_request).unwrap();
    println!("sgx_key = {:?}", sgx_key);

**Comment by volcano0dr** [comment]
1. The rsgx_get_key function is used to get the sgx related key, not to get the machine code.
2.  Whether the key_request.key_id change or not when the rsgx_get_key function is called each time?

**Comment by renxingliang** [comment]
1.Each time the key is obtained, the id and return value are different.
2.If rsgx_get_key is not the interface we want, is there any interface in sdk that can get machine code?

**Comment by volcano0dr** [comment]
1. If key_id changes, the key obtained by calling rsgx_get_key will be different.
2. There is no interface to get machine code in SDK.
