### ISSUE TITLE
Where is the white paper?

### ISSUE THREAD

**Issue by adombeck** [apache/teaclave-sgx-sdk#2]
This looks like a very interesting project and I would love to learn more about it. In the 0.1.0 release notes you refer to the white paper for details, but I can't find the white paper. The `release_docs/whitepaper.md` is empty.

**Comment by dingelish** [comment]
Hi there, we are preparing for version 0.2.0 as well as the white paper! V0.2.0 will be released in a couple of days.

**Comment by adombeck** [comment]
Great, looking forward to it :)
