### ISSUE TITLE
Intel SGX v2.9

### ISSUE THREAD

**Issue by dingelish** [apache/teaclave-sgx-sdk#200]
Intel just released 2.8 Linux SGX SDK. The SDK changelog says:
> Intel® Software Guard Extensions SDK includes the following changes in version 2.8:
> - Supported open source version of Intel® Integrated Performance Primitives (Intel® IPP)
cryptography library.
> - Support for the Intel® Deep Neural Network Library (DNNL) library, OpenMP library*
and POSIX Threads (Pthread) library*.
> (*) Limited support only. Refer to the Developer Reference for additional details.
> - Refactored the switchless library. Developers have to opt-in, i.e. import the
sgx_tswitchless.edl into their enclave EDL file and link with the trusted library
(sgx_tswitchless.a) and untrusted library (sgx_uswitchless.a), in order to do enclave
> transitions using threads.
> - Removed sgx_uae_platform.h, sgx_tae_service.h, sgx_tae_service.edl,
libsgx_platform.so and libsgx_platform_sim.so
> - Updated Local Attestation sample project to demonstrate key exchange flow between
multiple processes.
> - Fixed bugs.

PSW changelog:

> Intel® Software Guard Extensions PSW includes the following changes in 2.8.100:
> - Added support for modularized installation.
> - Added support for running SGX applications inside Docker containers.
> - Fixed bugs

Will move to 2.8. But it seems that Intel missed some packages:

```
$ apt-get update && apt-get install -y gnupg2 apt-transport-https ca-certificates curl software-properties-common
$ curl -fsSL  https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | apt-key add -
$ add-apt-repository "deb https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main"
$ apt-get update
$ apt-get install libsgx-aesm-ecdsa-plugin-dbgsym libsgx-aesm-launch-plugin libsgx-ae-pce libsgx-dcap-pccs libsgx-ae-qe3 libsgx-dcap-default-qpl-dbgsym libsgx-ae-qve libsgx-quote-ex libsgx-aesm-pce-plugin libsgx-epid-dev libsgx-quote-ex-dev libsgx-enclave-common-dev libsgx-aesm-ecdsa-plugin libsgx-aesm-epid-plugin-dbgsym libsgx-dcap-ql-dbg libsgx-dcap-ql-dev libsgx-epid-dbgsym libsgx-aesm-quote-ex-plugin-dbgsym libsgx-aesm-launch-plugin-dbgsym libsgx-ae-le libsgx-epid libsgx-urts-dbgsym libsgx-enclave-common-dbgsym libsgx-aesm-epid-plugin libsgx-aesm-quote-ex-plugin libsgx-enclave-common libsgx-launch libsgx-launch-dbgsym libsgx-dcap-ql-dbgsym libsgx-dcap-default-qpl-dbg libsgx-dcap-default-qpl-dev libsgx-ae-epid libsgx-uae-service-dbgsym libsgx-launch-dev libsgx-aesm-pce-plugin-dbgsym libsgx-dcap-default-qpl libsgx-quote-ex-dbgsym libsgx-uae-service libsgx-urts libsgx-dcap-ql
The following packages have unmet dependencies:
 libsgx-dcap-default-qpl-dbg : Depends: libsgx-dcap-default-qpl (= 1.3.101.3-bionic1) but 1.4.100.4-bionic1 is to be installed
 libsgx-dcap-ql-dbg : Depends: libsgx-dcap-ql (= 1.3.101.3-bionic1) but 1.4.100.4-bionic1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by dingelish** [comment]
Issue created on
https://github.com/intel/linux-sgx/issues/483

**Comment by andyzyb** [comment]
Hi, you've installed the conflicting packages as below,  you should only install *-dbgsym for the new release.

libsgx-dcap-ql-dbg
libsgx-dcap-ql-dbgsym, 

libsgx-dcap-default-qpl-dbg
libsgx-dcap-default-qpl-dbgsym

**Comment by dingelish** [comment]
Thanks! @andyzyb So we should only install -dbgsym packages instead of -dbg ones, right?

**Comment by dingelish** [comment]
Created a new branch sgx2.8_patch, which includes a small patch to support Intel SGX 2.8

https://github.com/apache/incubator-teaclave-sgx-sdk/tree/sgx2.8_patch
