### ISSUE TITLE
confusing no_std issue: duplicate lang item ...

### ISSUE THREAD

**Issue by brenzi** [apache/teaclave-sgx-sdk#210]
When building 
https://github.com/encointer/encointer-worker/commit/7252e20264e63c7dce11470922d7c2965378842e

with
```
cd enclave
make
```
I get an error:
```
error: duplicate lang item in crate `sgx_tstd` (which `palette_support` depends on): `f32_runtime`.
  |
  = note: first defined in crate `std` (which `pallet_encointer_ceremonies` depends on).

error: duplicate lang item in crate `sgx_tstd` (which `palette_support` depends on): `f64_runtime`.
  |
  = note: first defined in crate `std` (which `pallet_encointer_ceremonies` depends on).

error: duplicate lang item in crate `sgx_tstd` (which `palette_support` depends on): `panic_impl`.
  |
  = note: first defined in crate `std` (which `pallet_encointer_ceremonies` depends on).

error: duplicate lang item in crate `sgx_tstd` (which `palette_support` depends on): `begin_panic`.
  |
  = note: first defined in crate `std` (which `pallet_encointer_ceremonies` depends on).

error: duplicate lang item in crate `sgx_tstd` (which `palette_support` depends on): `oom`.
  |
  = note: first defined in crate `std` (which `pallet_encointer_ceremonies` depends on).

error: aborting due to 5 previous errors
```

The strange thing is that it is caused by the last commit, introducing the dependency on 
https://github.com/encointer/pallet-encointer-ceremonies
but that crate has no dependencies (and no new features) that were not present in the [previous commit](https://github.com/encointer/encointer-worker/commit/5220a7560dde3cdd893aa913c73c561e0969e5f3).

Any help appreciated

**Comment by brenzi** [comment]
`cargo nono check` warns about exactly the same crates in both commits 
```
webpki: FAILURE
log: FAILURE
serde_json: FAILURE
sgx-externalities: FAILURE
env_logger: FAILURE
rustls: FAILURE
num-bigint: FAILURE
webpki-roots: FAILURE
substratee-stf: FAILURE
chrono: FAILURE
base64: FAILURE
yasna: FAILURE
serde: FAILURE
bit-vec: FAILURE
rust-base58: FAILURE
```
whereas none of them are dependencies of `pallet-encointer-ceremonies`.

However, `serde` is a `dev-dependency`, but I've already checked if I'm running into [this](https://github.com/rust-lang/cargo/issues/5730) or one of the similar issues. I just removed all dev-dependencies in `pallet-encointer-ceremonies`. To no success

**Comment by brenzi** [comment]
as this is probably not a bug of this sdk, I've filed an issue with cargo:
https://github.com/rust-lang/cargo/issues/7951

**Comment by clangenb** [comment]
Turned out to be a false alarm, see: rust-lang/cargo#7951

This can be closed.
