### ISSUE TITLE
http_req samplecode not working

### ISSUE THREAD

**Issue by m3ngzhang** [apache/teaclave-sgx-sdk#216]
Hi, I tried http_req samplecode in both HW and SW mode, and I got the same error. Here is it.

cp ./target/release/libhttpreqenclave.a ../lib/libenclave.a
make[1]: Leaving directory '/root/sgx/samplecode/http_req/enclave'
make -C /root/sgx/compiler-rt/ 2> /dev/null
make[1]: Entering directory '/root/sgx/compiler-rt'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/sgx/compiler-rt'
cp /root/sgx/compiler-rt/libcompiler-rt-patch.a ./lib
./lib/libenclave.a(sgx_libc-fd0a3e880c2101d2.sgx_libc.14eng8nx-cgu.3.rcgu.o): In function `sgx_libc::linux::x86_64::ocall::stat64':
sgx_libc.14eng8nx-cgu.3:(.text._ZN8sgx_libc5linux6x86_645ocall6stat6417he2b503da1412f08eE+0x27): undefined reference to `u_stat64_ocall'
collect2: error: ld returned 1 exit status
Makefile:127: recipe for target 'enclave/enclave.so' failed
make: *** [enclave/enclave.so] Error 1

Anyone help? THX

**Comment by dingelish** [comment]
thanks for the report! confirmed. it's a bug. fixed in 779acddb67863d33bf3cf2e73efa5c80a3d8da2c.

Thank you!
