### ISSUE TITLE
thread panics while doing keygen

### ISSUE THREAD

**Issue by edison0xyz** [apache/teaclave-sgx-sdk#218]
I'm getting some strange errors with `Rng`, and will appreciate if anyone could give pointers on how to solve it.

Error:
```
thread panicked while processing panic. aborting.
Illegal instruction
```

It might not be a SDK problem, but more of usage problem. On the same file, I've tried the following and got two different outcomes.

Works:
```rust
    let mut rand = match StdRng::new() {
        Ok(rng) => rng,
        Err(_) => { return sgx_status_t::SGX_ERROR_UNEXPECTED; },
    };
```

**Doesn't work**

Bad Example 1:

```rust
    let ecc_handle = SgxEccHandle::new();
    println!("attempting to create keypair");
    let mut private = sgx_ec256_private_t::default();
    let mut public = sgx_ec256_public_t::default();
    let (private, public) = ecc_handle.create_key_pair().unwrap();
```

Bad Example 2:

```
        // fixme: change to mut after randomisation impl
        let rand_container = vec![0u8; (threshold - 1) as usize];

        for c in secret.as_bytes() {

            // fixme: randomise the bytes
            
            thread_rng().fill_bytes(&mut rand_container);
            let mut coef: Vec<u8> = vec![*c];
            for r in rand_container.iter() {
                coef.push(*r);
            }
            coefficients.push(coef);
        }
```

Bad Example 1 and 2 returns the same errors

### Hypothesis

My hypothesis is there's some segfault going on.

**Comment by dingelish** [comment]
Hi @edisonljh , could you please a sample project that i can play with? then i can provide a fix as a PR quickly :-)

**Comment by dingelish** [comment]
@edisonljh I guess you missed `ecc_handle.open()` after opening it. Please see my patch below:

```diff
+    let mut ecc_handle = SgxEccHandle::new();
+    let _ = ecc_handle.open(); // <-- here
+    println!("attempting to create keypair");
+    let mut private = sgx_ec256_private_t::default();
+    let mut public = sgx_ec256_public_t::default();
```

**Comment by dingelish** [comment]
For bad example 2, please check if the panic info is: `thread '<unnamed>' panicked at 'TLS access error: AccessError { msg: "If TLS data needs to be destructed, TCS policy must be Bound." }'`. If so, the problem is:

1. the enclave is signed with TCSPOLICY=UNBOUND, which means there's no reliable thread local storage slots.
2. the enclave is using thread local storage, which often relates to `thread_rng`

Two ways to fix:
- Edit TCSPolicy in `Enclave.config.xml`. make TCSPolicy = 0
- or use `SgxRng` in `sgx_rand`, or `OsRng` in ported `rand`

```toml
rand = { git = "https://github.com/mesalock-linux/rand-sgx", tag = "v0.6.5_sgx1.1.1" }
```

```rust
use std::string::ToString;
let threshold = 128;
let secret = "abcdefg".to_string();
let mut rand_container = vec![0u8; (threshold - 1) as usize];
let mut coefficients= vec![];

for c in secret.as_bytes() {

    // fixme: randomise the bytes

    let mut rng = SgxRng::new().unwrap();
    rng.fill_bytes(&mut rand_container);
    let mut coef: Vec<u8> = vec![*c];
    for r in rand_container.iter() {
        coef.push(*r);
    }
    coefficients.push(coef);
}

{
    use rand::rngs::OsRng;
    use rand::RngCore;
    OsRng.fill_bytes(&mut rand_container);
}

```

**Comment by lhfbc** [comment]
I downloaded the latest code, and ran the 'file' in samplecode, it also showed the same error info.
But a few days ago, it worked well, and I didn't change anything.
```
thread panicked while processing panic. aborting.
Illegal instruction (core dumped)
```
What a strange thing! Is there anything updated, or the compiler updated? Maybe some dependences changed.

**Comment by dingelish** [comment]
v1.1.1 patch was merged on March 27. you need to upgrade your SGX suite to v2.9 (driver + psw + SDK)

**Comment by lhfbc** [comment]
> v1.1.1 patch was merged on March 27. you need to upgrade your SGX suite to v2.9 (driver + psw + SDK)

Cool! Now it's OK!

**Comment by edison0xyz** [comment]
> For bad example 2, please check if the panic info is: `thread '<unnamed>' panicked at 'TLS access error: AccessError { msg: "If TLS data needs to be destructed, TCS policy must be Bound." }'`. If so, the problem is:
> 
>     1. the enclave is signed with TCSPOLICY=UNBOUND, which means there's no reliable thread local storage slots.
> 
>     2. the enclave is using thread local storage, which often relates to `thread_rng`
> 
> 
> Two ways to fix:
> 
>     * Edit TCSPolicy in `Enclave.config.xml`. make TCSPolicy = 0
> 
>     * or use `SgxRng` in `sgx_rand`, or `OsRng` in ported `rand`
> 
> 
> ```toml
> rand = { git = "https://github.com/mesalock-linux/rand-sgx", tag = "v0.6.5_sgx1.1.1" }
> ```
> 
> ```rust
> use std::string::ToString;
> let threshold = 128;
> let secret = "abcdefg".to_string();
> let mut rand_container = vec![0u8; (threshold - 1) as usize];
> let mut coefficients= vec![];
> 
> for c in secret.as_bytes() {
> 
>     // fixme: randomise the bytes
> 
>     let mut rng = SgxRng::new().unwrap();
>     rng.fill_bytes(&mut rand_container);
>     let mut coef: Vec<u8> = vec![*c];
>     for r in rand_container.iter() {
>         coef.push(*r);
>     }
>     coefficients.push(coef);
> }
> 
> {
>     use rand::rngs::OsRng;
>     use rand::RngCore;
>     OsRng.fill_bytes(&mut rand_container);
> }
> ```

Thanks for the help! :)
