### ISSUE TITLE
http_req Illegal instruction

### ISSUE THREAD

**Issue by m3ngzhang** [apache/teaclave-sgx-sdk#219]
Hi,
I am trying to accomplish https request using rust sgx sdk.  I use MacBook with baidu lab docker as my develop tool. And I got "**thread panicked while processing panic. aborting.Illegal instruction**" when sending request to my https sever which written by python3. And I also want to use my own certifications created by openssl by myself. If there is any instructions, that would be nice.

**Comment by dingelish** [comment]
how about this: you create a repo with the https server and it's ca/cert/private key, and then let me create a corresponding https client and create a PR?

**Comment by m3ngzhang** [comment]
@dingelish Hi, I created a repo with my https server. 
https://github.com/czzmmc/rust_sgx_https_req
It's so nice of you.

**Comment by dingelish** [comment]
what's the password of server cert?

my fork with a sample client: https://github.com/dingelish/rust_sgx_https_req

**Comment by m3ngzhang** [comment]
@dingelish Sony to forget about that.  The pwd for server crt and client is 123456. And other info you might use is like below.
Country Name (2 letter code) []:CN
State or Province Name (full name) []:BJ
Locality Name (eg, city) []:BJ
Organization Name (eg, company) []:My Client / My Server / My CA (depending on different cert)
Organizational Unit Name (eg, section) []:
Common Name (eg, fully qualified host name) []:localhost
Email Address []:

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:123456

**Comment by m3ngzhang** [comment]
@dingelish I updated the all cert files. Please update, too.

**Comment by dingelish** [comment]
i don't think it's a problem of any rust codes. your server pem does not contain `Subject Alternative Name` and DNS name verifier cannot let it go. since this is related to this sdk, let's move to my fork and create a issue to discuss. thanks

https://github.com/dingelish/rust_sgx_https_req

**Comment by m3ngzhang** [comment]
@dingelish Sounds great! Please open the issue feature of your fork repo. I'll leave my comment there.

**Comment by m3ngzhang** [comment]
@dingelish Hi, I found the cure. I was using baiduxlab/sgx-rust:latest docker, which is an old version. I switched to baiduxlab/sgx-rust:1804-1.1.1, and then it works. I run the https sample code successfully!

**Comment by dingelish** [comment]
that's really good news!
