### ISSUE TITLE
mio support in third_party

### ISSUE THREAD

**Issue by tarcieri** [apache/teaclave-sgx-sdk#22]
It would be fantastic if it were possible to leverage the tokio ecosystem from within SGX (I am particularly interested in [gRPC support](https://github.com/tower-rs/tower-grpc)).

The first step is [mio](https://github.com/carllerche/mio) which provides a pure Rust abstraction for synchronous I/O multiplexing, and on Linux wraps the [epoll_*(2) family of system calls](http://man7.org/linux/man-pages/man7/epoll.7.html).

I think for this SDK you'd need to do something like forking mio into `third_party/` and adding OCALL wrappers which invoke the `epoll_*()` system calls from untrusted userspace, much in the same way `std::io` has been wrapped.

It's something I'd be interested in contributing if there aren't existing plans to work on it.

**Comment by dingelish** [comment]
Hi Tony,

Good idea! Intel just released [v2.2](https://github.com/intel/linux-sgx/releases) of their SDK and provide an interface of switchless call. I think with the help of this feature, we have chance to make tokio work on SGX. We need some time to understand how the switchless call works and design an appropriate interface for it before porting tokio. Let's keep this issue open and I'll keep updating.

**Comment by dingelish** [comment]
Update

Finally, I got some time on the switchless feature. c5bf1ace82a56986755057c180470b09b68b236c fixes bug in `sgx_urts` and `sgx_types` and provides a new code sample on switchless execution.

**Comment by dingelish** [comment]
Next step is to mio.

**Comment by dingelish** [comment]
Sounds like solved. Closing it now :-)
