### ISSUE TITLE
What about arrange extended edl files with cargo?

### ISSUE THREAD

**Issue by sammyne** [apache/teaclave-sgx-sdk#224]
## Observation
During daily development with this great SDK, we have to copy theses [edls](https://github.com/apache/incubator-teaclave-sgx-sdk/tree/master/edl) to local file system to use as extra searching paths for the `sgx_edger8r` tool for every project.

There isn't any version control for these edls.

Considering our projects with this SDK using rust and cargo, I think it would be nice to collect all these edls as a crate. If done, it would be possible for us to just collect these edls using `cargo vendor` command with a Cargo.toml specifying this crate as the only dependency. This also helps the version control.

**Comment by teaclave-archiver** [comment]
Good idea. These files can be included (
https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields)
in sgx_tstd.

**Comment by volcano0dr** [comment]
Good idea! I will consider using a  crate to control and compile these edls.

**Comment by sammyne** [comment]
I would be better if the common folder can be put into that crate also~ @volcano0dr

**Comment by sammyne** [comment]
It has been done at https://github.com/apache/incubator-teaclave-sgx-sdk/commit/df76765f586cf103189a5e62355672c96f4920ce
