### ISSUE TITLE
Is ring-sgx ready to use?

### ISSUE THREAD

**Issue by assafmo** [apache/teaclave-sgx-sdk#233]
Hi @dingelish, would you say that https://github.com/mesalock-linux/ring-sgx is ready to use, and if so could you tell us how to import it?

**Comment by dingelish** [comment]
yes it's ready to use.

Cargo.toml sample: https://github.com/mesalock-linux/rustls/blob/mesalock_sgx/Cargo.toml#L17

```toml
ring = { git = "https://github.com/mesalock-linux/ring-sgx", tag = "v0.16.5" }
```

the tag is still v0.16.5, while the accurate version is 0.16.10 -- it's because 0.16 "stabled" since 0.16.5 and we started to use this tag since then.

**Comment by assafmo** [comment]
Thanks!
