### ISSUE TITLE
v1.1.2: `InternalBacktrace` in the backtrace feature of tstd

### ISSUE THREAD

**Issue by fredfortier** [apache/teaclave-sgx-sdk#238]
I'm trying adapt the `error-chain` crate. It relies on the `backtrace` crate which I replaced by the backtrace feature of tstd. I don't know what to do with the hidden `InternalBacktrace` here: https://github.com/rust-lang-nursery/error-chain/blob/44c9240940e974695386cb7b9ab020df1147dbfe/src/lib.rs#L558

```
error[E0432]: unresolved import `std::backtrace::InternalBacktrace`
   --> /root/.cargo/git/checkouts/error-chain-cd67bb92899312ae/0503635/src/lib.rs:560:9
    |
560 | pub use std::backtrace::InternalBacktrace;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `InternalBacktrace` in `backtrace`
```

**Comment by mssun** [comment]
I believe there is something wrong.

`InternalBacktrace` is not an std struct, but from here: https://github.com/rust-lang-nursery/error-chain/blob/master/src/backtrace.rs#L16.

I'm not sure what changes did you make to adapt with the SDK. It would be very helpful if you can provide me more details.

**Comment by dingelish** [comment]
It seems error-chain needs porting. @fredfortier do you need help with the porting?

**Comment by fredfortier** [comment]
@dingelish Yes, I would appreciate help with the porting.

**Comment by fredfortier** [comment]
@mssun You were right. I confused error-chain backtrace module with the std. I got past this issue but now getting the error below. Like @dingelish suggested, I'm just trying to port the crate.
```
error[E0308]: mismatched types
   --> /root/.cargo/git/checkouts/error-chain-cd67bb92899312ae/f73f94d/src/lib.rs:691:9
    |
691 |         self.backtrace.as_backtrace()
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::backtrace::Backtrace`, found `()`
    |
    = note: expected enum `core::option::Option<&std::backtrace::Backtrace>`
               found enum `core::option::Option<&()>`

error: aborting due to previous error
```

**Comment by fredfortier** [comment]
I was able port this crate, at least according to my needs.
