### ISSUE TITLE
failure in compiling 'hello-rust '

### ISSUE THREAD

**Issue by EighteenZi** [apache/teaclave-sgx-sdk#24]
Hi Ding:
    when i compiled 'hello-rust', i got the error below.

> cp ./target/release/libhelloworldsampleenclave.a ../lib/libenclave.a
make[1]: Leaving directory '/home/sgx/github/rust-sgx-sdk/samplecode/hello-rust/enclave'
make -C ../../compiler-rt/ 2> /dev/null
make[1]: Entering directory '/home/sgx/github/rust-sgx-sdk/compiler-rt'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/sgx/github/rust-sgx-sdk/compiler-rt'
cp ../../compiler-rt/libcompiler-rt-patch.a ./lib
./lib/libenclave.a(sgx_tstd-f19980ed579769c0.sgx_tstd15-b7871f5ef2fc69b240503e44dd6ff56.rs.rcgu.o): In function `__rg_alloc':
sgx_tstd15-b7871f5ef2fc69b240503e44dd6ff56.rs:(.text.__rg_alloc+0x41): undefined reference to `posix_memalign'
./lib/libenclave.a(sgx_tstd-f19980ed579769c0.sgx_tstd15-b7871f5ef2fc69b240503e44dd6ff56.rs.rcgu.o): In function `__rg_realloc':
sgx_tstd15-b7871f5ef2fc69b240503e44dd6ff56.rs:(.text.__rg_realloc+0x83): undefined reference to `posix_memalign'
./lib/libenclave.a(sgx_tstd-f19980ed579769c0.sgx_tstd15-b7871f5ef2fc69b240503e44dd6ff56.rs.rcgu.o): In function `__rg_alloc_zeroed':
sgx_tstd15-b7871f5ef2fc69b240503e44dd6ff56.rs:(.text.__rg_alloc_zeroed+0x45): undefined reference to `posix_memalign'
collect2: error: ld returned 1 exit status
Makefile:150: recipe for target 'enclave/enclave.so' failed
make: *** [enclave/enclave.so] Error 1

**In function `__rg_alloc_zeroed':
sgx_tstd15-b7871f5ef2fc69b240503e44dd6ff56.rs:(.text.__rg_alloc_zeroed+0x45): undefined reference to `posix_memalign'**

ubuntu16.04

$ rustup toolchain list
nightly-2018-04-12-x86_64-unknown-linux-gnu (default)
nightly-2018-05-23-x86_64-unknown-linux-gnu

Would you please help me on this error? I cannot find an answer by google.

**Comment by dingelish** [comment]
Hi there,

sgx_tstd does require posix_memalign which is disabled in Intel's tlibc by default. Please refer to the dockerfile [here](https://github.com/baidu/rust-sgx-sdk/blob/7f14232acabff3ad4add6deab87aba2498831555/dockerfile/Dockerfile#L60) to see how to patch tlibc.

Overall, you need to take the following step for this patch:
1. Download the correct version of linux-sgx sdk source code from Intel's github.
2. Apply the given [patch](https://github.com/baidu/rust-sgx-sdk/raw/master/dockerfile/patch).
3. Compile the entire sdk
4. Copy the generated libsgx_tlibc.a to the SDK/lib64 dir to overwrite the existing one.

These steps has been hard-coded in the [dockerfile](https://github.com/baidu/rust-sgx-sdk/blob/master/dockerfile/Dockerfile).

Best,
Yu

**Comment by EighteenZi** [comment]
Great!
Yes, i read the dockerfile, but i missed the patch -_-!
Thanks, Yu.

**Comment by EighteenZi** [comment]
There is another question.
It seems like that rust-sgx-sdk doesn't support nightly-2018-05-23.
When i compile 'hello-rust' with nightly-2018-05-23, the following error will appear.

> error[E0407]: method `oom` is not a member of trait `Alloc`
  --> /home/sgx/.cargo/registry/src/mirrors.ustc.edu.cn-b63e9dae659fc205/sgx_alloc-1.0.0/src/lib.rs:80:5
   |
80 | /     fn oom(&mut self, err: AllocErr) -> ! {
81 | |         (&*self).oom(err)
82 | |     }
   | |_____^ not a member of trait `Alloc`

Maybe it's caused by differences between the 2 rust standard libraries.

Will you update the rust toolchain?

**Comment by dingelish** [comment]
Yes. I’ll release an update to support recent rust nightly in a couple of days.
