### ISSUE TITLE
TLS -> TCS policy must be bound

### ISSUE THREAD

**Issue by fredfortier** [apache/teaclave-sgx-sdk#240]
I recently upgraded to sdk 1.1.2, and I'm getting this error with a TLS client similar to the example provided.
```
thread '<unnamed>' panicked at 'Can not access a Thread Local Storage value: AccessError { msg: "If TLS data needs to be destructed, TCS policy must be Bound." }', /root/.cargo/git/checkouts/teaclave-sgx-sdk-be25c2ad2f03718d/253b3ac/sgx_tstd/src/thread/local.rs:148:9
note: Call backtrace::enable_backtrace with 'PrintFormat::Short/Full' for a backtrace.
fatal runtime error: failed to initiate panic, error 5
```

Any clues on how to investigate would be appreciated.

**Comment by Zha0Chan** [comment]
Please configure Enclave.config.xml
> TCSPolicy TCS management policy.
0 – TCS is bound to the untrusted
thread.
1 – TCS is not bound to the untrusted
thread.

https://download.01.org/intel-sgx/linux-2.2/docs/Intel_SGX_Developer_Reference_Linux_2.2_Open_Source.pdf

**Comment by dingelish** [comment]
> I recently upgraded to sdk 1.1.2, and I'm getting this error with a TLS client similar to the example provided.
> 
> ```
> thread '<unnamed>' panicked at 'Can not access a Thread Local Storage value: AccessError { msg: "If TLS data needs to be destructed, TCS policy must be Bound." }', /root/.cargo/git/checkouts/teaclave-sgx-sdk-be25c2ad2f03718d/253b3ac/sgx_tstd/src/thread/local.rs:148:9
> note: Call backtrace::enable_backtrace with 'PrintFormat::Short/Full' for a backtrace.
> fatal runtime error: failed to initiate panic, error 5
> ```
> 
> Any clues on how to investigate would be appreciated.

The reason is that something is relying on thread local storage, while your enclave is configured as `TCSPOLICY = UNBOUND` which means your enclave does not support thread local storage.

The most frequent case is using `rand::thread_rng`, which depends on thread local storage.

**Comment by volcano0dr** [comment]
When `TCSPOLICY = UNBOUND`, each root ECALL will re-initialize thread local storage, so in most cases, when using thread local storage, you should configure the enclave TCS policy to bound.

**Comment by fredfortier** [comment]
Thank you so much guys! These were all the right clues. I did recently start using `rand::thread_rng` in the untrusted module. I suspect that this is what caused the error rather than the SDK upgrade. Setting `<TCSPolicy>0</TCSPolicy>` worked although I'm reading more about it to understand its ramification.
