### ISSUE TITLE
duplicate lang item in crate `sgx_tstd`

### ISSUE THREAD

**Issue by 60ke** [apache/teaclave-sgx-sdk#242]
```shell
error: duplicate lang item in crate `sgx_tstd` (which `testenclave` depends on): `f32_runtime`.
  |
  = note: the lang item is first defined in crate `sgx_tstd` (which `serde` depends on)

error: duplicate lang item in crate `sgx_tstd` (which `testenclave`` depends on): `f64_runtime`.
  |
  = note: the lang item is first defined in crate `sgx_tstd` (which `serde` depends on)

error: duplicate lang item in crate `sgx_tstd` (which `testenclave`` depends on): `panic_impl`.
  |
  = note: the lang item is first defined in crate `sgx_tstd` (which `serde` depends on)

error: duplicate lang item in crate `sgx_tstd` (which `testenclave`` depends on): `begin_panic`.
  |
  = note: the lang item is first defined in crate `sgx_tstd` (which `serde` depends on)

error: duplicate lang item in crate `sgx_tstd` (which `testenclave`` depends on): `oom`.
  |
  = note: the lang item is first defined in crate `sgx_tstd` (which `serde` depends on)
```

Cargo.toml中使用的是:
serde = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_derive = { git = "https://github.com/mesalock-linux/serde-sgx" }

**Comment by mssun** [comment]
You have mixed different std (Rust's std or different version of `sgx_tstd`). Make sure to check your dependencies, all `sgx_std` depdencies should be from same source+tag.

**Comment by Zha0Chan** [comment]
whether to contain depend on other third-party libraries without ported？

**Comment by 60ke** [comment]
I change `sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk.git" }` to `sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git" }` . 
Problem solved.
Uh, I thought `https://github.com/baidu/rust-sgx-sdk.git`  was ok. But i'm wrong.

**Comment by NTSC-J** [comment]
Recently, I had the same problem.
In my case, I set `sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git" }` and it failed.
So, should I keep using the URI `https://github.com/apache/teaclave-sgx-sdk.git` even though it's old?
That's okay, but not straightforward I feel.
