### ISSUE TITLE
框架现在支持dcap吗？

### ISSUE THREAD

**Issue by 60ke** [apache/teaclave-sgx-sdk#249]
我在这里看到有引用: [sgx_qe_set_enclave_load_policy](https://github.com/apache/incubator-teaclave-sgx-sdk/blob/7b87824b9165e5b7a3ad21876e4a65b8c076fdb3/sgx_types/src/function.rs#L700)第三方远程证实的一些函数，但是调用的时候报错
```bash
undefined reference to `sgx_qe_set_enclave_load_policy'
undefined reference to `sgx_ql_set_path'
undefined reference to `sgx_ql_set_path'
undefined reference to `sgx_ql_set_path'
undefined reference to `sgx_qe_get_target_info'
undefined reference to `sgx_qe_get_quote_size'
undefined reference to `sgx_qe_get_quote'
```
想确定一下这个错误是我代码本身的问题，还是因为框架还不支持dcap

**Comment by mssun** [comment]
Yes, please refer to these reference implementation: https://github.com/apache/incubator-teaclave/tree/master/dcap

For your error, you should install DCAP related libraries for linking. See [DCAP installation guide](https://download.01.org/intel-sgx/sgx-dcap/1.3.1/linux/docs/Intel_SGX_DCAP_Linux_SW_Installation_Guide.pdf).

**Comment by 60ke** [comment]
> Yes, please refer to these reference implementation: https://github.com/apache/incubator-teaclave/tree/master/dcap
> 
> For your error, you should install DCAP related libraries for linking. See [DCAP installation guide](https://download.01.org/intel-sgx/sgx-dcap/1.3.1/linux/docs/Intel_SGX_DCAP_Linux_SW_Installation_Guide.pdf).
```bash
root@useer-04:/usr/lib/x86_64-linux-gnu# ls |grep sgx
libsgx_dcap_ql.so
libsgx_dcap_ql.so.1
libsgx_dcap_ql.so.1.6.100.2
libsgx_dcap_quoteverify.so
libsgx_dcap_quoteverify.so.1
libsgx_dcap_quoteverify.so.1.6.100.2
libsgx_default_qcnl_wrapper.so
libsgx_default_qcnl_wrapper.so.1
libsgx_default_qcnl_wrapper.so.1.6.100.2
libsgx_enclave_common.so
libsgx_enclave_common.so.1
libsgx_enclave_common.so.1.0.110.2
libsgx_epid.so.1
libsgx_epid.so.1.0.105.2
libsgx_launch.so.1
libsgx_launch.so.1.0.105.2
libsgx_pce_logic.so
libsgx_pce.signed.so
libsgx_qe3_logic.so
libsgx_qe3.signed.so
libsgx_quote_ex.so
libsgx_quote_ex.so.1
libsgx_quote_ex.so.1.1.105.2
libsgx_qve.signed.so
libsgx_urts.so
libsgx_urts.so.1
libsgx_urts.so.1.1.107.2

root@useer-04:/usr/include# ls |grep sgx
sgx_attributes.h
sgx_dcap_pcs_com.h
sgx_dcap_ql_wrapper.h
sgx_dcap_quoteverify.h
sgx_enclave_common.h
sgx_key.h
sgx_pce.h
sgx_ql_lib_common.h
sgx_ql_quote.h
sgx_quote_3.h
sgx_quote.h
sgx_report.h
sgx_uae_quote_ex.h

```
dcap我是安装过了，我是按照rust_sgx_sdk项目下面的samplecode构建的，之前写其它例子是没问题的。这个dcap链接的问题，是要修改[RustEnclave_Link_Flags](https://github.com/apache/incubator-teaclave-sgx-sdk/blob/7b87824b9165e5b7a3ad21876e4a65b8c076fdb3/samplecode/hello-rust/Makefile#L100)的参数吗? 有在samplecode出dacp示例的计划吗？

**Comment by dingelish** [comment]
> > Yes, please refer to these reference implementation: https://github.com/apache/incubator-teaclave/tree/master/dcap
> > For your error, you should install DCAP related libraries for linking. See [DCAP installation guide](https://download.01.org/intel-sgx/sgx-dcap/1.3.1/linux/docs/Intel_SGX_DCAP_Linux_SW_Installation_Guide.pdf).
> 
> ```shell
> root@useer-04:/usr/lib/x86_64-linux-gnu# ls |grep sgx
> libsgx_dcap_ql.so
> libsgx_dcap_ql.so.1
> libsgx_dcap_ql.so.1.6.100.2
> libsgx_dcap_quoteverify.so
> libsgx_dcap_quoteverify.so.1
> libsgx_dcap_quoteverify.so.1.6.100.2
> libsgx_default_qcnl_wrapper.so
> libsgx_default_qcnl_wrapper.so.1
> libsgx_default_qcnl_wrapper.so.1.6.100.2
> libsgx_enclave_common.so
> libsgx_enclave_common.so.1
> libsgx_enclave_common.so.1.0.110.2
> libsgx_epid.so.1
> libsgx_epid.so.1.0.105.2
> libsgx_launch.so.1
> libsgx_launch.so.1.0.105.2
> libsgx_pce_logic.so
> libsgx_pce.signed.so
> libsgx_qe3_logic.so
> libsgx_qe3.signed.so
> libsgx_quote_ex.so
> libsgx_quote_ex.so.1
> libsgx_quote_ex.so.1.1.105.2
> libsgx_qve.signed.so
> libsgx_urts.so
> libsgx_urts.so.1
> libsgx_urts.so.1.1.107.2
> 
> root@useer-04:/usr/include# ls |grep sgx
> sgx_attributes.h
> sgx_dcap_pcs_com.h
> sgx_dcap_ql_wrapper.h
> sgx_dcap_quoteverify.h
> sgx_enclave_common.h
> sgx_key.h
> sgx_pce.h
> sgx_ql_lib_common.h
> sgx_ql_quote.h
> sgx_quote_3.h
> sgx_quote.h
> sgx_report.h
> sgx_uae_quote_ex.h
> ```
> 
> dcap我是安装过了，我是按照rust_sgx_sdk项目下面的samplecode构建的，之前写其它例子是没问题的。这个dcap链接的问题，是要修改[RustEnclave_Link_Flags](https://github.com/apache/incubator-teaclave-sgx-sdk/blob/7b87824b9165e5b7a3ad21876e4a65b8c076fdb3/samplecode/hello-rust/Makefile#L100)的参数吗? 有在samplecode出dacp示例的计划吗？

这周我会传一个dcap pck retrival的重写例子，link到dcap ql，到时候你可以参考

**Comment by dingelish** [comment]
请参考 #250 。谢谢！
