### ISSUE TITLE
No return value of u_malloc_ocall from sgx_ustdc

### ISSUE THREAD

**Issue by henrysun007** [apache/teaclave-sgx-sdk#265]
The function definition is here: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/6e720490c813bd6b67b81e645e73e76a39e75d73/sgx_ustdc/mem.c#L23-L29
It should return ```ret``` explicitly.

**Comment by dingelish** [comment]
@henrysun007 Please check if #266 fixes it. Thanks!

**Comment by henrysun007** [comment]
Yes. I am closing the issue as the bug has been fixed.
