### ISSUE TITLE
Failed to run 'hello-rust'

### ISSUE THREAD

**Issue by EighteenZi** [apache/teaclave-sgx-sdk#29]

**Comment by EighteenZi** [comment]
I got the error below when i ran 'hello-rust', showing that the enclave created failed.
but i can succeed in running SampleEnclave copyed from intel's sdk and print something out.

[+] Home dir is /home/sgx
[+] Open token file success! 
[+] Token file valid!
[-] Init Enclave Failed SGX_ERROR_ENCLAVE_FILE_ACCESS!

Did i miss something?
The version of rust toolchain  is nightly-2018-04-12-x86_64-unknown-linux-gnu.

**Comment by dingelish** [comment]
Hi @EighteenZi , did you `cd bin && ./app` or just `./bin/app`? The latter would not work because i'm lazy with the path searching ...

**Comment by EighteenZi** [comment]
Oh, I didn't read the code very carefully.
Thanks.

Maybe it's better to describe it in README :)
