### ISSUE TITLE
SGX_RSA3072_DEFAULT_E has different value from documented one.

### ISSUE THREAD

**Issue by clangenb** [apache/teaclave-sgx-sdk#296]
The default exponent is documented to be 65537, see:

 https://github.com/apache/incubator-teaclave-sgx-sdk/blob/255b2093ea39ce7b9729135e65c75cdd9045b379/sgx_crypto_helper/src/rsa3072.rs#L7

However: `[0x01, 0x00, 0x00, 0x01]` equals 16777217

It should be: `[0x00, 0x01, 0x00, 0x01]`, which equals 65537

**Comment by dingelish** [comment]
fixed by #299  :-) thanks!
