### ISSUE TITLE
Potential Bug in sgx::tseal::SgxSealedData::<[T]>::unseal_data

### ISSUE THREAD

**Issue by silvanegli** [apache/teaclave-sgx-sdk#30]
I recently ran into an issue while using the [sgx::tseal::SgxSealedData::<[T]>::unseal_data](https://dingelish.github.io/sgx_tseal/sgx_tseal/struct.SgxSealedData.html#method.unseal_data-) function. While the following code runs as expected (as an Ecall inside an enclave) printing out 123456789
```rust
#[no_mangle]
pub extern "C" fn test_number_sealing() {
    let data: u64 = 123456789;
    let aad: [u8; 0] = [0_u8; 0];
    let sealed_data = SgxSealedData::<u64>::seal_data(&aad, &data).expect("error while sealing u64");
    let unsealed_data = sealed_data.unseal_data().expect("error while unsealing u64");
    println!("unsealed data: {:?}", unsealed_data.get_decrypt_txt());
}
```
this produces a Segmentation fault.
```rust
#[no_mangle]
pub extern "C" fn test_array_sealing() {
    let data: [u8; 10] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    let aad: [u8; 0] = [0_u8; 0];
    let sealed_data = SgxSealedData::<[u8]>::seal_data(&aad, &data).expect("error while sealing array");
    let unsealed_data = sealed_data.unseal_data().expect("error while unsealing array");
    println!("unsealed data: {:?}", unsealed_data.get_decrypt_txt());
}

```
Debugging the code revealed that at function exit dropping the _unsealed_data_ variable lead to freeing the pointer pointing to the decrypted memory region twice. 

Changing the [unseal_data(&self) -> SgxResult<SgxUnsealedData<'a, [T]>>](https://dingelish.github.io/sgx_tseal/src/sgx_tseal/seal.rs.html#681-705) function to the following
```rust
    pub fn unseal_data(&self) -> SgxResult<SgxUnsealedData<'a, [T]>> {
        let size = mem::size_of::<T>();
        if size == 0 {
            return Err(sgx_status_t::SGX_ERROR_INVALID_PARAMETER);
        }
        let encrypt_len = self.get_encrypt_txt_len() as usize;
        if size > encrypt_len {
            return Err(sgx_status_t::SGX_ERROR_MAC_MISMATCH);
        }
        if (encrypt_len % size) != 0 {
            return Err(sgx_status_t::SGX_ERROR_MAC_MISMATCH);
        }
        self.inner.unseal_data().map(|x| {
            let ptr = Box::into_raw(x.decrypt);
            let slice = unsafe{slice::from_raw_parts_mut(ptr as * mut T, encrypt_len/size)};
            SgxUnsealedData {
                payload_size: x.payload_size,
                decrypt: unsafe{Box::from_raw(slice as * mut [T])},
                additional: x.additional,
                marker: PhantomData,
            }
        })
    }
```
resolved my issue. Probably due to the fact explained [here](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.from_raw) 

> After calling this function, the raw pointer is owned by the resulting Box. Specifically, the Box destructor will call the destructor of T and free the allocated memory. Since the way Box allocates and releases memory is unspecified, the only valid pointer to pass to this function is the one taken from another Box via the Box::into_raw function.
This function is unsafe because improper use may lead to memory problems. For example, a double-free may occur if the function is called twice on the same raw pointer.

**Comment by dingelish** [comment]
Thank you very much @silvanegli ! You're right. This is a bug. I've just merged your patch. Please double check if this [commit](https://github.com/baidu/rust-sgx-sdk/commit/c96d1d34630e7f3b53a62701bb121cfa664d72b6) is correct. Thanks again!

**Comment by silvanegli** [comment]
You' re welcome. Looks good, perfect !

**Comment by dingelish** [comment]
Crate updated on [https://crates.io/crates/sgx_tseal](https://crates.io/crates/sgx_tseal). Have a nice day!
