### ISSUE TITLE
upgrade serde_json to v1.0.60

### ISSUE THREAD

**Issue by haerdib** [apache/teaclave-sgx-sdk#302]
This is an issue concerning mesalock-linux, I hope it's okay if I post this here.

I'm currently working on a version of jsonrpc-core supporting no-std (see the [issue](https://github.com/paritytech/jsonrpc/issues/601)). I have my first working version ([github](https://github.com/scs/jsonrpc/tree/601/no-std-core)) and would like to test it in within the sgx. However, due to multiple serde dependencies I need to patch it with mesalock serde-json. 
My dependencies require serde_json v1.0.60, and the current mesalock serde version is lagging behind, hence cargo doesnt apply the patch. Would it be possible to upgrade the mesalock dependencies to serde_json v1.0.60? 

Thank you very much in advance!

**Comment by dingelish** [comment]
no problem! thanks for your support :-)

**Comment by dingelish** [comment]
@haerdib upgraded. please check it out!

**Comment by haerdib** [comment]
That was fast, thanks alot! serde-json patching is now working. 👍 
Of course the next problem was just around the corner. Serde mesalock also needs an update to atleast v.1.0.118 (current mesalock version: 1.0.117). @dingelish, would it be possible to update serde aswell?

**Comment by dingelish** [comment]
completed!

**Comment by haerdib** [comment]
Perfect. thank you very much. 👍
