### ISSUE TITLE
Any plan to update sgx_cov

### ISSUE THREAD

**Issue by henrysun007** [apache/teaclave-sgx-sdk#306]
LLVM has changed the profiling API. Sgx_cov is no longer compatible with the latest `cargo`. Do you have any plan to fix the inconsistency?

**Comment by dingelish** [comment]
hi @henrysun007 , thanks for this report! yes it should be a bug. we'll definitely fix that. but no eta yet... i'll look into it whenever i've got time

**Comment by dingelish** [comment]
and could you please give some hint on upstream llvm's change? documents/commit id will be helpful. thanks!

**Comment by dingelish** [comment]
never mind. i got the changes. will work on it.

**Comment by dingelish** [comment]
@volcano0dr please help trigger `uninit_global_object` in `t_global_exit_ecall` and make it feature gated, since we need to remove it after `edmm` is public available.

**Comment by dingelish** [comment]
@henrysun007 almost there! please checkout https://github.com/apache/incubator-teaclave-sgx-sdk/pull/309 . the only problem now is xargo support. cargo works perfectly with `gcov` <= 7 and `llvm-cov` >= 11

**Comment by dingelish** [comment]
it's done! please checkout the latest sgx-cov sample!

closed by #307 and #309

**Comment by henrysun007** [comment]
Excellent! You guys are awesome! Let me try this out!
