### ISSUE TITLE
Is there any tool for enclave memory measurement?

### ISSUE THREAD

**Issue by Lanjiejie** [apache/teaclave-sgx-sdk#310]
I want to measure the enclave memory cost. Is there any tool? Can it use in simulator mode?

**Comment by dingelish** [comment]
please check out https://download.01.org/intel-sgx/sgx-linux/2.12/docs/Intel_SGX_Developer_Reference_Linux_2.12_Open_Source.pdf

page 25

Enclave Memory Measurement Tool
An enclave is an isolated environment. The Intel® Software Guard Extensions SDK provides a tool called sgx_emmt to measure the real usage of protected memory by the enclave at runtime.
