### ISSUE TITLE
upgrade mesalock-linux / log-sgx  to v0.4.14

### ISSUE THREAD

**Issue by haerdib** [apache/teaclave-sgx-sdk#323]
Hi there,

we'd like to upgrade our project dependencies which unfortunately depend on log 0.4.14. Since mesalock is currently at 0.4.11 cargo throws an failed to select version for 'log' error.

Would it be possible to upgrade log-sgx to >=0.4.14? Thanks alot!

**Comment by dingelish** [comment]
@haerdib updated!

**Comment by haerdib** [comment]
Sorry for the late answer. Its working perfectly, thank you very much!
