### ISSUE TITLE
Rls not finding sgx_tstd in VS Code within Docker image

### ISSUE THREAD

**Issue by dhuynh95** [apache/teaclave-sgx-sdk#334]
Hello everyone,

I use WSL 2 on my laptop, and pulled the `baiduxlab/sgx-rust` Docker image to develop with Rust SGX in simulation mode. Once I am connected to the Docker image using VS Code, 

I manage to compile the `helloworld` sample in simulation and get it to work.

However, when I try to use the Rust plugin in VS Code with rls, I get the following error : 

![image](https://user-images.githubusercontent.com/36925557/112944940-dfdb8f80-9133-11eb-828c-aaa7f8407ec7.png)

I am not familiar with the inner workings of rls but it seems that it `tstd` was not found by rls but I don't know how I could do to add it ro rls. 

Could anyone help me solve this issue ?
Thanks

**Comment by dingelish** [comment]
hi @dhuynh95 , this could be a bug of rls or misconfiguration of rls, but i'm not familiar with rls and vscode so can't give you a precise solution. i looked into such issues in the past and had this [note](https://github.com/apache/incubator-teaclave-sgx-sdk/wiki/Use-VSCode---rls---rust-analysis---sgx-gdb-for-graphic-developing-(not-in-docker)) . wish it helps ...
