### ISSUE TITLE
about DCAP based RA

### ISSUE THREAD

**Issue by colourtemp** [apache/teaclave-sgx-sdk#343]
Hi. I recently tried to re-invent ecdsa quote generation (pretty much the same as samplecode/dcap-pckretrieval) and ecdsa quote verification in code v1.1.3. The problem is sgx_qv_verify_quote will always return with the error SGX_QL_PCK_CERT_UNSUPPORTED_FORMAT. Got no clue what causes it. Just wondering if these functionalities are fully useable in v1.1.3? Are there more DCAP based RA sample codes coming out?

**Comment by volcano0dr** [comment]
possible cause: The PCK certificate chain is not included in the ECDSA quote.
PCCS service needs to be installed to generate ECDSA quote.
[https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/QuoteGeneration/pccs](url)
