### ISSUE TITLE
Transplant rust crates to sgx sdk

### ISSUE THREAD

**Issue by ClawSeven** [apache/teaclave-sgx-sdk#344]
Hi, I have a question about how to transplant rust crates [resolv-conf](https://github.com/tailhook/resolv-conf) to sgx sdk. I have followed the steps in [SGXfail](https://github.com/dingelish/SGXfail/blob/master/04.md), but the bugs present as `could not compile `sgx_alloc``. And I read some code in [sgx-world](https://github.com/dingelish/sgx-world), but it is hard for me to employ same strategy.

**Comment by volcano0dr** [comment]
Can you provide the error message when compiling `sgx_alloc`? 
What version of rust are you using?

**Comment by ClawSeven** [comment]
Thanks for reminding modify Rust version, when I change rust version to nightly-2020-10-25, problem solved. And I successfully transplant resolv-conf crate into sgx-world [https://github.com/ClawSeven/resolv-conf] and apply this crate to occlum.
