### ISSUE TITLE
`sgx_align_struct_attribute` compile error

### ISSUE THREAD

**Issue by EmisonLu** [apache/teaclave-sgx-sdk#364]
rust-sdk version: v1.1.4
rustc version: rustc 1.57.0-nightly (51e514c0f 2021-09-12)
When I use `cargo b` in the folder `sgx_align_struct_attribute`, the following error is reported:
```
error[E0658]: use of unstable library feature 'proc_macro_is_available'
  --> /home/emison/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/proc-macro2-1.0.33/src/detection.rs:28:21
   |
28 |     let available = proc_macro::is_available();
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #71436 <https://github.com/rust-lang/rust/issues/71436> for more information
   = help: add `#![feature(proc_macro_is_available)]` to the crate attributes to enable
```

**Comment by volcano0dr** [comment]
Thank you for reporting this issue.
I am aware of this issue and I will fix it by upgrading the rust toolchain to `nightly-2021-11-01`.
https://github.com/rust-lang/rust/issues/71436

**Comment by volcano0dr** [comment]
@EmisonLu I have upgraded rust-toolchain to `nightly-2021-11-01.`

**Comment by EmisonLu** [comment]
Many thanks!
