### ISSUE TITLE
What is the difference between this repo and apache/incubator-teaclave?

### ISSUE THREAD

**Issue by SHiftLin** [apache/teaclave-sgx-sdk#365]
Hi I am new to Teaclave. I found two repos about Teaclave, one is this repo, and the another is https://github.com/apache/incubator-teaclave. I am confused by their difference. It seems that the site https://teaclave.apache.org/ only introduces the latter and does not contain instructions on this repo?

Thanks!

**Comment by mssun** [comment]
Teaclave has several subprojects:
- Teaclave: a FaaS confidential computing platform
- Teaclave SGX SDK: a Rust SDK for developing SGX apps
- Teaclave TrustZone SDK: a Rust SDK for developing TrustZone apps

The homepage contains information (SDK introductions, docs, API docs) of these three projects.

**Comment by SHiftLin** [comment]
Thanks for your amazing fast reply!
