### ISSUE TITLE
Running `mutual-ra` on different physical machines

### ISSUE THREAD

**Issue by algon-320** [apache/teaclave-sgx-sdk#369]
Hello,

I'm trying to run the `mutual-ra` sample program on different physical machines (running a server on machine A and a client on machine B), but I got `SGX_ERROR_UNEXPECTED` error on `ocall_get_update_info` [call](https://github.com/apache/incubator-teaclave-sgx-sdk/blob/565960cd7b4b36d1188459d75652619971c43f7e/samplecode/mutual-ra/enclave/src/cert.rs#L321-L324).
When I run both sides on the same machine, it works well.

Apparently, the root cause is calling `ocall_get_update_info` with the other machine's `platformInfoBlob` as an argument.

I wrote a simple [test program](https://gist.github.com/algon-320/9256454fb8d9ba8ad44bc3877d644175) which just calls `sgx_report_attestation_status` (actual function `ocall_get_update_info` calls).
When I give a machine's PIB and run the program on the same machine, it works as I expected (resulting in `SGX_SUCCESS` or `SGX_ERROR_UPDATE_NEEDED`).
However, when I give a machine's PIB and run the program on **the other machine**, it results in `SGX_ERROR_UNEXPECTED`.

I'm not completely sure about `sgx_report_attestation_status` SDK function,
but it seems to expect to be called on the same machine as the source of the `platformInfoBlob`.

So, now I have two questions:
1. Is the `mutual-ra` sample program expected to run on different physical machines?
2. Can we call `sgx_report_attestation_status` with a `platformInfoBlob` generated on another physical machine?

<details>
<summary>My configuration</summary>

- machine A:
    - Motherboard: ASUS PRIME Z390-A
    - CPU: Core i7-9700K
    - OS: Ubuntu 20.04.3 LTS (Linux 5.11.0-46-generic)
    - Driver: in-kernel
    - PSW, SDK: latest
    - SGX supported: Yes
    - SGX launch config supported: Yes

- machine B:
    - System: Lenovo ThinkPad X1 Carbon 6th
    - CPU: i7-8550U
    - OS: Ubuntu 20.04.3 LTS (Linux 5.11.0-46-generic) with `nosgx` parameter
    - Driver: OOT-driver 2.11
    - PSW, SDK: latest
    - SGX supported: Yes
    - SGX launch config supported: No

</details>

**Comment by volcano0dr** [comment]
We can't call `sgx_report_attestation_status` with a `platformInfoBlob` generated on another physical machine.
Please refer to: [https://api.trustedservices.intel.com/documents/sgx-attestation-api-spec.pdf](url)
3.2 Verify Attestation Evidence
3.2.1 Description

> Optionally, a signed Platform Info Blob Type-Length-Value (TLV)will be generated and included in the report (as defined in Platform Info Blobsection).The SP involved in the remote attestation process shouldforward Platform Info Blob, excluding the TLV header, to ISV SGX application running on the client platform that is being attested.The ISV SGX application can then process the Platform Info Blob using SGX SDK API sgx_report_attestation_status().

So,  The `mutual-ra` can't run on a different physical machine. 
Later, I will remove the call of `ocall_get_update_info`in the function that validates the `mra` certificate.

**Comment by algon-320** [comment]
Hi, @volcano0dr.

Thank you for the information!
After that, I made several changes to call `sgx_report_attestation_status` on the correct side and confirmed it works.

> Later, I will remove the call of `ocall_get_update_info` in the function that validates the `mra` certificate.

Should I close this issue? or leave it open until you apply the change?

**Comment by volcano0dr** [comment]
@algon-320 I have fixed the issue

**Comment by algon-320** [comment]
Thank you very much @volcano0dr . I'll close this issue.
