### ISSUE TITLE
PanicInfo in sgx_tstd

### ISSUE THREAD

**Issue by 4ncly** [apache/teaclave-sgx-sdk#375]
error[E0061]: this function takes 3 arguments but 2 arguments were supplied
   --> /root/sgx/sgx_tstd/src/panicking.rs:552:20
    |
552 |     let mut info = PanicInfo::internal_constructor(message, location);
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ -------  -------- supplied 2 arguments
    |                    |
    |                    expected 3 arguments

when i port a rust crate into rust sgx, why there is something with the sgx_tstd ?

**Comment by volcano0dr** [comment]
The reason the compilation fails is that the version of rust you are using is incompatible with the version of rust required by sgx_tstd.
sgx_tstd requires` rust-nightly-2021-11-01`

**Comment by 4ncly** [comment]
@volcano0dr thank you very much and i have just solved this problem with your method
