### ISSUE TITLE
Support for swapping 'std' in sysroot using xargo

### ISSUE THREAD

**Issue by tarcieri** [apache/teaclave-sgx-sdk#38]
xargo can potentially be used to swap in `sgx_tstd` for `std` using the [custom sysroot crate feature](https://github.com/japaric/xargo#creating-a-sysroot-with-custom-crates).

> Xargo lets you create a sysroot with custom crates. You can virtually put any crate in the sysroot. However, this feature is mainly used to create alternative std facades.

Hypothetically this would be something like:

```
[dependencies.std]
git = "https://github.com/baidu/sgx_tstd" # or whatever
stage = 2
```

I tried this at one point and ran into a weird error with `rustc` (something about a hack to prevent you from accidentally loading crates from the sysroot when you didn't mean to).

That said, if you can get it to work, it would allow any crate which is compatible with the subset of `std` which `sgx_tstd` implements to work out-of-the-box.

**Comment by dingelish** [comment]
Hi @tarcieri ,

Sorry for the late reply. I'll prepare for the 'mirror' very soon. Thanks!

**Comment by dingelish** [comment]
Hi @tarcieri , i found [this](https://github.com/blockchainhelppro/Connect-Core-to-Andriod/blob/076966120d2887a0e50a27c432270cca832f1993/Xargo.toml). It works amazingly on my code samples.
