### ISSUE TITLE
about dcap interface version

### ISSUE THREAD

**Issue by colourtemp** [apache/teaclave-sgx-sdk#381]
As commented, the SDK now supports DCAP 1.6 (like sgx_ql_set_path function), yet Intel has released DCAP 1.13 and there are already changes happened (like enum sgx_ql_path_type_t now has 4 variables). Just wondering if there is a planned update to catch up.

**Comment by volcano0dr** [comment]
I have submitted a  PR #380   which will be merged into master after review.

**Comment by colourtemp** [comment]
bravo
