### ISSUE TITLE
请更新下SDK中远程认证(ue-ra)中的代码

### ISSUE THREAD

**Issue by xin201501** [apache/teaclave-sgx-sdk#383]
我收到intel邮件提示
>2022年8月16日`DEV Intel® Software Guard Extensions Attestation Service (IAS) API version 3`会结束支持，请尽快升级到version4。

我看到API v4中有些数据结构的定义似乎发生了变化。可以更新下Teaclave SGX SDK中`samplecode`中`ue-ra`的代码并给一些从V3迁移到V4的建议吗，谢谢。

**Comment by mssun** [comment]
Teaclave 是基于 version 4 实现的 IAS attestation (https://github.com/apache/incubator-teaclave/blob/master/attestation/src/service.rs#L42) ，可以参考对应的代码。

对于 samplecode 的更新，欢迎提交 PR 贡献。
