### ISSUE TITLE
Trying to compile sample code on the v2.0.0-preview branch fails

### ISSUE THREAD

**Issue by reuvenpo** [apache/teaclave-sgx-sdk#387]
When switching to the `v2.0.0-preview` branch and trying to compile the `helloworld` or `httpreq` examples with `make clean all` fails with:

```
SDK version is not correct. The same SDK should be used for enclave building and signing.
The SDK version for building enclave could be obtained by below command:

           $ strings {Enclave.so} | grep SGX_TSTDC_VERSION 

Error happened while signing the enclave.
```

I haven't tried the others yet, but this happens with any of the `BUILD_STD` settings, either `no`, `cargo`, or `xargo`.

I have the latest packages installed [as per the guide here](https://teaclave.apache.org/docs/my-first-function/) (I believe). Is there a specific version, dependency, or similar that I need in addition to it? Compiling on v1.1.4 does work without issue.

**Comment by volcano0dr** [comment]
Thank you for using version `v2.0.0-preview.` Please install `intel sgx sdk 2.16` and use  `sgx_sign` to re-sign enclave.

**Comment by reuvenpo** [comment]
@volcano0dr Thanks, that worked!
I installed the SDK from here:
https://download.01.org/intel-sgx/sgx-linux/2.16/distro/ubuntu18.04-server/
