### ISSUE TITLE
Garbled circuit implementation

### ISSUE THREAD

**Issue by Joschuka** [apache/teaclave-sgx-sdk#39]
Hello guys,

I wouldlike to know if there is a simple way to implement garbled circuit using the rust-sgx framework. I saw that there's a third party library in C making it easier to do such circuits but it is not supported at the moment. https://github.com/esonghori/TinyGarble

Is there a way to implement garbled circuits or to make the library compatible with rust-sgx ?

**Comment by dingelish** [comment]
Hi @intelphd ,

Why do you need GC within SGX enclave?

With SGX, we can construct 100% trusted enclave. Each party could send its own secret to the trusted enclave after remote attestation. The trusted enclave computes f() and sends results back to each party respectively. Nobody could touch those secrets because SGX protects them. Everybody trust the result because they attested the SGX enclave.

GC is designed to solve SMC without any trusted party. We could achieve a better solution by simply constructing a trusted f() calculator in an enclave.

**Comment by Joschuka** [comment]
Hi @dingelish ,

The idea would be to do the garbling/regarbling operation into an sgx enclave instead of the user doing it, it would be useful if he doesn't have the computational means to do so.

**Comment by dingelish** [comment]
Got it.

Is [libgc](https://github.com/aead/libgc) an option?

**Comment by Joschuka** [comment]
It seems to be able to do what I need, so I think so !

**Comment by Joschuka** [comment]
Actually it seems to just convert an already garbled circuit right ? It doesn't have some regarbling feature, would I need to do this by hand in the enclave then ?

**Comment by dingelish** [comment]
How about this? https://github.com/spaceships/boots

**Comment by Joschuka** [comment]
This one seems to do the garbling process indeed ! I just have no clue about the input format he uses. Also he seems to use a lot of scripts which could be a bit difficult to port on an enclave maybe.
However it seems to have all the functionnalities needed

**Comment by Joschuka** [comment]
@dingelish Can I actually use this library directly as a third party ? Or do you need to make some changes first ?
The first option would be great as I would need it in the next few days

**Comment by dingelish** [comment]
@intelphd 
If you need to put it into enclave, you need to do some porting work. Porting is simple on a lot of crates. You can try reading my [blog](https://github.com/dingelish/SGXfail/blob/master/04.md) on porting. :-)

**Comment by Joschuka** [comment]
Ok I'll try to do this tomorrow then, thanks a lot !

**Comment by Joschuka** [comment]
Hey @dingelish, 
I've been looking for another library and finally found one, I'm now doing the porting process.
Everything goes well until the last step in which I get some errors like :
`error : duplicate lag item in crate 'std' 
note : first defined in crate sgx_tstd`

There seems to be some conflict between std and its sgx  implementation. What is the best way to handle that please ? Do I have to use `extern sgx_tstd as std` at the beginning of each file of the third party ?

**Comment by davidp94** [comment]
yes And you add to the lib.rs #![no_std]

**Comment by Joschuka** [comment]
Thanks, I don't have this error anymore !
However I've got a lot of errors because Vec was used in the third party library, is there a way to avoid putting `use std::vec::Vec` at the beginning of each file or do I have to do it ?

**Comment by davidp94** [comment]
I think I would add it everywhere. (I am not an expert)

**Comment by Joschuka** [comment]
I just checked the machine learning samplecode and it seems I have to put it indeed ! Thanks a lot for your help :+1:

**Comment by dingelish** [comment]
First look at the doc of [std::prelude](https://doc.rust-lang.org/std/prelude/index.html). In a `std` environment, Rust compiler automatically adds `extern crate std` on each `lib.rs` and adds `use std::prelude::v1::*` at the head of each `.rs` file.

In the `cargo` world of rust-sgx, crates are build in `no_std` env and we manually import `std`. So we need to manually import `prelude` as well. To do that, please add `use std::prelude::v1::*` for each `.rs` file.

**Comment by davidp94** [comment]
Cool really interesting, thanks!

**Comment by Joschuka** [comment]
Thanks for the answer !

However the error wasn't gone unfortunatley, it was just hidden by the amount of Vec errors that appeared when I put the #![no_std] at the beginning.
I'm pretty sure I put everything needed at the beginning of each .rs file and I still got the conflict but the other way around this time :
`error : duplicate lag item in crate 'std' note : first defined in crate sgx_tstd`

**Comment by davidp94** [comment]
you should do the same for all dependencies (and their dependencies and so
on) of the crate you wanna port ( make them no_std)

**Comment by Joschuka** [comment]
I use the following library : https://github.com/spaceships/fancy-garbling
I patched the fancy-garbling/src/ files and the fancy-garbling/base_conversion/ files it should be enough right ?

**Comment by davidp94** [comment]
I checked the cargo.toml and there are some dependencies that you
should change the path from, or remove and import sgx_rand for
instance

https://github.com/spaceships/fancy-garbling/blob/master/Cargo.toml

**Comment by davidp94** [comment]
For num

https://github.com/baidu/rust-sgx-sdk/tree/master/third_party/num

**Comment by dingelish** [comment]
@intelphd 
David is right. This crate has several dep crates which very 'unfriendly' to `no_std`. I think it's too much difficult for you.

Let me do the porting and I'll keep you updated.

**Comment by Joschuka** [comment]
Thank you so much ! It would really help me !

**Comment by dingelish** [comment]
@intelphd 

Bad news. This crate depends on rust-gmp, which depends on external libgmp library, which cannot be put in to SGX environment.

**Comment by Joschuka** [comment]
I think gmp is only used in number.rs in some functions and I don't need these. Would it be possible to remove them and port the rest ?

**Comment by dingelish** [comment]
func defined in number.rs seems to be coupling tightly to the other codes. could you give me a simplified version which does not depend on rust-gmp? so that I can move on quickly

**Comment by Joschuka** [comment]
From what I see all the functions in number.rs that are used in the other files are not using rust-gmp Mpz, I believe the author didn't use them yet.
So I would assume you could straight up delete every function and statement involving rust-gmp in numbers.rs and it should be fine

**Comment by dingelish** [comment]
Nope.

`crt_inv` and `inv_u8` are exposed by `number.rs` and used by `high_level.rs`. Without these two function, `high_level.rs` cannot work as designed. Is that what you want?

**Comment by Joschuka** [comment]
You're right, I missed that unfortunately. So I won't have access to the decode function.
Would I be able to export the results from the enclave and use this decode outside of it ?

Either way could you still port it by deleting the parts of `high_level.rs` which contain `crt_inv` and 'inv_u8' please ? I'll find a way to decode

**Comment by Joschuka** [comment]
As long as I can encode the circuit inside the enclave it will be fine so that should be ok. The decoding and evaluation don't have to happen inside the enclave.

**Comment by Joschuka** [comment]
Hey @dingelish , 
Great news, the author was kind enough to remove the gmp dependency so we can port it directly now !

**Comment by dingelish** [comment]
Great! @intelphd i'll do this today or tomorrow :)

**Comment by Joschuka** [comment]
Thank you really much !

**Comment by dingelish** [comment]
Pushed in 1f3a5e420b3c21ee1a299eb44bfad9cf26348ef4. Please check if the ported [fancy-garbling](https://github.com/baidu/rust-sgx-sdk/tree/master/third_party/fancy-garbling) works!

**Comment by dingelish** [comment]
And please inform the author that I'm maintaining a modified version of his project and the original license is unmodified. Thanks!

**Comment by Joschuka** [comment]
It worked, thank you so much ! I'll tell him, don't worry ! 
Once again thanks a lot !
