### ISSUE TITLE
Support for Intel SGX SDK 2.17

### ISSUE THREAD

**Issue by clauverjat** [apache/teaclave-sgx-sdk#393]
Hello,

Intel has released a new version of its SDK yesterday. I know you are working on a v2 of the Teaclave SDK. Still, do you plan to add support for Intel SDK 2.17 in the current version (v1) ? 

Thank you

**Comment by volcano0dr** [comment]
I plan to support `Intel SGX SDK 2.17` on both `v1` and `v2`. The upgrade will be done soon.

**Comment by clauverjat** [comment]
That's great. Thanks

**Comment by tshepang** [comment]
looks like can be closed, for there is now support for v2.18

**Comment by clauverjat** [comment]
Indeed thanks
