### ISSUE TITLE
`sgx_uspfs` crate missing

### ISSUE THREAD

**Issue by tilosp** [apache/teaclave-sgx-sdk#395]
https://github.com/apache/incubator-teaclave-sgx-sdk/commit/605c8ea7a05d9d1a2536be66c09d3b5a06f348b0#diff-098172a73a9296db4489460ba19ef8590f2884d1336f5d9b99693bc8eae8f7e7R22 added a new dependency to `sgx_urts`. But this dependency is missing from this repo.

**Comment by volcano0dr** [comment]
Thanks for reporting this issue, I have fixed it.
[d2d339c](https://github.com/apache/incubator-teaclave-sgx-sdk/commit/d2d339cbb005f676bb700059bd51dc689c025f6b)

**Comment by tilosp** [comment]
Thanks a lot for resolving it this quickly.
