### ISSUE TITLE
Docker pull failed with unauthorized: authentication required

### ISSUE THREAD

**Issue by andyzyb** [apache/teaclave-sgx-sdk#4]
Always fail to pull the docker image with the error "unauthorized: authentication required".  Is that a private  docker repo?

**Comment by dingelish** [comment]
Hi there, I've double checked the docker image. It's [public](https://hub.docker.com/r/baiduxlab/sgx-rust/), and I've just successfully pulled one from a brand new linux machine.

**Comment by tarcieri** [comment]
I encountered this problem at one point as well. I think it might be a rate limit of some sort?

**Comment by dingelish** [comment]
This is really weird. I find one similar [case](https://github.com/docker/hub-feedback/issues/1131). Maybe a bug of docker hub?

**Comment by andyzyb** [comment]
May be some network issue, now I can pull the image successfully.

**Comment by Davidian1024** [comment]
I'm seeing this issue as well.  I'm logged in and I'm trying to pull the public jpbarto/boto3-docker image.  I get the same result for any public image.  But I am able to pull official images.  I enabled debugging and I see these messages in the system log.

Mar 30 15:54:49 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:49.547562252Z" level=debug msg="Calling GET /_ping"
Mar 30 15:54:49 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:49.548371586Z" level=debug msg="Calling GET /v1.37/info"
Mar 30 15:54:52 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:52.939167617Z" level=debug msg="Calling POST /v1.37/auth"
Mar 30 15:54:52 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:52.939861879Z" level=debug msg="form data: {\"password\":\"*****\",\"serveraddress\":\"https://index.docker.io/v1/\",\"username\":\"davidian1024\"}"
Mar 30 15:54:52 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:52.940297256Z" level=debug msg="attempting v2 login to registry endpoint https://registry-1.docker.io/v2/"
Mar 30 15:54:54 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:54.743986956Z" level=debug msg="Calling GET /_ping"
Mar 30 15:54:54 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:54.745111985Z" level=debug msg="Calling GET /v1.37/info"
Mar 30 15:54:54 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:54.753453621Z" level=debug msg="Calling POST /v1.37/images/create?fromImage=jpbarto%2Fboto3-docker&tag=latest"
Mar 30 15:54:54 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:54.753859828Z" level=debug msg="Trying to pull jpbarto/boto3-docker from https://registry-1.docker.io v2"
Mar 30 15:54:54 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:54.979651292Z" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Mar 30 15:54:54 ip-172-31-28-10 dockerd[9558]: time="2018-03-30T15:54:54.980062011Z" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"

**Comment by dingelish** [comment]
Hi David,

I've double checked this issue. I intend to believe it's a problem of dockerhub. I've just tried on my cluster which contains a dozen of servers. Each server could fetch the docker image without login. I've no idea how this happens -- do you have any idea?

Best,
Yu

**Comment by Davidian1024** [comment]
I decided to move that post to a different issue.  I didn't notice this one was closed when I first posted this.

I put it here:
https://github.com/docker/hub-feedback/issues/1131

I have no idea what's causing this.
