### ISSUE TITLE
One question about 'sgx_edger8r'

### ISSUE THREAD

**Issue by EighteenZi** [apache/teaclave-sgx-sdk#41]
Hi Yu,
I found one difference between interfaces in enclave_u.c generated by the tool 'sgx_edger8r'.
some interfaces' parameters contain 'eid: sgx_enclave_id_t' and `ret: *mut sgx_status_t` both, while some interfaces' parameters only have  'eid: sgx_enclave_id_t' . as follows.
```
fn foo(eid: sgx_enclave_id_t);
fn aes_gcm_128_encrypt(eid: sgx_enclave_id_t, ret: *mut sgx_status_t, ...)

```

Do you know which caused this difference? Thanks.

**Comment by dingelish** [comment]
It depends on whether or not you have defined the return value in EDL file. Here are my EDL guessings according to your examples:

```
void foo();
sgx_status_t aes_gcm_128_encrypt(...);
```
