### ISSUE TITLE
Problem when compiling the remoteattestation sample code

### ISSUE THREAD

**Issue by yang-sec** [apache/teaclave-sgx-sdk#42]
Hi Yu,

Could you help check the following problem I encountered when compiling the remoteattestation?

When I `make` the Application program within your docker, the following error occurs:

`make[1]: Leaving directory '/root/sgx/sgx_ustdc'
cp ../../../sgx_ustdc/libsgx_ustdc.a ./lib
/usr/bin/ld: cannot find -lsgx_ustdc
collect2: error: ld returned 1 exit status
`

When I tried `cp ../../../sgx_ustdc/libsgx_ustdc.a ./lib` outside your docker, it shows permissioned denied, and a `sudo` solves the problem. But the problem persists even if I added `sudo` inside that line in the makefile when running within your docker. So it seems a problem with docker. Can you help circumvent this?

Thanks much!
Yang

**Comment by dingelish** [comment]
Hi @mike123666 ,

Thanks for the bug report. I'll patch it today. Will keep you updated here.

Best,
Yu

**Comment by davidp94** [comment]
I personally added a `-L./lib` somewhere.

**Comment by dingelish** [comment]
Everything fixed in cc770441563785f48323c4093d44927ea1efb76b. Please check if it works! Thanks! @mike123666

**Comment by dingelish** [comment]
@davidp94 Please help me check it out. Thanks!

**Comment by yang-sec** [comment]
Thank you @dingelish @davidp94 !

**Comment by yang-sec** [comment]
Hello again:) I got another problem compiling the program after configuring `GeneralSettings.h` like this:


    static int rh_port = 22222;
    static string rh_host = "localhost";

    static string server_crt = "../server.crt"; //certificate for the HTTPS connection between the SP and the App
    static string server_key = "../server.key"; //private key for the HTTPS connection

    static string spid = "293XXXXXXXXXXXXXXXXXXXXXXXXXX0CB"; //SPID provided by Intel after registration for the IAS service
    static const char *ias_crt = "../client.crt"; //location of the certificate send to Intel when registring for the IAS
    static string ias_url = "https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v2/";

When I make ServiceProvider, I got:

> ...
CXX  <=  ../Networking/Session.cpp
In file included from /usr/include/openssl/ssl.h:1699:0,
                 from /usr/include/boost/asio/ssl/detail/openssl_types.hpp:20,
                 from /usr/include/boost/asio/ssl/context_base.hpp:19,
                 from /usr/include/boost/asio/ssl/context.hpp:27,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from ../Networking/AbstractNetworkOps.h:39,
                 from ../Networking/Client.h:32,
                 from ../Networking/Client.cpp:29:
/usr/include/openssl/dtls1.h:176:1: internal compiler error: Segmentation fault
 typedef struct hm_fragment_st {

When I make Application, I got:

> ...
CXX  <=  ../Networking/NetworkManager.cpp
In file included from /usr/include/boost/iterator/iterator_facade.hpp:16:0,
                 from /usr/include/boost/range/iterator_range_core.hpp:27,
                 from /usr/include/boost/range/iterator_range.hpp:13,
                 from /usr/include/boost/range/as_literal.hpp:22,
                 from /usr/include/boost/algorithm/string/trim.hpp:19,
                 from /usr/include/boost/algorithm/string.hpp:19,
                 from ../Networking/AbstractNetworkOps.h:44,
                 from ../Networking/Session.h:32,
                 from ../Networking/Session.cpp:29:
/usr/include/boost/iterator/detail/facade_iterator_category.hpp:53:5: internal compiler error: Segmentation fault
     }

And I put `server.key`, `server.crt`, `client.crt` under the remoteattestation folder. The SPID is what I received from Intel after registration. Could you help check if this is a bug or I did it wrong with `GeneralSettings.h`? Thanks!

**Comment by dingelish** [comment]
Oops. You triggered GCC internal error when compiling with openssl/libboost header files.

I've tested your config on my macbook/ubuntu but cannot trigger that bug :(

Are you using the docker image we provide? If so, try reboot your machine and start a new docker container.

**Comment by dingelish** [comment]
Update: 29e74daa9107db236d6ce411b7687010b6c055ea fixes the remote attestation IAS url

**Comment by yang-sec** [comment]
It works now. Thank you!
