### ISSUE TITLE
Could raft-rs run under sgx?

### ISSUE THREAD

**Issue by yingfeng** [apache/teaclave-sgx-sdk#43]
I notice that `raft-rs` has been included under the thirdparty components, does it mean that raft store could also work under sgx seamlessly? Thank you~

**Comment by tarcieri** [comment]
I'd also be interested in trying to figure out how to make this work

**Comment by dingelish** [comment]
@yingfeng You're right! It works!

@tarcieri Partition on demand and it should work as normal!

**Comment by yingfeng** [comment]
Thank you~
