### ISSUE TITLE
HW mode on virtual machine ?

### ISSUE THREAD

**Issue by modao1234** [apache/teaclave-sgx-sdk#449]
I'm using VMware virtual machine Ubuntu 22.04 which host cpu support SGX. Could I develop projects on hardware mode?

**Comment by andyzyb** [comment]
You'd better to check if Vmware supports SGX (means expose SGX device to guest OS).   

If so, it can work in hardware mode.

**Comment by modao1234** [comment]
> You'd better to check if Vmware supports SGX (means expose SGX device to guest OS).
> 
> If so, it can work in hardware mode.

Got it. Thank you for your reply. The virtual machine I am using support SGX I think.
