### ISSUE TITLE
无效#![feature(alloc_layout_extra)]

### ISSUE THREAD

**Issue by z1114836770** [apache/teaclave-sgx-sdk#45]
use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> src/collections/hash/table.rs:679:18
    |
679 |     let hashes = Layout::array::<HashUint>(capacity)?;
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable
我使用的是nightly，我已经在文件的头部添加#![feature(alloc_layout_extra)] 但还是报这个错误，

**Comment by dingelish** [comment]
Hi @z1114836770 ,

只指定 nightly 是不能编译 std 的——事实上 std 和编译器的版本是捆绑的。用不指明一个具体日期的 rustc nightly 编译 std 这个行为本身就是错误的。

当前的版本固定到了[nightly-2018-10-01](https://github.com/baidu/rust-sgx-sdk/blob/41c56930190f7619ebab249adc8066a39add8bb0/dockerfile/Dockerfile.1604.nightly#L73)，请使用 `rustup default nightly-2018-10-01` 来指定 nightly 版本。

**Comment by dingelish** [comment]
如果无法回滚版本，修正这个错误需要在 `sgx_tstd/src/lib.rs` 的开头加上这个 feature，而不是在 enclave 代码中加入这个 feature

**Comment by z1114836770** [comment]
好的，谢谢您。对这一块比较感兴趣，刚开始接触。多指教

**Comment by z1114836770** [comment]
两种方式我都采用了一下，都可以。但是现在有新的问题：posix_memalign’未定义的引用！ 据悉这个是linux的函数，是关于内存对齐。。。我看到在sgx_trts内有声明这个函数。对于这一块，不是肯理解。希望可以帮忙解释一下。

**Comment by dingelish** [comment]
std 依赖于 GlobalAlloc，要求对齐内存的能力。这个能力通常是通过函数`posix_memalign`提供的。这个函数在 Intel SGX 的 libsgx_tstdc.a 里没有默认编译进去。我们提供提供的 Docker image 已经做了妥善处理，强烈建议使用我们提供的 Docker image.

已经有4个issue [3](https://github.com/baidu/rust-sgx-sdk/issues/3) [14](https://github.com/baidu/rust-sgx-sdk/issues/14) [15](https://github.com/baidu/rust-sgx-sdk/issues/15) [24](https://github.com/baidu/rust-sgx-sdk/issues/24) 问过这个问题。你可以参考 [Dockerfile](https://github.com/baidu/rust-sgx-sdk/blob/master/dockerfile/Dockerfile.1604.nightly) 的61-68行重编译 intel sgx sdk 打开这个函数。

**Comment by z1114836770** [comment]
这个打补丁的方式，走到在git apply ../patch不行了。
当前没有运行在docker。

**Comment by dingelish** [comment]
@z1114836770 不会的，我们的 docker image 是按这个 dockerfile 和 patch 自动构建的。不会有问题。请按照 Dockerfile 从头配置。

**Comment by z1114836770** [comment]
我的意思是，我没有在docker内部运行。直接在本地进行操作。是否一定需要docker这个运行环境

**Comment by dingelish** [comment]
不需要

但是你要按照 Dockerfile 配置环境，从第一行开始执行。

**Comment by dingelish** [comment]
这个 patch 是绝对有效的。如果patch 失败一定是没有操作正确。

**Comment by z1114836770** [comment]
我现在从头操作了一下，在安装libsgx-enclave-common的时候出现包依赖问题。需要libcurl3he 和libprotobuf9v5。于是我准备安装这两个包，但是找不到这两个依赖包。我看到dockerfile写着ubuntu16，但我这边现在的系统是18的，是否和版本有关系

**Comment by dingelish** [comment]
那就按照dockerfile.1804这个文件进行配置即可

**Comment by dingelish** [comment]
https://github.com/baidu/rust-sgx-sdk/blob/master/dockerfile/Dockerfile.1804.nightly

**Comment by z1114836770** [comment]
@dingelish 还是在 git apply ../patch 不行。我有点疑惑就是，这块安装的插件是怎么生存的。然而我并没有这个../patch这个目录。

**Comment by z1114836770** [comment]
还有一个事情就是，如果我没有icls 没有英特尔的许可证。是否还可以利用rust-sgx，进行sgx程序的开发

**Comment by dingelish** [comment]
1. patch 在 [这里](https://github.com/baidu/rust-sgx-sdk/raw/master/dockerfile/patch)
2. icls 需要硬件支持，您确定 /dev/mei0 设备 和 /dev/isgx 设备均存在才可以用。
3. icls注册免费，但是需要向 intel 注册
4. 如果您没有 Linux 经验，不建议徒手配置环境。建议使用 docker image 内配置好的环境
5. Docker 安装[教程](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-18-04)
6. 软件模拟模式使用 rust-sgx-sdk 请参见[这里](https://github.com/baidu/rust-sgx-sdk#use-simulation-mode-for-non-sgx-enabled-machine-includes-macos)

**Comment by dingelish** [comment]
由于这个讨论对于绝大多数人都没有意义，所以暂时关闭这个 thread。您依然可以继续在这里提问，不受影响。

**Comment by z1114836770** [comment]
First, make sure Intel SGX Driver 2.3.1 is installed and functions well. /dev/isgx should appear.
找不到这个isgx文件。
这是我操作的：
zbf@Z400:~/intel_sgx$ sudo ./sgx_linux_x64_driver_4d69b9c.bin
Unpacking Intel SGX Driver ... done.
Verifying the integrity of the install package ... done.
Installing Intel SGX Driver ...
/tmp/sgx-driver-PF9HeY ~/intel_sgx
install -d /opt/intel/sgxdriver/package
install -d /opt/intel/sgxdriver/scripts
install package/* /opt/intel/sgxdriver/package
install scripts/* /opt/intel/sgxdriver/scripts
~/intel_sgx
/opt/intel/sgxdriver/package ~/intel_sgx
make -C /lib/modules/4.15.0-20-generic/build SUBDIRS=/opt/intel/sgxdriver/package modules
make[1]: 进入目录“/usr/src/linux-headers-4.15.0-20-generic”
  CC [M]  /opt/intel/sgxdriver/package/sgx_main.o
symbolmap: 00000001: invalid section
  CC [M]  /opt/intel/sgxdriver/package/sgx_page_cache.o
symbolmap: 00000001: invalid section
  CC [M]  /opt/intel/sgxdriver/package/sgx_ioctl.o
  CC [M]  /opt/intel/sgxdriver/package/sgx_vma.o
  CC [M]  /opt/intel/sgxdriver/package/sgx_util.o
  CC [M]  /opt/intel/sgxdriver/package/sgx_encl.o
  CC [M]  /opt/intel/sgxdriver/package/sgx_encl2.o
  LD [M]  /opt/intel/sgxdriver/package/isgx.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /opt/intel/sgxdriver/package/isgx.mod.o
  LD [M]  /opt/intel/sgxdriver/package/isgx.ko
make[1]: 离开目录“/usr/src/linux-headers-4.15.0-20-generic”

uninstall.sh script generated in /opt/intel/sgxdriver

Installation is successful!

**Comment by z1114836770** [comment]
这边安装驱动sgx_linux_x64_driver_4d69b9c.bin 后，找不到isgx文件。

**Comment by dingelish** [comment]
您的 CPU 不支持 SGX 功能，只想使用模拟环境的话，可以不需要`/dev/isgx`，继续安装libsgx-enclave-common即可。

**Comment by z1114836770** [comment]
docker run -v /your/path/to/rust-sgx:/root/sgx -ti baiduxlab/sgx-rust
其中 /your/path/to/rust-sgx:/root/sgx 是指哪个路径

**Comment by z1114836770** [comment]
是指rust-sgx-sdk的路径么？

**Comment by dingelish** [comment]
是

**Comment by z1114836770** [comment]
我在docker中运行，最后Succeed了。
但是有一点不是很明确。
首先，如果是采用intel的方式，那么make后，会在同级目录中出现app，然后运行app。
那么在docker用make后，在统计目录中没有这个app文件。那么怎么去运行

**Comment by z1114836770** [comment]
不好意思。看到了。是运行 bin下面的app。但好像点问题。先自己看下

**Comment by z1114836770** [comment]
在docker环境中。运行helloworld是可以正常运行的。
然而hello-rust不能正常运行。
[+] Home dir is /root
[+] Open token file success! 
[+] Token file valid!
[-] Init Enclave Failed SGX_ERROR_MODE_INCOMPATIBLE!
是不是因为该程序有涉及到文件的操作

**Comment by z1114836770** [comment]
还有一点是，我在本地打补丁的时候。
make -j
报错
make[6]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk/cpprt/linux/libunwind/src”
make[5]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk/cpprt/linux/libunwind/src”
make[5]: 进入目录“/root/linux-sgx-sgx_2.3.1/sdk/cpprt/linux/libunwind”
make[5]: 对“all-am”无需做任何事。
make[5]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk/cpprt/linux/libunwind”
make[4]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk/cpprt/linux/libunwind”
/bin/cp -f linux/libunwind/src/.libs/libunwind.a libcpprt.a
ar rs libcpprt.a linux/auxhelper.o linux/dynamic_cast.o linux/exception.o linux/gcc_personality_v0.o linux/guard.o linux/stdexcept.o linux/terminate.o linux/typeinfo.o memory_manage/delete1.o memory_manage/delete2.o memory_manage/delete3.o memory_manage/delete4.o memory_manage/delete5.o memory_manage/delete6.o memory_manage/delete7.o memory_manage/delete8.o memory_manage/new1.o memory_manage/new2.o memory_manage/new3.o memory_manage/new4.o memory_manage/new5.o memory_manage/new6.o memory_manage/new_handler.o tstdcxx_version.o
make[3]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk/cpprt”
make[2]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk”
Makefile:53: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk”
Makefile:41: recipe for target 'sdk' failed
make: *** [sdk] Error 2
这个是不是硬件不支持有关？
希望可以指点一下。谢谢

**Comment by dingelish** [comment]
不是。是因为你没有指定模拟模式编译：`SGX_MODE=SW make`。你需要 `make clean` 之后再 `SGX_MODE=SW make`

```
docker run -ti --rm -v /home/ding/rust-sgx-sdk:/sgx baiduxlab/sgx-rust
root@91ee6806d303:~# cd /sgx
root@91ee6806d303:/sgx# ls
LICENSE       common       edl          release_notes.md  sgx_rand              sgx_serialize_derive_internals  sgx_tprotected_fs  sgx_tservice   sgx_unwind   xargo
Readme.md     compiler-rt  logo.png     rustsgx.png       sgx_rand_derive       sgx_tcrypto                     sgx_trts           sgx_tstd       sgx_urts
build_helper  dockerfile   logo_25.png  samplecode        sgx_serialize         sgx_tdh                         sgx_tse            sgx_tunittest  sgx_ustdc
buildenv.mk   documents    mesalock-rt  sgx_alloc         sgx_serialize_derive  sgx_tkey_exchange               sgx_tseal          sgx_types      third_party
root@91ee6806d303:/sgx# cd samplecode/hello-rust/
root@91ee6806d303:/sgx/samplecode/hello-rust# SGX_MODE=SW make
/opt/sgxsdk/bin/x64/sgx_edger8r --trusted enclave/Enclave.edl --search-path /opt/sgxsdk/include --search-path ../../edl --trusted-dir enclave
/opt/sgxsdk/bin/x64/sgx_edger8r --untrusted enclave/Enclave.edl --search-path /opt/sgxsdk/include --search-path ../../edl --untrusted-dir app
GEN  =>  enclave/Enclave_t.c enclave/Enclave_t.h app/Enclave_u.c app/Enclave_u.h
CC   <=  enclave/Enclave_t.c
ar rcsD app/libEnclave_u.a app/Enclave_u.o
cp app/libEnclave_u.a ./lib
    Updating crates.io index
   Compiling libc v0.2.44
   Compiling sgx_types v1.0.4 (/sgx/sgx_types)
   Compiling app v1.0.0 (/sgx/samplecode/hello-rust/app)
   Compiling sgx_urts v1.0.4 (/sgx/sgx_urts)
   Compiling dirs v1.0.4
    Finished release [optimized] target(s) in 14.91s
Cargo  =>  bin/app
cp ./app/target/release/app ./bin
make -C ./enclave/
make[1]: Entering directory '/sgx/samplecode/hello-rust/enclave'
cargo build --release
   Compiling sgx_build_helper v0.1.0 (/sgx/build_helper)
   Compiling sgx_unwind v0.0.1 (/sgx/sgx_unwind)
   Compiling sgx_types v1.0.4 (/sgx/sgx_types)
   Compiling sgx_trts v1.0.4 (/sgx/sgx_trts)
   Compiling sgx_tstd v1.0.4 (/sgx/sgx_tstd)
   Compiling sgx_tprotected_fs v1.0.4 (/sgx/sgx_tprotected_fs)
   Compiling sgx_alloc v1.0.4 (/sgx/sgx_alloc)
   Compiling Helloworldsampleenclave v1.0.0 (/sgx/samplecode/hello-rust/enclave)
    Finished release [optimized] target(s) in 3.43s
cp ./target/release/libhelloworldsampleenclave.a ../lib/libenclave.a
make[1]: Leaving directory '/sgx/samplecode/hello-rust/enclave'
make -C ../../compiler-rt/ 2> /dev/null
make[1]: Entering directory '/sgx/compiler-rt'
cc -c -Wjump-misses-init -Wstrict-prototypes -Wunsuffixed-float-constants -fstack-protector -O2   -UDEBUG -DNDEBUG -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -ffreestanding -nostdinc -fvisibility=hidden -fpie -O2  -I../common/inc/ muloti4.c -o muloti4.o
ar rcsD libcompiler-rt-patch.a muloti4.o
make[1]: Leaving directory '/sgx/compiler-rt'
CC   <=  enclave/Enclave_t.c
cp ../../compiler-rt/libcompiler-rt-patch.a ./lib
LINK =>  enclave/enclave.so
<!-- Please refer to User's Guide for the explanation of each field -->
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 1675264B.
Succeed.
SIGN =>  bin/enclave.signed.so
root@91ee6806d303:/sgx/samplecode/hello-rust# cd bin/
root@91ee6806d303:/sgx/samplecode/hello-rust/bin# ./app
[+] Home dir is /root
[-] Open token file /root/enclave.token error! Will create one.
[+] Saved updated launch token!
[+] Init Enclave Successful 2542620639234!
This is a normal world string passed into Enclave!
This is a in-Enclave Rust string!
[+] say_something success...
```

**Comment by dingelish** [comment]
> 还有一点是，我在本地打补丁的时候。
> make -j
> 报错
> make[6]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk/cpprt/linux/libunwind/src”
> make[5]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk/cpprt/linux/libunwind/src”
> make[5]: 进入目录“/root/linux-sgx-sgx_2.3.1/sdk/cpprt/linux/libunwind”
> make[5]: 对“all-am”无需做任何事。
> make[5]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk/cpprt/linux/libunwind”
> make[4]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk/cpprt/linux/libunwind”
> /bin/cp -f linux/libunwind/src/.libs/libunwind.a libcpprt.a
> ar rs libcpprt.a linux/auxhelper.o linux/dynamic_cast.o linux/exception.o linux/gcc_personality_v0.o linux/guard.o linux/stdexcept.o linux/terminate.o linux/typeinfo.o memory_manage/delete1.o memory_manage/delete2.o memory_manage/delete3.o memory_manage/delete4.o memory_manage/delete5.o memory_manage/delete6.o memory_manage/delete7.o memory_manage/delete8.o memory_manage/new1.o memory_manage/new2.o memory_manage/new3.o memory_manage/new4.o memory_manage/new5.o memory_manage/new6.o memory_manage/new_handler.o tstdcxx_version.o
> make[3]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk/cpprt”
> make[2]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk”
> Makefile:53: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: 离开目录“/root/linux-sgx-sgx_2.3.1/sdk”
> Makefile:41: recipe for target 'sdk' failed
> make: *** [sdk] Error 2
> 这个是不是硬件不支持有关？
> 希望可以指点一下。谢谢

无关，你所给的信息不足以判断错误。这个是 Intel SGX SDK 的编译问题，请依照 [Dockerfile](https://github.com/baidu/rust-sgx-sdk/blob/41c56930190f7619ebab249adc8066a39add8bb0/dockerfile/Dockerfile.1804.nightly#L37)自行检查依赖项有没有全部安装。

**Comment by z1114836770** [comment]
好的。谢谢
1、我在Makefile内设置了SGX_MODE=SW, 和显示的使用SGX_MODE=SW make有什么区别么？
2、我仔细看了下本地make -j的结果发现是少了一个库，我重新安装了它，并吧libsgx_urts_sim.so复制到安装sgxsdk的目录中去了。但是显示出现了另一个问题：error while loading shared libraries: libsgx_urts_sim.so: cannot open shared object file: No such file or directory
通过查询资料说吧 安装libsgx_urts_sim.so的目录放入到 /etc/ld.so.conf中，也尝试过在ld.so.conf.d添加一个文件指引到libsgx_urts_sim.so，并且也试过source environment。但是还是不行，是不是我哪个环节出现了问题？

**Comment by dingelish** [comment]
1. 应该没有区别
2. 这就是我说的 不建议没有 linux 经验的人自己手动搭建环境。如果你是一步一步按照Dockerfile设置下来，先装驱动，再装libsgx-enclave-common，再编译sgxsdk，再替换libsgx_tlibc.a，那就一定没有任何问题。现在我并不知道你的环境出了什么问题，你所查看的资料完全就是错的，环境改来改去我也没办法帮你……再次建议你使用 Docker。

**Comment by z1114836770** [comment]
不搞出来很有点难受。不好意思了。
仔细看了一下发现libxml2-dev没有这个库，libprotobuf-c0-dev应该是libprotobuf-c-dev。

**Comment by dingelish** [comment]
如果您用的是 ubuntu 18.04，那么这libxml2-dev库是存在于官方源的：

https://packages.ubuntu.com/bionic/libxml2-dev

libprotobuf-c0-dev会自动转到libprotobuf-c-dev

**Comment by dingelish** [comment]
您在编译 Intel SGX SDK 时遇到的困难请到 Intel SGX SDK 的社区进行提问。本项目恕不解答 Intel 库相关的问题，抱歉。

**Comment by z1114836770** [comment]
好的。谢谢。
在dockerfile内ENV DEBIAN_FRONTEND=noninteractive，是指在/etc/profile内添加环境export DEBIAN_FRONTEND=noninteractive 的意思么？

**Comment by dingelish** [comment]
该环境变量只作用在 `docker build` 过程中。请您阅读 [Dockerfile](https://docs.docker.com/engine/reference/builder/) 语法。

**Comment by z1114836770** [comment]
@dingelish 谢谢你了。现在已经能在本地运行rust-sgx-sdk的例子。谢谢。
但是我把rustc安装在root下面了，有点措手不及。现在准备在安装一边rust

**Comment by z1114836770** [comment]
我还想了解几个问题：
1、到目前为止，我是不是以及可以利用rust-sgx-sdk进行操作，如调用库和写入操作？
     （因为我听说需要一个许可，才能进行调用库等操作，我不是很明确）
2、iclsClient 这个具体干什么用的？

**Comment by dingelish** [comment]
1. 如果您对 Intel SGX 技术有任何问题，请查看 Intel SGX 相关的技术文档。只要是 Intel SGX 支持的，rust-sgx-sdk 都支持。本项目不负责解答 Intel SGX 的问题。
2. 请查阅  Intel Capability Licensing Service 相关文档。

如果您不熟悉 Intel SGX，建议您阅读两份入门材料：
[1] Intel SGX Explained, https://eprint.iacr.org/2016/086.pdf
[2] Platform Embedded Security Technology Revealed, https://link.springer.com/book/10.1007/978-1-4302-6572-6

**Comment by z1114836770** [comment]
我用普通用户
make可以成功～
运行bin内的app的时候报错
[+] Home dir is /home/zbf
[+] Open token file success! 
[+] Token file valid!
Please use the correct uRTS library from PSW package.
[-] Init Enclave Failed SGX_ERROR_UNEXPECTED!

使用root是可以的

**Comment by dingelish** [comment]
这是 Intel SGX 环境的配置问题，本项目恕不提供支持。一切关于 Intel SGX 环境相关的问题请到 Intel SGX 产品论坛寻求技术支持。

https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx

**Comment by z1114836770** [comment]
奥。好的，谢谢。
还有两点我想了解一下。
1、rust-sgx-sdk是基于intel sgx之上。还是重新实现的？
2、当采用intel sgx 进行 SGX_MODE=HW make时需要提供许可证。那么采用rust-sgx-sdk进行HW时，是否也需要许可证？

**Comment by dingelish** [comment]
1.  建于 Intel SGX SDK 之上
2. 都不需要。关于 Intel SGX 的技术请移步 Intel SGX 产品论坛。
