### ISSUE TITLE
V2.0.0-perview supports Intel Linux SGX SDK 2.21 or later

### ISSUE THREAD

**Issue by yangfh2004** [apache/teaclave-sgx-sdk#454]
The V2.0.0 preview only supports Intel's SGX SDK 2.17.1, which does not support Ubuntu 22.04. We are looking forward to supporting newer versions of Intel's SGX SDK so that we have supports to the latest kernel, tool chains and DCAP drivers.

We are experimenting with the support on version 2.21 on [our fork](https://gitlab.com/dexlabs/incubator-teaclave-sgx-sdk/-/tree/v2.0.0-preview-sdk-2.21?ref_type=heads) 

The `helloworld` demo compiled OK but have issues with a segmentation fault on TCS initiation while it creates and `memset` a new piece of memory inside the enclave for a new TCS. We haven't digged into the root cause but it seems that there might be some difference in memory management in the newer version.

The same segmentation fault happens in all modes, including HW and SIM with or without optimization libraries.
Since the `memset` function is provided by Intel, I don't believe the root cause is the fast or regular `memset`.

<img width="1275" alt="Screenshot 2024-02-13 at 5 47 50 PM" src="https://github.com/apache/incubator-teaclave-sgx-sdk/assets/20646825/1830859e-4164-4154-b1de-421fbf36ff99">
Where it crashes in the SIM mode, it will also crash in the HW mode at the same line of code.
<img width="623" alt="Screenshot 2024-02-14 at 5 23 29 PM" src="https://github.com/apache/incubator-teaclave-sgx-sdk/assets/20646825/b370ccc5-3854-4862-8958-730c38ecdc7a">
Where it crashes the enclave with regular `memset`
<img width="1330" alt="Screenshot 2024-02-15 at 10 38 27 AM" src="https://github.com/apache/incubator-teaclave-sgx-sdk/assets/20646825/f17c98e5-cc0b-4f10-9077-ed1abaef4a15">
Where it crashes the enclave with fast `memset`

**Comment by yangfh2004** [comment]
@volcano0dr please take a look at our fork branch and your suggestions are welcome, thanks.

**Comment by yangfh2004** [comment]
I see the `typedef struct _thread_data_t` has changes and would result different mapping in into the rust struct, which I believe might be the root cause of the problem.

**Comment by yangfh2004** [comment]
I fixed it by updating the `Tds` struct in the global data

**Comment by yangfh2004** [comment]
Still have some problems with heap allocation since the EDMM is missing. Please review our fork and leave comments so that we can improve, thanks!

**Comment by ClawSeven** [comment]
Hi, @yangfh2004, you could update the intel sgx sdk version with [this script](https://download.01.org/intel-sgx/sgx-linux/2.21/distro/ubuntu20.04-server/sgx_linux_x64_sdk_2.21.100.1.bin).
