### ISSUE TITLE
off_t should be signed

### ISSUE THREAD

**Issue by tatetian** [apache/teaclave-sgx-sdk#46]
Hi there,

The Rust type `off_t`, which is defined as `u64` in `sgx_trts/src/libc.rs` and `sgx_tstd/src/os/raw.rs`, are meant to represent the C definition of `off_t` defined in libc, right? But, in libc, `off_t` is actually signed. The reason that `off_t` has to be signed is that you want to be able to `lseek` backward relative to the current position (`SEEK_CUR`), in which case the offset value is negative. So, the Rust type `off_t` should be `i64`; so is `off64_t`.

Best,
Tate

**Comment by dingelish** [comment]
@tatetian 
Thank you very much! I think you're right. I'm testing with your fix and will fix it on Github asap!

**Comment by dingelish** [comment]
@tatetian 
Fixed in 4d999470c8c12a6e6f70d302c09114957114bb05 Thanks again for your contribution!

**Comment by tatetian** [comment]
Thanks. The fix seems good to me :thumbsup:
