### ISSUE TITLE
Upgrade to Intel SGX Linux 2.4 Release

### ISSUE THREAD

**Issue by tomtau** [apache/teaclave-sgx-sdk#48]
https://01.org/node/29957

**Comment by dingelish** [comment]
Hi @tomtau ,

I'm busy working with this but encountered a lot of problems. For example, v2.4 has some [bugs](https://github.com/intel/linux-sgx/pull/359) and I just filed PR and waiting for response. And I have a pending [PR](https://github.com/rust-lang/rust/pull/57243) at Rust to fix xargo build failure in most recent Rust nightly ([issue here](https://github.com/rust-lang/rust/issues/57231)).

Here are a minimal solution for v2.4:
1. Install the 2.4 suite, and patch libsgx_tstdc.a as usual.
2. Use patch from this [PR](https://github.com/intel/linux-sgx/pull/359) to generate a new aesm_service binary and copy it to /opt/intel/libsgx-enclave-common/aesm/aesm_service to overwrite.
3. Stay on nightly-2018-10-01. Do not upgrade to most recent nightly. ([issue here](https://github.com/rust-lang/rust/issues/57231)).
4. When linking with trts, e.g. `-l$(Trts_Library_Name)`, add another link flag to libsgx_tservice.a. For example, the new linking flag may be `-l$(Trts_Library_Name) -l$(Service_Library_Name)`.

Plan:
After Intel fixes`sgx_report_attestation_status`, and the patch to Rust merged, I'll release next version asap!

Best,
Yu

**Comment by dingelish** [comment]
Update: [PR](https://github.com/rust-lang/rust/pull/57243) to Rust has been merged.

Still waiting for Intel's response.

**Comment by dingelish** [comment]
Update: found another linking problem when linking with libsgx_tstdc.a, about multiple definition of `memcpy`, `memcmp` and `memset`. The collision roots from Fortanix's recent commits and I've submitted a [PR](https://github.com/rust-lang-nursery/compiler-builtins/pull/269) to fix. Waiting for Rust team's response.

**Comment by dingelish** [comment]
Update: the patch to compiler-builtins has been [merged](https://github.com/rust-lang-nursery/compiler-builtins/pull/269) and compiler-builtins is upgraded to [v1.0.4](https://github.com/rust-lang-nursery/compiler-builtins/commit/0c5dffb5ba791251ae6d2a92d4491d444a5c45b2). On the Rust side, the dependency of compiler-builtins is maintained in Cargo.lock and the upgrade of compiler-builtin is [approved](https://github.com/rust-lang/rust/pull/57327) and pending for merge.

**Comment by dingelish** [comment]
Update: all existing PRs to Rust has been merged and nightly-2019-01-09 works well on my unreleased version. Intel confirms that the problem of report checking is a bug, but the fix is being tested and has not been merged. So now I have two choices:

(1) wait until 2.4.1 and skip 2.4
(2) release with 2.4 support and add my own aesm patch. after the release of 2.4.1, upgrade to 2.4.1

Which one do you guys prefer?

**Comment by tomtau** [comment]
Probably wait for 2.4.1?

**Comment by elichai** [comment]
Yeah I'll say wait for 2.4.1,
Anyway each upgrade requires a lot of work on our sides too (I'll guess anyone who's using this have their own forks of stuff)
And I'll want to also try and see if using your version from crates.io works for us :)

**Comment by dingelish** [comment]
@tomtau @elichai 
Seems that we'd better wait for 2.4.1 according to the security advisory
https://www.intel.com/content/www/us/en/security-center/advisory/INTEL-SA-00203.html

**Comment by elichai** [comment]
BTW, do you know if there's some mailing list or subscription that I can get notified for these vulnerabilities?

**Comment by tarcieri** [comment]
@elichai you should receive them if you're enrolled in the SGX Program (which you'll need to be in order to sign production enclaves)

**Comment by elichai** [comment]
@tarcieri I am enrolled, but all I get from them is some spam on compute vision lol

**Comment by elichai** [comment]
@dingelish Is there a way to know when 2.4.1 will be released? if not It might be better to use a patch because a couple of changes with unstable features getting stable (specifically const_fn) makes using some libraries a bit more difficult
(Or maybe you can release an update just to the compiler and dockers and wait for 2.4.1 for updating the sdk?)

**Comment by dingelish** [comment]
@elichai Yesterday I asked Intel the same question and they answered that the current 2.4 is exactly 2.4.100. There is no 2.4.1. It seems that the current 2.4 has already patched IPP bug (but not the sig verification bug which is fixed later).

I can provide a branch to support recent Rust nightly today. And I'll need another few days for documentation and rust-stable branch. Is this ok for you? I think the next v1.0.5 could be ready next week.

**Comment by elichai** [comment]
Sounds great.
It will probably take me a day or too to update all my stuff to support the latest nightly too, (I'll start working on that once you release the updates to the sgx-* libraries)
Thanks!

**Comment by dingelish** [comment]
@elichai @tomtau 
New [branch](https://github.com/baidu/rust-sgx-sdk/tree/v1.0.5-preview) pushed. Updated the readme a little. No more documentation for now.
