### ISSUE TITLE
which rust version is correct ? i compile the sample code have so many errors!!!!!!

### ISSUE THREAD

**Issue by followinds** [apache/teaclave-sgx-sdk#49]
hello-rust ,there have some rust's feature was removed,please tell which rust version is correct,thanks:

cargo build --release
   Compiling sgx_tstd v1.0.4 (/home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd)
error[E0557]: feature has been removed
  --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/lib.rs:97:12
   |
97 | #![feature(panic_implementation)]
   |            ^^^^^^^^^^^^^^^^^^^^
   |
note: subsumed by `#[panic_handler]`
  --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/lib.rs:97:12
   |
97 | #![feature(panic_implementation)]
   |            ^^^^^^^^^^^^^^^^^^^^

warning: lint `private_no_mangle_fns` has been removed: `no longer a warning, #[no_mangle] functions always exported`
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/panicking.rs:442:9
    |
442 | #[allow(private_no_mangle_fns)] // yes we get it, but we like breakpoints
    |         ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(renamed_and_removed_lints)] on by default

error[E0658]: use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/collections/hash/table.rs:676:18
    |
676 |     let hashes = Layout::array::<HashUint>(capacity)?;
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/collections/hash/table.rs:677:17
    |
677 |     let pairs = Layout::array::<(K, V)>(capacity)?;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/collections/hash/table.rs:678:12
    |
678 |     hashes.extend(pairs).map(|(layout, _)| {
    |            ^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/collections/hash/table.rs:686:36
    |
686 |             hashes.size() + hashes.padding_needed_for(mem::align_of::<(K, V)>()),
    |                                    ^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable

error: aborting due to 5 previous errors

Some errors occurred: E0557, E0658.
For more information about an error, try `rustc --explain E0557`.
error: Could not compile `sgx_tstd`.

To learn more, run the command again with --verbose.
Makefile:42: recipe for target 'libenclave.a' failed
make[1]: *** [libenclave.a] Error 101
make[1]: Leaving directory '/home/chen/file/rust-sgx/rust-sgx-sdk/samplecode/hello-rust/enclave'
Makefile:162: recipe for target 'enclave' failed
make: *** [enclave] Error 2

**Comment by dingelish** [comment]
Hi there,

The first line of v1.0.4 release says:
This version supports Rust nightly build (nightly-2018-10-01) in the master branch and the most recent stable build (stable-2018-09-25) in the rust-stable branch.

You can run `rustup default nightly-2018-10-01` to install the correct version of Rust.
