### ISSUE TITLE
does the version of v1.0.4 can support ubuntu16.04?

### ISSUE THREAD

**Issue by followinds** [apache/teaclave-sgx-sdk#50]
when i compile the hello-rust,i met this error:
 

  Compiling Helloworldsampleenclave v1.0.0 (/home/chen/file/rust-sgx/rust-sgx-sdk/samplecode/helloworld/enclave)
    Finished release [optimized] target(s) in 4.38s                             
cp ./target/release/libhelloworldsampleenclave.a ../lib/libenclave.a
make[1]: Leaving directory '/home/chen/file/rust-sgx/rust-sgx-sdk/samplecode/helloworld/enclave'

make -C ../../compiler-rt/ 2> /dev/null
make[1]: Entering directory '/home/chen/file/rust-sgx/rust-sgx-sdk/compiler-rt'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/chen/file/rust-sgx/rust-sgx-sdk/compiler-rt'
CC   <=  enclave/Enclave_t.c
cp ../../compiler-rt/libcompiler-rt-patch.a ./lib
./lib/libenclave.a(sgx_tstd-0b33fc6301c1ccb7.sgx_tstd.bifjyx31-cgu.5.rcgu.o)：在函数‘__rg_alloc’中：
sgx_tstd.bifjyx31-cgu.5:(.text.__rg_alloc+0x26)：对‘posix_memalign’未定义的引用
./lib/libenclave.a(sgx_alloc-76add1030b1b18c0.sgx_alloc.7a64x7l3-cgu.0.rcgu.o)：在函数‘sgx_alloc::realloc_fallback::_$LT$impl$u20$sgx_alloc..System$GT$::realloc_fallback::h96602220191637e6’中：
sgx_alloc.7a64x7l3-cgu.0:(.text._ZN9sgx_alloc16realloc_fallback35_$LT$impl$u20$sgx_alloc..System$GT$16realloc_fallback17h96602220191637e6E+0x40)：对‘posix_memalign’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:166: recipe for target 'enclave/enclave.so' failed
make: *** [enclave/enclave.so] Error 1

rust version:rustc 1.31.0-nightly (fc403ad98 2018-09-30)
os:ubuntu16.04
sgx-sdk:2.3.1
rust-sgx-sdk:1.0.4

**Comment by dingelish** [comment]
It supports Ubuntu 16.04.

Please read the Readme carefully. It seems that you're trying to build your own environment without using pre-configure docker image. In your case, [this line](https://github.com/baidu/rust-sgx-sdk#native-without-docker-not-recommended) of Readme would guide you to the [Dockerfile](https://github.com/baidu/rust-sgx-sdk/blob/master/dockerfile/Dockerfile.1604.nightly). Please set up the environment as claimed in Dockerfile and get libsgx_tstdc.a patched.

As a careful reminder, please search the keyword of your question in this repository before submitting a new issue. If you search 'posix_memalign' in this repo, github would give you five resolved issues (#3 #14 #15 #24 #45) where you could find the aforementioned solution.

**Comment by followinds** [comment]
@dingelish 
thanks, i ran the hello-world project well by your suggestions,but i run the hello-rust project met new errors:




error[E0557]: feature has been removed
  --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/lib.rs:97:12
   |
97 | #![feature(panic_implementation)]
   |            ^^^^^^^^^^^^^^^^^^^^
   |
note: subsumed by `#[panic_handler]`
  --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/lib.rs:97:12
   |
97 | #![feature(panic_implementation)]
   |            ^^^^^^^^^^^^^^^^^^^^

warning: lint `private_no_mangle_fns` has been removed: `no longer a warning, #[no_mangle] functions always exported`
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/panicking.rs:442:9
    |
442 | #[allow(private_no_mangle_fns)] // yes we get it, but we like breakpoints
    |         ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(renamed_and_removed_lints)] on by default

error[E0658]: use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/collections/hash/table.rs:676:18
    |
676 |     let hashes = Layout::array::<HashUint>(capacity)?;
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/collections/hash/table.rs:677:17
    |
677 |     let pairs = Layout::array::<(K, V)>(capacity)?;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/collections/hash/table.rs:678:12
    |
678 |     hashes.extend(pairs).map(|(layout, _)| {
    |            ^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/collections/hash/table.rs:686:36
    |
686 |             hashes.size() + hashes.padding_needed_for(mem::align_of::<(K, V)>()),
    |                                    ^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable

error: aborting due to 5 previous errors

Some errors occurred: E0557, E0658.
For more information about an error, try `rustc --explain E0557`.
error: Could not compile `sgx_tstd`.




I have used this command to set toolchain:
rustup default nightly-2018-10-01
maybe this version is incorrect?

**Comment by dingelish** [comment]
Hi @FolloWinds ,

I'm pretty sure the version is correct. And I cannot reproduce your bug. Here is my log:

```
root@c758337c9adb:~/sgx/samplecode/hello-rust# make
/opt/sgxsdk/bin/x64/sgx_edger8r --trusted enclave/Enclave.edl --search-path /opt/sgxsdk/include --search-path ../../edl --trusted-dir enclave
/opt/sgxsdk/bin/x64/sgx_edger8r --untrusted enclave/Enclave.edl --search-path /opt/sgxsdk/include --search-path ../../edl --untrusted-dir app
GEN  =>  enclave/Enclave_t.c enclave/Enclave_t.h app/Enclave_u.c app/Enclave_u.h
CC   <=  enclave/Enclave_t.c
ar rcsD app/libEnclave_u.a app/Enclave_u.o
cp app/libEnclave_u.a ./lib
    Updating crates.io index
   Compiling libc v0.2.46
   Compiling sgx_types v1.0.4 (/root/sgx/sgx_types)
   Compiling app v1.0.0 (/root/sgx/samplecode/hello-rust/app)
   Compiling dirs v1.0.4
   Compiling sgx_urts v1.0.4 (/root/sgx/sgx_urts)
    Finished release [optimized] target(s) in 16.81s
Cargo  =>  bin/app
cp ./app/target/release/app ./bin
make -C ./enclave/
make[1]: Entering directory '/root/sgx/samplecode/hello-rust/enclave'
cargo build --release
   Compiling sgx_types v1.0.4 (/root/sgx/sgx_types)
   Compiling sgx_unwind v0.0.1 (/root/sgx/sgx_unwind)
   Compiling sgx_build_helper v0.1.0 (/root/sgx/build_helper)
   Compiling sgx_trts v1.0.4 (/root/sgx/sgx_trts)
   Compiling sgx_tstd v1.0.4 (/root/sgx/sgx_tstd)
   Compiling sgx_tprotected_fs v1.0.4 (/root/sgx/sgx_tprotected_fs)
   Compiling sgx_alloc v1.0.4 (/root/sgx/sgx_alloc)
   Compiling Helloworldsampleenclave v1.0.0 (/root/sgx/samplecode/hello-rust/enclave)
    Finished release [optimized] target(s) in 3.34s
cp ./target/release/libhelloworldsampleenclave.a ../lib/libenclave.a
make[1]: Leaving directory '/root/sgx/samplecode/hello-rust/enclave'
make -C ../../compiler-rt/ 2> /dev/null
make[1]: Entering directory '/root/sgx/compiler-rt'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/root/sgx/compiler-rt'
CC   <=  enclave/Enclave_t.c
cp ../../compiler-rt/libcompiler-rt-patch.a ./lib
LINK =>  enclave/enclave.so
<!-- Please refer to User's Guide for the explanation of each field -->
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>1</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 1, tcs_max_num 1, tcs_min_pool 1
The required memory is 1662976B.
Succeed.
SIGN =>  bin/enclave.signed.so
root@c758337c9adb:~/sgx/samplecode/hello-rust# rustup toolchain list
nightly-2018-10-01-x86_64-unknown-linux-gnu (default)
```

**Comment by dingelish** [comment]
What's your output of `which rustc`? Mine is

```
root@c758337c9adb:~/sgx/samplecode/hello-rust# which rustc
/root/.cargo/bin/rustc
```

**Comment by followinds** [comment]
this is my output:

root@chen:~/linux-sgx-sgx_2.3.1/build/linux# which rustc
/root/.cargo/bin/rustc
root@chen:~/linux-sgx-sgx_2.3.1/build/linux# rustup toolchain list
stable-2018-09-25-x86_64-unknown-linux-gnu
stable-x86_64-unknown-linux-gnu
beta-x86_64-unknown-linux-gnu
nightly-2018-07-16-x86_64-unknown-linux-gnu
nightly-2018-10-01-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
root@chen:~/linux-sgx-sgx_2.3.1/build/linux# rustc --version
rustc 1.31.0-nightly (fc403ad98 2018-09-30)

**Comment by followinds** [comment]
/home/chen/application/sgxsdk/bin/x64/sgx_edger8r --trusted enclave/Enclave.edl --search-path /home/chen/application/sgxsdk/include --search-path ../../edl --trusted-dir enclave
/home/chen/application/sgxsdk/bin/x64/sgx_edger8r --untrusted enclave/Enclave.edl --search-path /home/chen/application/sgxsdk/include --search-path ../../edl --untrusted-dir app
GEN  =>  enclave/Enclave_t.c enclave/Enclave_t.h app/Enclave_u.c app/Enclave_u.h
CC   <=  enclave/Enclave_t.c
ar rcsD app/libEnclave_u.a app/Enclave_u.o
cp app/libEnclave_u.a ./lib
    Updating crates.io index
   Compiling libc v0.2.46
   Compiling app v1.0.0 (/home/chen/file/rust-sgx/rust-sgx-sdk/samplecode/hello-rust/app)
   Compiling sgx_types v1.0.4 (/home/chen/file/rust-sgx/rust-sgx-sdk/sgx_types)
warning: the feature `tool_lints` has been stable since 1.31.0 and no longer requires an attribute to enable
  --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_types/src/lib.rs:30:12
   |
30 | #![feature(tool_lints)]
   |            ^^^^^^^^^^
   |
   = note: #[warn(stable_features)] on by default

   Compiling sgx_urts v1.0.4 (/home/chen/file/rust-sgx/rust-sgx-sdk/sgx_urts)
   Compiling dirs v1.0.4
warning: the feature `tool_lints` has been stable since 1.31.0 and no longer requires an attribute to enable
  --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_urts/src/lib.rs:29:12
   |
29 | #![feature(tool_lints)]
   |            ^^^^^^^^^^
   |
   = note: #[warn(stable_features)] on by default

    Finished release [optimized] target(s) in 2.40s
Cargo  =>  bin/app
cp ./app/target/release/app ./bin
make -C ./enclave/
make[1]: Entering directory '/home/chen/file/rust-sgx/rust-sgx-sdk/samplecode/hello-rust/enclave'
cargo build --release
   Compiling sgx_build_helper v0.1.0 (/home/chen/file/rust-sgx/rust-sgx-sdk/build_helper)
   Compiling sgx_types v1.0.4 (/home/chen/file/rust-sgx/rust-sgx-sdk/sgx_types)
   Compiling sgx_unwind v0.0.1 (/home/chen/file/rust-sgx/rust-sgx-sdk/sgx_unwind)
warning: the feature `tool_lints` has been stable since 1.31.0 and no longer requires an attribute to enable
  --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_types/src/lib.rs:30:12
   |
30 | #![feature(tool_lints)]
   |            ^^^^^^^^^^
   |
   = note: #[warn(stable_features)] on by default

   Compiling sgx_trts v1.0.4 (/home/chen/file/rust-sgx/rust-sgx-sdk/sgx_trts)
   Compiling sgx_tstd v1.0.4 (/home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd)
warning: the feature `tool_lints` has been stable since 1.31.0 and no longer requires an attribute to enable
  --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_trts/src/lib.rs:82:12
   |
82 | #![feature(tool_lints)]
   |            ^^^^^^^^^^
   |
   = note: #[warn(stable_features)] on by default

   Compiling sgx_tprotected_fs v1.0.4 (/home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tprotected_fs)
   Compiling sgx_alloc v1.0.4 (/home/chen/file/rust-sgx/rust-sgx-sdk/sgx_alloc)
warning: lint `private_no_mangle_fns` has been removed: `no longer a warning, #[no_mangle] functions always exported`
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/panicking.rs:442:9
    |
442 | #[allow(private_no_mangle_fns)] // yes we get it, but we like breakpoints
    |         ^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(renamed_and_removed_lints)] on by default

error[E0658]: use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/collections/hash/table.rs:676:18
    |
676 |     let hashes = Layout::array::<HashUint>(capacity)?;
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/collections/hash/table.rs:677:17
    |
677 |     let pairs = Layout::array::<(K, V)>(capacity)?;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/collections/hash/table.rs:678:12
    |
678 |     hashes.extend(pairs).map(|(layout, _)| {
    |            ^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'alloc_layout_extra' (see issue #55724)
   --> /home/chen/file/rust-sgx/rust-sgx-sdk/sgx_tstd/src/collections/hash/table.rs:686:36
    |
686 |             hashes.size() + hashes.padding_needed_for(mem::align_of::<(K, V)>()),
    |                                    ^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(alloc_layout_extra)] to the crate attributes to enable

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `sgx_tstd`.

To learn more, run the command again with --verbose.
Makefile:42: recipe for target 'libenclave.a' failed
make[1]: *** [libenclave.a] Error 101
make[1]: Leaving directory '/home/chen/file/rust-sgx/rust-sgx-sdk/samplecode/hello-rust/enclave'
Makefile:162: recipe for target 'enclave' failed
make: *** [enclave] Error 2

**Comment by dingelish** [comment]
That's weird. What's your output of `which cargo`? Mine is
```
root@c758337c9adb:~/sgx/samplecode/hello-rust# which cargo
/root/.cargo/bin/cargo
```

**Comment by followinds** [comment]
root@chen:/home/chen/file/rust-sgx/rust-sgx-sdk/samplecode/hello-rust# which cargo
/root/.cargo/bin/cargo

mine is the sam as yours.

**Comment by dingelish** [comment]
No idea what's going on. But I'm pretty sure the rustc used during compilation is not `/root/.cargo/bin/rustc`.

I just re-installed the toolchain nightly-2018-10-01 and it works fine.

So I recommend using the docker image. That's the easiest way. Docker is very easy to install and use.

**Comment by followinds** [comment]
root@chen:/home/chen/file/rust-sgx/rust-sgx-sdk/samplecode/hello-rust# rustup toolchain list
nightly-2018-10-01-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
root@chen:/home/chen/file/rust-sgx/rust-sgx-sdk/samplecode/hello-rust# rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

nightly-2018-10-01-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (directory override for '/home/chen/file/rust-sgx/rust-sgx-sdk/samplecode/hello-rust')
rustc 1.33.0-nightly (b92552d55 2019-01-06)




i removed other toolchain ,but nightly-x86_64-unknown-linux-gnu will download automatically. and the active toolchain is not the defalut

**Comment by followinds** [comment]
Ok,i'll try it again.thanks.
