### ISSUE TITLE
when i test the ra project,met curl_easy_perform() failed: Problem with the local SSL certificate

### ISSUE THREAD

**Issue by xiaoshui1994** [apache/teaclave-sgx-sdk#51]
SampleCode/remoteattestation

SP output:
1546845758 INFO  : Curl initialized successfully
1546845758 INFO  : Start connecting...
1546845758 INFO  : Connection established
1546845758 INFO  : Verifying certificate: /C=AU/ST=SICHUAN/L=CHENGDU/O=GANG/OU=GANG/CN=GANG/emailAddress=975868484@qq.com
1546845758 INFO  : Handshake successful
1546845758 INFO  : Prepare Verification request
1546845758 INFO  : Serialization successful
1546845758 INFO  : MSG0 received
1546845758 INFO  : Received extended EPID group ID: 0
1546845758 INFO  : Serialization successful
1546845758 INFO  : Send to client
1546845758 INFO  : MSG1 received
1546845758 INFO  : Retrieving SigRL from IAS
1546845758 INFO  : sending url: https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v3/sigrl/000013dc
1546845760 INFO  : Curl cert file: /home/chen/tes/AttestationReportSigningCACert.pem
**_1546845760 INFO  : curl_easy_perform() failed: Problem with the local SSL certificate_**
**1546845760 INFO  : 	Response status is: 0
1546845760 INFO  : 	Content-Length: 0
1546845760 INFO  : Error, processing MSG1 failed**
1546845760 INFO  : Send to client
1546845760 INFO  : Remote attestation done

app output:
1546845750 INFO  : Certificate "/home/chen/tes/client.txt" set
1546845750 INFO  : Server running on port: 22222
1546845758 INFO  : New accept request, starting new session
1546845758 INFO  : Connection from 127.0.0.1
1546845758 INFO  : Handshake successful
1546845758 INFO  : Verification request received
1546845758 INFO  : Call MSG0 generate
1546845758 INFO  : Call sgx_get_extended_epid_group_id success
1546845758 INFO  : Serialization successful
1546845758 INFO  : Send to client
1546845758 INFO  : MSG0 response received
1546845758 INFO  : Call sgx_create_enclave success
1546845758 INFO  : Enclave created, ID: 2
1546845758 INFO  : Call enclave_init_ra success
1546845758 INFO  : Sending msg1 to remote attestation service provider. Expecting msg2 back
1546845758 INFO  : MSG1 generated Successfully
1546845758 INFO  : Serialization successful
1546845758 INFO  : Send to client
1546845760 ERROR  : Unknown socket error while reading occured!

@dingelish   thanks,my friend.
i use these certificate to run the offical ra example(sgx-ra-example) is well, but there is no use.

**Comment by dingelish** [comment]
It seems your certificate is not working.

You are using Intel's report signing key to connect IAS. This is wrong. You should use your client cert/key suite to connect to IAS.

Can you try this example instead?

https://github.com/baidu/rust-sgx-sdk/tree/master/samplecode/mutual-ra

Pay attention to the readme. Test the crt/key before start.

**Comment by dingelish** [comment]
If your registration is finished with unlinkable policy, change [this line](https://github.com/baidu/rust-sgx-sdk/blob/4d999470c8c12a6e6f70d302c09114957114bb05/samplecode/mutual-ra/enclave/src/lib.rs#L402) to unlinkable.

**Comment by dingelish** [comment]
> SampleCode/remoteattestation
> 
> SP output:
> 1546845758 INFO : Curl initialized successfully
> 1546845758 INFO : Start connecting...
> 1546845758 INFO : Connection established
> 1546845758 INFO : Verifying certificate: /C=AU/ST=SICHUAN/L=CHENGDU/O=GANG/OU=GANG/CN=GANG/emailAddress=[975868484@qq.com](mailto:975868484@qq.com)
> 1546845758 INFO : Handshake successful
> 1546845758 INFO : Prepare Verification request
> 1546845758 INFO : Serialization successful
> 1546845758 INFO : MSG0 received
> 1546845758 INFO : Received extended EPID group ID: 0
> 1546845758 INFO : Serialization successful
> 1546845758 INFO : Send to client
> 1546845758 INFO : MSG1 received
> 1546845758 INFO : Retrieving SigRL from IAS
> 1546845758 INFO : sending url: https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v3/sigrl/000013dc
> 1546845760 INFO : Curl cert file: /home/chen/tes/AttestationReportSigningCACert.pem
> **_1546845760 INFO : curl_easy_perform() failed: Problem with the local SSL certificate_**
> **1546845760 INFO : Response status is: 0 1546845760 INFO : Content-Length: 0 1546845760 INFO : Error, processing MSG1 failed**
> 1546845760 INFO : Send to client
> 1546845760 INFO : Remote attestation done
> 
> app output:
> 1546845750 INFO : Certificate "/home/chen/tes/client.txt" set
> 1546845750 INFO : Server running on port: 22222
> 1546845758 INFO : New accept request, starting new session
> 1546845758 INFO : Connection from 127.0.0.1
> 1546845758 INFO : Handshake successful
> 1546845758 INFO : Verification request received
> 1546845758 INFO : Call MSG0 generate
> 1546845758 INFO : Call sgx_get_extended_epid_group_id success
> 1546845758 INFO : Serialization successful
> 1546845758 INFO : Send to client
> 1546845758 INFO : MSG0 response received
> 1546845758 INFO : Call sgx_create_enclave success
> 1546845758 INFO : Enclave created, ID: 2
> 1546845758 INFO : Call enclave_init_ra success
> 1546845758 INFO : Sending msg1 to remote attestation service provider. Expecting msg2 back
> 1546845758 INFO : MSG1 generated Successfully
> 1546845758 INFO : Serialization successful
> 1546845758 INFO : Send to client
> 1546845760 ERROR : Unknown socket error while reading occured!
> 
> @dingelish thanks,my friend.
> i use these certificate to run the offical ra example(sgx-ra-example) is well, but there is no use.

The reason is that your pem file is invalid. If you really needs to run this outdated remote attestation sample, the required pem should work with the following command:
```
curl -1 --tlsv1.2 -v -E /root/sgx/client.pem https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v3/sigrl/00000ABC
```

Here the pem is a **combination** of client.crt and client.key.

**Comment by followinds** [comment]
yes,my local ssl self-certificate file is incorrect. but i follow the offical [course](https://software.intel.com/en-us/articles/how-to-create-self-signed-certificates-for-use-with-intel-sgx-remote-attestation-using) to get it.
do you have other way to get this file?

**Comment by dingelish** [comment]
Have you ever filled out [this](https://software.intel.com/en-us/form/sgx-onboarding) form to register your client key?

If not, you can never get the report from Intel.

**Comment by dingelish** [comment]
If you have the correct crt/key bundle registered to IAS, you can generate the pem using the following commands:
```
openssl pkcs12 -export -in ./client.crt -inkey client.key > client.p12
openssl pkcs12 -in client.p12 -out client.pem -clcerts
```
Then
```
curl -1 --tlsv1.2 -v -E /root/sgx/client.pem https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v3/sigrl/00000ABC
```

**Comment by xiaoshui1994** [comment]
> If you have the correct crt/key bundle registered to IAS, you can generate the pem using the following commands:
> 
> ```
> openssl pkcs12 -export -in ./client.crt -inkey client.key > client.p12
> openssl pkcs12 -in client.p12 -out client.pem -clcerts
> ```
> Then
> 
> ```
> curl -1 --tlsv1.2 -v -E /root/sgx/client.pem https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v3/sigrl/00000ABC
> ```




I have registered for intel. and got my spid and AttestationReportSigningCACert.pem .
I follow your step,but get a error:
root@chen:/home/chen/client# openssl pkcs12 -export -in ./client.crt -inkey client.key > client.p12
Enter Export Password:
Verifying - Enter Export Password:
root@chen:/home/chen/client# 
root@chen:/home/chen/client# openssl pkcs12 -in client.p12 -out client.pem -clcerts
Enter Import Password:
MAC verified OK
Enter PEM pass phrase:
root@chen:/home/chen/client# ls
AttestationReportSigningCACert.pem  client.pem
ca                                  client.pfx
client.cnf                          client.req
client.crt                          client.txt
client.key                          linux-sgx-remoteattestation-master
client.p12
root@chen:/home/chen/client# curl -1 --tlsv1.2 -v -E /root/sgx/client.pem https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v3/sigrl/00000ABC
*   Trying 52.22.58.45...
* Connected to test-as.sgx.trustedservices.intel.com (52.22.58.45) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* error reading X.509 key or certificate file: Error while reading file.
* Closing connection 0
curl: (35) error reading X.509 key or certificate file: Error while reading file.



Is my registration's way incorrect ? but my crt file is passed form intel.

**Comment by dingelish** [comment]
what's the output of
```
curl -1 --tlsv1.2 -v --key client.key --cert client.crt https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v3/sigrl/00000ABC
```

**Comment by xiaoshui1994** [comment]
root@chen:/home/chen/client# curl -1 --tlsv1.2 -v --key client.key --cert client.crt https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v3/sigrl/00000ABC
*   Trying 52.22.58.45...
* Connected to test-as.sgx.trustedservices.intel.com (52.22.58.45) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: The handshake data size is too large.
* Closing connection 0
curl: (35) gnutls_handshake() failed: The handshake data size is too large.

**Comment by dingelish** [comment]
Obviously, your registration to IAS is wrong.

99% of this situation is caused by you're missing the 'Common Name' field in your cert -- doing wrong thing in generating your license. Without properly set it up, IAS cannot finish the TLS handshake.

You need to generate the certificate again and register to IAS again.

**Comment by dingelish** [comment]
Since this issue is not caused by this project, this thread should be closed.

**Comment by xiaoshui1994** [comment]
thank you very much.
i will re-register again carefully.

**Comment by xiaoshui1994** [comment]
could i follow your [step](https://github.com/baidu/rust-sgx-sdk/tree/master/samplecode/ue-ra)(ue-ra     Custom CA/client setup) to get my local ca crt file? and send the crt file to intel.

@dingelish

**Comment by dingelish** [comment]
You can't. Please just follow the instruction provided by Intel and fill up every item of the CSR.

**Comment by xiaoshui1994** [comment]
I'm breaking down. I tried to operate and register three times. I'm sure I filled in every step carefully. Then upload the CRT file to GitHub and provide the download link to intel. When I get the Intel reply to my SPID, I use the curl command line you gave me to test, but the results are the same as before. I don't know what's wrong. i'm sure i filled up every item of the CSR.           [INTEL's  SSL CERTIFICATE COURSE](https://software.intel.com/zh-cn/articles/how-to-create-self-signed-certificates-for-use-with-intel-sgx-remote-attestation-using)

**Comment by dingelish** [comment]
Just go to the official SGX forum and asks for support. The engineers there will help you debug.

https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx

**Comment by dingelish** [comment]
Let me show you a success log a few seconds ago:

```
curl -1 --tlsv1.2 -v --key client.key --cert client.crt https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v3/sigrl/00000ABC

*   Trying 52.22.58.45...
* TCP_NODELAY set
* Connected to test-as.sgx.trustedservices.intel.com (52.22.58.45) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; postalCode=95630; ST=CA; L=Folsom; street=FM1-110; street=1900 Prairie City Rd.; O=Intel Corporation; OU=Hosted by Intel Corporation; OU=Enterprise SSL Pro; CN=test-as.sgx.trustedservices.intel.com
*  start date: Aug 28 00:00:00 2017 GMT
*  expire date: Aug 28 23:59:59 2019 GMT
*  subjectAltName: host "test-as.sgx.trustedservices.intel.com" matched cert's "test-as.sgx.trustedservices.intel.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Organization Validation Secure Server CA
*  SSL certificate verify ok.
> GET /attestation/sgx/v3/sigrl/00000ABC HTTP/1.1
> Host: test-as.sgx.trustedservices.intel.com
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< content-length: 0
< request-id: f11b321fff8b41bfb2f0aa89a074c704
< date: Fri, 11 Jan 2019 06:34:45 GMT
< Connection: keep-alive
<
* Connection #0 to host test-as.sgx.trustedservices.intel.com left intact
```

**Comment by xiaoshui1994** [comment]
Ok,i know. thanks
