### ISSUE TITLE
Documentation for debugging

### ISSUE THREAD

**Issue by tomtau** [apache/teaclave-sgx-sdk#53]
There's a `sgx-gdb`. It'd be good to have a tutorial / documentation how to debug Rust enclave code with it, ideally if it can be setup with a visual debugger (e.g. for Rust code, one can use this extension in VSCode: https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb )

**Comment by tomtau** [comment]
A small bounty here: https://www.bountysource.com/issues/68777276-documentation-for-debugging

**Comment by morangeous** [comment]
Hey Man, do you know how to use sgx-gdb in the docker? If you know that, could you give me a hand?
Thanks a lot :)

**Comment by dingelish** [comment]
I'll write something on the wiki page to show how to use `sgx-gdb` tonight :)

**Comment by dingelish** [comment]
@morangeous @tomtau 
Basic debugging instructions could be found in the first wiki page:
https://github.com/baidu/rust-sgx-sdk/wiki/Debugging-a-local-Rust-SGX-enclave-in-docker-with-sgx-gdb

**Comment by tomtau** [comment]
I think those basic instructions are fine for now and a good start; one could then just hook up gdb tooling to `sgx-gdb` and go from there
