### ISSUE TITLE
use memalign instead of malloc in `sgx_alloc` crate?

### ISSUE THREAD

**Issue by cbeck88** [apache/teaclave-sgx-sdk#64]
Hi, I notice that at this line you use `malloc` to implement the global allocator:

https://github.com/baidu/rust-sgx-sdk/blob/9d4fa0f603e44bb82efae9d913c586a498b7d9da/sgx_alloc/src/lib.rs#L117

We did something similar but we can have an issue because rust global allocator API allows user to request both size and alignment.

This led to panics when we tried to run `hashbrown` crate in our enclave, see here: https://github.com/Amanieu/hashmap_core/issues/9#issuecomment-455901603

The maintainer was correct, this issue went away when we used `memalign` instead of `malloc` to implement the rust standard allocator.

It is not that common that something requires 16 byte alignment, and malloc by default provides 8 byte alignment for everything so it usually works. But it is a hard bug to figure out if you don't already know this

**Comment by dingelish** [comment]
wow. seems that you are right. i'll push the commit today (revert to the previous `posix_memalign` version)

**Comment by cbeck88** [comment]
we were using this function from intel, i think you wrap it in `tstd`:

https://github.com/intel/linux-sgx/blob/master/common/inc/tlibc/stdlib.h#L101

Thanks! HTH

**Comment by dingelish** [comment]
Sounds good! And do you think using `align` [here](https://github.com/baidu/rust-sgx-sdk/blob/212d9f4bab149d967b73bc6eb0a48fe459cd98eb/sgx_alloc/src/lib.rs#L160) is correct?

**Comment by cbeck88** [comment]
Yeah that looks right to me!

**Comment by dingelish** [comment]
Goooood! Just let me tweak a little and test the fix. I'll push a fix shortly!

**Comment by dingelish** [comment]
Just pushed. See if it's ok. Will push to crates.io later tonight with a new version number `v1.0.6` of everything.

Thanks!
