### ISSUE TITLE
SGX UnitTests with inputs

### ISSUE THREAD

**Issue by elichai** [apache/teaclave-sgx-sdk#65]
Hi @dingelish,
I need to pass inputs to some of the unittests (pointers to later pass to ocalls), but I couldn't use `rsgx_unit_test` because it only accepts a `&'static Fn()` which means regular functions that receive nothing.
I get why you did that, I just wanted to know if you think there's something to do, 
right now what I did is implement my own function as the following:
(which is a copy of your function but with a FnOnce instead of a static Fn)

```
    fn core_unitests<F, R>(ncases: &mut u64, failurecases: &mut Vec<String>, f:F, name: &str )
        where F: FnOnce() -> R + UnwindSafe {
        *ncases = *ncases + 1;
        match std::panic::catch_unwind (|| { f(); } ).is_ok() {
            true => {
                println!("{} {} ... {}!",
                         "testing",
                         name,
                         "\x1B[1;32mok\x1B[0m");
            },
            false => {
                println!("{} {} ... {}!",
                         "testing",
                         name,
                         "\x1B[1;31mfailed\x1B[0m");
                failurecases.push(String::from(name));
            },
        }
    }
```

**Comment by dingelish** [comment]
good idea! could you please provide an PR and i can merge it today and release 1.0.6 tonight!

**Comment by elichai** [comment]
Ok, Thanks! will do (interesting to see if it will work good with the macro and closures)

**Comment by dingelish** [comment]
as long as it passes the unit-test code sample!

**Comment by elichai** [comment]
Testing now. BTW, why don't you set up a CI that tests all the sample code?
We use drone.io on a SGX supporting server.
(that's our config, it's not the latest because our latest code isn't public yet but it's pretty close: https://github.com/enigmampc/enigma-core/blob/master/.drone.yml )

**Comment by dingelish** [comment]
thanks so much!!!

i have been searching for CI solutions for a while. seems that drone is good. just one small question: how should i test remote attestation on this sgx machine? should i upload the client crt/key/spid to it?

**Comment by elichai** [comment]
hmmm we have a proxy for the remote attestation. are you doing the mtls directly from rust?
if so I think it's possible to add a `secret` to drone that isn't checked in to the git.

And yeah drone is pretty cool, it took us a while to find a CI that we could use with sgx, it works great :)

**Comment by dingelish** [comment]
Thanks again, @elichai !

**Comment by dingelish** [comment]
btw. @elichai , do you mind if i change `ident` to `path`?

```
 macro_rules! rsgx_unit_tests {
     (
-        $($f : ident),*
+        $($f : path),*
     )
```

or I can create a new macro to support `path` :-)

**Comment by elichai** [comment]
I don't mind. I'm not sure what exactly does it change at the UX level

**Comment by dingelish** [comment]
ok. so I'll change it to `path` to support testing `mod::mod::func`.

**Comment by elichai** [comment]
That will actually be very helpful :)
