### ISSUE TITLE
support for rustup componenets

### ISSUE THREAD

**Issue by elichai** [apache/teaclave-sgx-sdk#78]
Hi,
I would like to request if in the next version when you lock the nightly version if you could try to aim for a nightly that contains also these components:  `clippy, rls, rust-analysis, rust-src`
(You can check via `rustup component list` )

Thanks,
Elichai.

**Comment by dingelish** [comment]
No problem!

**Comment by dingelish** [comment]
```
rustup component add clippy rls rust-analysis rust-src
```
will be added

**Comment by elichai** [comment]
Thanks!

**Comment by dingelish** [comment]
Hi @elichai , I notice that some nightly builds do not provide clippy (cannot find it in `rustup component list`). Do you know if there is a list to see what date it is available? Thanks!

**Comment by dingelish** [comment]
Just found this
https://rust-lang.github.io/rustup-components-history/

Do you have any idea about what nightly date we should use (to support built-in clippy)?

**Comment by elichai** [comment]
It actually doesn't look so good right now.
Clippy seems to fall a apart a bit right now https://github.com/rust-lang/rust/pull/59617

And if this is correct then 23-3  :(
https://rust-lang-nursery.github.io/rust-toolstate/

Edit: or 22-3 not sure if that is since the version was released or since that day.

**Comment by elichai** [comment]
@dingelish If I understand correctly everything is fixed now :)
https://github.com/rust-lang/rust/pull/59810
https://rust-lang-nursery.github.io/rust-toolstate/
