### ISSUE TITLE
failed to run 'pcl'

### ISSUE THREAD

**Issue by lhfbc** [apache/teaclave-sgx-sdk#80]
When I run the pcl example, It panicked.
1. one terminal
```
cd pcl-seal/bin
./app
```
2. another terminal
```
RUST_BACKTRACE=1 cargo run
```
it panicked, log as following
```
rust-sgx-sdk/samplecode/pcl/pcl-user$ RUST_BACKTRACE=1 cargo run
warning: Enclave encryption key: 6E1BE2D5F18478BCEFB4D0554265D9C9
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/pcl-user`
Starting ue-ra-client
Connecting to localhost:3443
Imported seal key = 6E1BE2D5F18478BCEFB4D0554265D9C9
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/da6ab956e1002517803ecd38b904504a1223274b/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/da6ab956e1002517803ecd38b904504a1223274b/src/libcore/result.rs:798
  10: pcl_user::main
             at src/main.rs:102
  11: std::rt::lang_start::{{closure}}
             at /rustc/da6ab956e1002517803ecd38b904504a1223274b/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/da6ab956e1002517803ecd38b904504a1223274b/src/libstd/rt.rs:64
  16: main
  17: __libc_start_main
  18: _start
```

**Comment by lhfbc** [comment]
I came into another error when using docker, 
1. one terminal
```
docker run -v ${PWD}/rust-sgx-sdk:/root/sgx -ti --device /dev/isgx baiduxlab/sgx-rust
root@9489f9f5051b:~# cd sgx/samplecode/pcl
root@9489f9f5051b:~/sgx/samplecode/pcl# make
root@9489f9f5051b:~/sgx/samplecode/pcl# cd pcl-seal/bin/
root@9489f9f5051b:~/sgx/samplecode/pcl/pcl-seal/bin# ./app 
[+] Home dir is /root
[-] Open token file /root/enclave.token error! Will create one.
[-] Init Enclave Failed SGX_ERROR_NO_DEVICE!
root@9489f9f5051b:~/sgx/samplecode/pcl/pcl-seal/bin# ls /dev/isgx 
/dev/isgx
```

**Comment by dingelish** [comment]
> I came into another error when using docker,
> 
> 1. one terminal
> 
> ```
> docker run -v ${PWD}/rust-sgx-sdk:/root/sgx -ti --device /dev/isgx baiduxlab/sgx-rust
> root@9489f9f5051b:~# cd sgx/samplecode/pcl
> root@9489f9f5051b:~/sgx/samplecode/pcl# make
> root@9489f9f5051b:~/sgx/samplecode/pcl# cd pcl-seal/bin/
> root@9489f9f5051b:~/sgx/samplecode/pcl/pcl-seal/bin# ./app 
> [+] Home dir is /root
> [-] Open token file /root/enclave.token error! Will create one.
> [-] Init Enclave Failed SGX_ERROR_NO_DEVICE!
> root@9489f9f5051b:~/sgx/samplecode/pcl/pcl-seal/bin# ls /dev/isgx 
> /dev/isgx
> ```

After entering docker container, the very first thing is to start aesm service daemon:
```
# /opt/intel/libsgx-enclave-common/aesm/aesm_service
```

**Comment by dingelish** [comment]
> When I run the pcl example, It panicked.
> 
> 1. one terminal
> 
> ```
> cd pcl-seal/bin
> ./app
> ```
> 1. another terminal
> 
> ```
> RUST_BACKTRACE=1 cargo run
> ```
> it panicked, log as following
> 
> ```
> rust-sgx-sdk/samplecode/pcl/pcl-user$ RUST_BACKTRACE=1 cargo run
> warning: Enclave encryption key: 6E1BE2D5F18478BCEFB4D0554265D9C9
>     Finished dev [unoptimized + debuginfo] target(s) in 0.07s
>      Running `target/debug/pcl-user`
> Starting ue-ra-client
> Connecting to localhost:3443
> Imported seal key = 6E1BE2D5F18478BCEFB4D0554265D9C9
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }', src/libcore/result.rs:997:5
> stack backtrace:
>    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
>              at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
>    1: std::sys_common::backtrace::_print
>              at src/libstd/sys_common/backtrace.rs:70
>    2: std::panicking::default_hook::{{closure}}
>              at src/libstd/sys_common/backtrace.rs:58
>              at src/libstd/panicking.rs:200
>    3: std::panicking::default_hook
>              at src/libstd/panicking.rs:215
>    4: std::panicking::rust_panic_with_hook
>              at src/libstd/panicking.rs:478
>    5: std::panicking::continue_panic_fmt
>              at src/libstd/panicking.rs:385
>    6: rust_begin_unwind
>              at src/libstd/panicking.rs:312
>    7: core::panicking::panic_fmt
>              at src/libcore/panicking.rs:85
>    8: core::result::unwrap_failed
>              at /rustc/da6ab956e1002517803ecd38b904504a1223274b/src/libcore/macros.rs:16
>    9: <core::result::Result<T, E>>::unwrap
>              at /rustc/da6ab956e1002517803ecd38b904504a1223274b/src/libcore/result.rs:798
>   10: pcl_user::main
>              at src/main.rs:102
>   11: std::rt::lang_start::{{closure}}
>              at /rustc/da6ab956e1002517803ecd38b904504a1223274b/src/libstd/rt.rs:64
>   12: std::panicking::try::do_call
>              at src/libstd/rt.rs:49
>              at src/libstd/panicking.rs:297
>   13: __rust_maybe_catch_panic
>              at src/libpanic_unwind/lib.rs:92
>   14: std::rt::lang_start_internal
>              at src/libstd/panicking.rs:276
>              at src/libstd/panic.rs:388
>              at src/libstd/rt.rs:48
>   15: std::rt::lang_start
>              at /rustc/da6ab956e1002517803ecd38b904504a1223274b/src/libstd/rt.rs:64
>   16: main
>   17: __libc_start_main
>   18: _start
> ```

Did you place the cert/key/spid files as [instructed](https://github.com/baidu/rust-sgx-sdk/tree/master/samplecode/pcl#build-and-run)?

> To run, please put your IAS registration files (client.key, client.crt and spid.txt) in under pcl_seal/bin/

The cert/key/spid has to pass the [validation](https://github.com/baidu/rust-sgx-sdk/tree/master/samplecode/mutual-ra#requirements):

> ## Requirements
> 
> To use this code sample, one needs to register at Intel website for dev IAS service access. Once the registration is finished, the following stuff should be ready:
> 
> 1. An SPID assigned by Intel
> 2. IAS client certificate such as `client.crt`
> 3. IAS client private key such as `client.key`
> 
> To check whether your IAS registration is complete, please perform the following query with your IAS client certificate and private key:
> 
> ```
> curl -1 --tlsv1.2 -v --key client.key --cert client.crt https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v3/sigrl/00000ABC
> ```
> 
> Here `00000ABC` is a fake group id which is only used here for testing connection. If this http request can successfully obtain an HTTP status code (no matter which code it is), your IAS service registration should be fine.

**Comment by lhfbc** [comment]
Thanks a lot !!!
