### ISSUE TITLE
Could this sdk be used on Windows?

### ISSUE THREAD

**Issue by lhfbc** [apache/teaclave-sgx-sdk#81]
The docker runs very well on Linux. Thanks a lot~~

Could it run on Windows? 
I installed docker software on Windows and pulled down the sgx-rust image.
I run into trouble when trying to run the image, as I don't know how to map the sgx device into the docker.
After I enabled SGX in BIOS and installed the SGX PSW, I can see the device in 'device manager' as follows.
![image](https://user-images.githubusercontent.com/45928776/54985697-43ce9900-4fec-11e9-8b90-3c38a1bfc006.png)

Would you please give some advice?
Any advice is always welcome~~

**Comment by dingelish** [comment]
The device shown in the figure is TPM, not Intel SGX.

I don't have a plan for Windows support -- but I believe it's do-able.

**Comment by lhfbc** [comment]
Thanks.
