### ISSUE TITLE
rsgx unit tests return output

### ISSUE THREAD

**Issue by elichai** [apache/teaclave-sgx-sdk#82]
Hi,
rsgx_unit_tests in awesome. it looks great and works great.
the only problem is that because it's unrelated to rust's test suite we need to somehow return -1 from the threads if there was any failure, so that CI's will fail this.

I see a couple of ways to do this. 
1. That `rsgx_unit_test_end()` will return the length of `failurecases`.
2. that `rsgx_unit_test_end()` will return `failurecases.is_empty()`.
3.  maybe `failurecases` will panic at the end if `failurecases` isn't empty? I'm not sure what will be the behavior here.

then you could pass this output back via the edl and assert on the untrusted side (or in the trusted side but again, I have a feeling that assertion in the enclave in tests can crash the whole process)

what do you think? tell me what you decide and I can make a PR to change the functions,macro and the samplecode accordingly.

Thanks.

**Comment by dingelish** [comment]
Hi Elichai,

I've been thinking about the same problem for a while -- in my current drone script I only "grep" the output for " 0 failed" for a hack ([ugly](https://github.com/dingelish/serde-sgx/blob/ba327d614a0eaaa1e124f129d4316ffd49014362/.drone.yml#L16)!).

Personally, I like (1) -- it provides more information which might be useful in CI. What do you think? I'm very glad to merge PR :-)

**Comment by elichai** [comment]
yeah I also this 1 is the best solution for the function and macro.

I hoped we can make the thread return -1 from the enclave it self but I think that's not possible without UB for the other tests, right?
Maybe I'll try to play with it a bit.

**Comment by dingelish** [comment]
what's the UB?  :joy:

**Comment by elichai** [comment]
That it would probably just crash all of the tests? lol

Because the C bridge (edl) can't decipher unwinding and it can treat it as process exit or something similiar

**Comment by elichai** [comment]
So it seems to me that 1 is the best option for knowing the result.
and the only option (if you can think of another please let me know) to fail the test visibly without crashing the other tests, is by returning some value and asserting on the outside.

If you agree I'll make a PR tomorrow to change both `sgx_tunittest` and the `sample_code/unit-test`

**Comment by dingelish** [comment]
Yeah I like the idea of asserting the value of failed count on the outside! I'll merge your PR 😆
