### ISSUE TITLE
Upgrade to Intel SGX Linux 2.5 Release 

### ISSUE THREAD

**Issue by tomtau** [apache/teaclave-sgx-sdk#85]
https://github.com/intel/linux-sgx/commit/d10cabebb5512878e84f5d21cdf27c39c428ffe2

**Comment by tomtau** [comment]
https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-linux-2.5-release

**Comment by dingelish** [comment]
@tomtau  Please check for the most recent release for 2.5 support. Thanks!

**Comment by dingelish** [comment]
@tomtau @elichai @cbeck88 @matthias-g @davidp94 @bradyjoestar 

I think the current codes seems ready to be released. Let me know if you have any updates/comments for this version. Thanks! I'd like to add a release tag and publish them to crates.io within a few days :-)

**Comment by tomtau** [comment]
@dingelish it looks ok. The only comment I'd have is not relevant to 2.5 support: in the release notes, you mention that "SGX forks" of third party crates are going to be maintained in https://github.com/mesalock-linux (and there are some of them). I think this is a good idea.
If the forks are maintained there, perhaps the ones in https://github.com/baidu/rust-sgx-sdk/tree/master/third_party can be deleted and related sample code's Cargo.toml dependencies can be updated to use the forked repository / crate (instead of being specified against rust-sgx-sdk's relative paths).

**Comment by dingelish** [comment]
Got it.

We need to choose the method of dependency (sgx_tstd/trts/...) organization on the forked repos. For cargo support, we have options of (1) crates.io and (2) github. For xargo support, we can only depends on github.

Should we unify them to depends on github repo? Currently those forked branches depend on crates.io when using Cargo, depends on github when using Xargo.

**Comment by tomtau** [comment]
Why does Xargo imply git-only dependencies?
I haven't been following that std-aware cargo proposal https://github.com/baidu/rust-sgx-sdk/issues/75 but if it has the same issue as Xargo, perhaps unifying them will make sense?

**Comment by dingelish** [comment]
Xargo depends on a crate named "std" -- which means it cannot acquire it from crates.io :-(

std-aware cargo -- seems beautiful, but is it going to be ready within a year?

**Comment by tomtau** [comment]
I see. Probably it makes sense to keep it as it currently is.

std-aware cargo may not be of the highest priority, but we'll see if anything materialises there.

**Comment by elichai** [comment]
Hmm I actually don't mind if it's from crates.io or github, if just needs to be consistent across all the repos.
And If you do chose crates.io you I think you should lock the version, because minor updates aren't acceptable without updating the rustc compiler and everything else. 

Until now I used github dependencies because that's what works with the third_parties and it's easy to tag the version.

**Comment by tomtau** [comment]
@dingelish just noticed 2.5 had a few more AESM errors https://github.com/intel/linux-sgx/blob/d10cabebb5512878e84f5d21cdf27c39c428ffe2/psw/ae/inc/internal/aesm_error.h#L67

versus
https://github.com/baidu/rust-sgx-sdk/commit/2647c31ee40403c8028ef880b6eaede027f71aae#diff-797c9e91cf9c364a4c9108ebcf1abf73R203

I guess the missing ones won't matter, as they are related to things not yet supported here, e.g. DCAP?

**Comment by dingelish** [comment]
@tomtau Hmmm, sounds like Intel SGX SDK is not exposing APIs which depends on `aesm_error_t`, such as [`oal_get_launch_token`](https://github.com/intel/linux-sgx/blob/d10cabebb5512878e84f5d21cdf27c39c428ffe2/psw/uae_service/uae_wrapper/src/uae_api.cpp#L102). But I can add it in sgx_types quickly.

Update:
Find some APIs depends on it
https://github.com/intel/linux-sgx/blob/d10cabebb5512878e84f5d21cdf27c39c428ffe2/common/inc/internal/oal/uae_oal_api.h#L54

**Comment by dingelish** [comment]
I intend not to add them now. It seems that `common/inc/internal` directory is not exposed to public directly. I'll add them in the next release :-)

**Comment by dingelish** [comment]
For the forked repos in `mesalock-linux` organization, I'll update the master branch to use the SDK from github, and maintain some new test cases which relies on crates.io.

**Comment by tomtau** [comment]
This one can be closed after the latest release
