### ISSUE TITLE
make `quote_type` configable?

### ISSUE THREAD

**Issue by bradyjoestar** [apache/teaclave-sgx-sdk#87]
I have meet the same error #71  #72 
https://github.com/baidu/rust-sgx-sdk/blob/99c5d5c461f5ac972ca61d3ec20b43c10ea142c5/samplecode/pcl/pcl-seal/enclave/src/lib.rs#L404

https://github.com/baidu/rust-sgx-sdk/blob/99c5d5c461f5ac972ca61d3ec20b43c10ea142c5/samplecode/mutual-ra/enclave/src/lib.rs#L402

It is difficult for enclave to distinguish it, how about we add a arg (i.e `quote_type`) in the create_attestation_report()?

If started by `./app` It will use default `SGX_LINKABLE_SIGNATURE`;
if started by `./app --unlink`, it will use `SGX_UNLINKABLE_SIGNATURE`.

I could help if need it. :beers:

**Comment by dingelish** [comment]
Good suggestion! I'd happy to merge PR! Thanks!

**Comment by bradyjoestar** [comment]
Got it. :smile:
