### ISSUE TITLE
trusted mult-party computing that use sgx as trusted computing base

### ISSUE THREAD

**Issue by bradyjoestar** [apache/teaclave-sgx-sdk#89]
I'm recently working on how to implement trusted mult-party computing based all participants use sgx as trusted computing base.

All participants know the whole logic but we should protect the data privacy.

May I create a pr when I have developed and it is put into samplecode? Your review is important to me.

Thank you. :smiley:

**Comment by dingelish** [comment]
of course! thanks for your contribution!

**Comment by bradyjoestar** [comment]
Got it. :ok_hand:

**Comment by dingelish** [comment]
Seems to work as claimed in Readme. Thank you!
