### ISSUE TITLE
Depending on JHI?

### ISSUE THREAD

**Issue by bl4ck5un** [apache/teaclave-sgx-sdk#9]
As ME is not supported in the docker image, JHI seems to be unnecessary too: https://github.com/baidu/rust-sgx-sdk/blob/6535a00bab5388ea5c95e5992f7112faa9fad5cb/dockerfile/Dockerfile#L49

**Comment by dingelish** [comment]
Thanks! I'll fix it very soon :)

**Comment by dingelish** [comment]
Finally I got time for this. Thanks to @bl4ck5un !
