### ISSUE TITLE
sgx_libc broken by alloc dependency

### ISSUE THREAD

**Issue by brenzi** [apache/teaclave-sgx-sdk#95]
Since a [recent commit](https://github.com/baidu/rust-sgx-sdk/commit/2647c31ee40403c8028ef880b6eaede027f71aae#diff-f965492ded47593def65c0d19a035fa0R38) I can't build my sgx project anymore:
```
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/abrenzikofer/.cargo/git/checkouts/rust-sgx-sdk-fc8771c5c45bde9a/2647c31/sgx_libc/src/lib.rs:38:1
   |
38 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(alloc)] to the crate attributes to enable

error: aborting due to previous error
```

**Comment by dingelish** [comment]
Hi @brenzi , `#![feature(alloc)]` has been stabilized in the most recent Rust compiler. Could you please upgrade to nightly-2019-04-26 if you use the master branch? Thanks!

**Comment by brenzi** [comment]
indeed, thanks
