### ISSUE TITLE
v1.0.7 breaks our code based on sealeddata example: undefined reference to `u_thread_wait_event_ocall'

### ISSUE THREAD

**Issue by brenzi** [apache/teaclave-sgx-sdk#96]
```
./lib/libenclave.a(sgx_tstd-3b39c27caf5563ab.sgx_tstd.3n9yueni-cgu.8.rcgu.o): In function `sgx_tstd::sync::mutex::SgxThreadMutexInner::lock':
sgx_tstd.3n9yueni-cgu.8:(.text._ZN8sgx_tstd4sync5mutex19SgxThreadMutexInner4lock17h3387cf2c2a22507cE+0x195): undefined reference to `u_thread_wait_event_ocall'
./lib/libenclave.a(sgx_tstd-3b39c27caf5563ab.sgx_tstd.3n9yueni-cgu.8.rcgu.o): In function `sgx_tstd::sync::mutex::SgxThreadMutexInner::unlock':
sgx_tstd.3n9yueni-cgu.8:(.text._ZN8sgx_tstd4sync5mutex19SgxThreadMutexInner6unlock17hcd0e85bf54896331E+0xd6): undefined reference to `u_thread_set_event_ocall'
c
```

code: https://github.com/scs/substraTEE-worker/tree/brenzi-crypto-helper-fixing

**Comment by dingelish** [comment]
Hi @brenzi ,

I managed to fix this by:
(1) Copy and overwrite edl/sgx_tstd.edl, edl/sgx_fd.edl. Add edl/sgx_time.edl.
(2) Copy and overwrite the entire rust-sgx-sdk/common directory to substratee's common

**Comment by dingelish** [comment]
I can submit a PR if you like :-)

**Comment by dingelish** [comment]
Here's my patch
https://github.com/dingelish/substraTEE-worker/commit/d75ce066dc7fd70685265133e651213c68909651

**Comment by brenzi** [comment]
Wow, I sure hope I may buy you a beer one day!
merged your commit into our master.
