### ISSUE TITLE
java or go client for ue-ra

### ISSUE THREAD

**Issue by bradyjoestar** [apache/teaclave-sgx-sdk#98]
we have implemented a untrusted side client in `ue-ra`,  I think it not limit rust but for all language that support `tls` library. Is this right?
I'd like to develop java or go client for more possible scenarios. 😄 :

**Comment by dingelish** [comment]
You're right! And I'd like to merge your code sample if possible!

**Comment by bradyjoestar** [comment]
Got it! :ok_hand:

**Comment by dingelish** [comment]
Awesome!
