### ISSUE TITLE
ignore more files in `.gitignore`

### ISSUE THREAD

**Issue by bradyjoestar** [apache/teaclave-sgx-sdk#99]
How about we ignore some generated files in `.gitignore` just like `intel/linux-sgx`? Thanks!:smile:

```
#object file
*.o

#library
*.a

#share object
*.so
*.so.*

#generated proxy
*_u.c
*_u.h
*_t.c
*_t.h
```

**Comment by dingelish** [comment]
Sure! c2cdb65efd2240dc497e854ee0f4d0fc2f39775e
